/**
 * Banco NUEVO (anti-spoiler) — algebra-lineal
 *
 * Mapa { [sectionId]: { quiz2: { tf, mc, ms }, flashcards2: [...] } }.
 * content.js mergea esto sobre las secciones por id (sec.quiz2 / sec.flashcards2).
 * Generado para autoevaluación: opciones homogéneas, sin pistas de forma.
 */
export default {
  '8': {
    quiz2: {
      tf: [
        { id: 'tf2-8-1', q: 'La introducción sostiene que el Álgebra Lineal perdió relevancia frente al avance de la computación.', a: false, explain: 'Afirma lo contrario: su importancia se elevó en proporción directa al aumento del poder de las computadoras.' },
        { id: 'tf2-8-2', q: 'El apunte menciona el procesamiento paralelo de datos y los cálculos a gran escala como puente entre la computación y el Álgebra Lineal.', a: true, explain: 'Ese crecimiento explosivo es lo que liga ambas disciplinas según la introducción.' },
        { id: 'tf2-8-3', q: 'El buscador cuyo algoritmo se describe se patentó dos años después de que empezara su diseño.', a: true, explain: 'El diseño arrancó en 1996 y la patente del algoritmo llegó en 1998.' },
        { id: 'tf2-8-4', q: 'La palabra que da nombre al buscador proviene de una unidad de medida informática.', a: false, explain: 'Proviene de googol, el nombre en inglés del número $10^{100}$, no de una unidad de medida.' },
        { id: 'tf2-8-5', q: 'Para el apunte, la mayoría de los problemas económicos queda resuelta con un solo valor numérico.', a: false, explain: 'Dice que eso es muy raro: lo usual es trabajar con gran cantidad de datos, y por eso aparecen matrices.' },
      ],
      mc: [
        {
          id: 'mc2-8-1',
          q: 'La introducción atribuye el aumento de relevancia de la materia principalmente a:',
          options: [
            'La reducción del costo de los libros de texto',
            'La incorporación de la materia en más carreras',
            'El crecimiento del poder de cómputo disponible',
            'La simplificación de sus contenidos teóricos',
          ],
          correctIndex: 2,
          explain: 'Cada generación de equipos y programas dispara una demanda de capacidades aún mayores.',
        },
        {
          id: 'mc2-8-2',
          q: 'El nombre del buscador surge como variación fonética de una palabra que designa:',
          options: [
            'Al número $10^{100}$',
            'Al número $10^{10}$',
            'A la cantidad de páginas indexadas',
            'A la velocidad de respuesta del sistema',
          ],
          correctIndex: 0,
          explain: 'Googol es el nombre en inglés de $10^{100}$.',
        },
        {
          id: 'mc2-8-3',
          q: 'La meta que el apunte asocia al diseño original del buscador consistía en que:',
          options: [
            'La primera página listada fuera siempre la más visitada del tema',
            'El sistema respondiera en menos de un segundo por consulta',
            'Los resultados se ordenaran según la antigüedad de cada sitio',
            'Al menos una de las diez primeras páginas resultara útil al usuario',
          ],
          correctIndex: 3,
          explain: 'Ese era el objetivo inicial que el apunte enuncia junto al origen del nombre.',
        },
        {
          id: 'mc2-8-4',
          q: 'La cuantificación matemática de las magnitudes económicas se apoya, según el apunte, en:',
          options: [
            'El concepto de número real',
            'El concepto de número entero',
            'El concepto de matriz inversa',
            'El concepto de máximo común divisor',
          ],
          correctIndex: 0,
          explain: 'Con los reales se representan precios, salarios, tasas, beneficios y costos.',
        },
        {
          id: 'mc2-8-5',
          q: 'El prejuicio estudiantil que la introducción intenta desarmar consiste en creer que la materia:',
          options: [
            'Requiere demasiadas horas de práctica semanal',
            'Trata temas abstractos sin utilidad concreta',
            'Depende exclusivamente de herramientas informáticas',
            'Repite contenidos ya vistos en la escuela media',
          ],
          correctIndex: 1,
          explain: 'Por eso el apunte se compromete a ir mostrando aplicaciones en la vida diaria.',
        },
      ],
      ms: [
        {
          id: 'ms2-8-1',
          q: '¿Qué magnitudes económicas enumera explícitamente el apunte?',
          options: ['Salarios', 'Tasas de desempleo', 'Costos', 'Probabilidades', 'Tipos de cambio'],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La lista incluye precios, salarios, utilidades, probabilidades, tasas de inflación y de desempleo, beneficios y costos; el tipo de cambio no figura.',
        },
        {
          id: 'ms2-8-2',
          q: '¿Qué datos sobre el origen del buscador aporta el apunte?',
          options: [
            'Sus creadores tenían 23 años',
            'El trabajo de diseño empezó en 1996',
            'El algoritmo se llama PageRank',
            'La patente se obtuvo en 1998',
            'La empresa se fundó en Palo Alto',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La ubicación geográfica no aparece en ninguna parte del texto.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-8-1', front: 'Motor del crecimiento del Álgebra Lineal', back: 'El aumento del poder de las computadoras: cada generación de hardware y software exige capacidades mayores.' },
      { id: 'fc2-8-2', front: 'Puente con la ciencia de la computación', back: 'El crecimiento explosivo del procesamiento paralelo de datos y de los cálculos a gran escala (Big Data).' },
      { id: 'fc2-8-3', front: 'Valor de la materia según el apunte', back: 'Mayor valor potencial en campos científicos y de negocios que cualquier otra materia de matemáticas.' },
      { id: 'fc2-8-4', front: 'De dónde salen las matrices en economía', back: 'De que casi ningún problema económico se define con un solo dato: hay que trabajar con muchos a la vez.' },
      { id: 'fc2-8-5', front: 'Cronología del buscador', back: '1996: dos jóvenes de 23 años empiezan el diseño. 1998: se patenta el algoritmo PageRank.' },
      { id: 'fc2-8-6', front: 'Googol', back: 'Nombre en inglés del número $10^{100}$; “Google” es su variación fonética.' },
      { id: 'fc2-8-7', front: 'Meta original del buscador', back: 'Que al menos una de las diez primeras páginas mostradas contenga información útil para quien consulta.' },
    ],
  },
  '9': {
    quiz2: {
      tf: [
        { id: 'tf2-9-1', q: 'El apunte trabaja con la convención de que el cero pertenece a los números naturales.', a: true, explain: 'Menciona ambas convenciones y adopta $\\mathbb{N} = \\{0, 1, 2, 3, \\dots\\}$.' },
        { id: 'tf2-9-2', q: 'La resta de dos naturales cualesquiera siempre da otro natural.', a: false, explain: 'No es cerrado bajo la sustracción: llegando a cero no se puede seguir saltando a la izquierda.' },
        { id: 'tf2-9-3', q: 'El número $-n$ se define como el resultado de dar $n$ pasos a la izquierda partiendo de cero.', a: true, explain: 'Por eso resulta simétrico de $n$ y cumple $n + (-n) = 0$.' },
        { id: 'tf2-9-4', q: 'Un número con expansión decimal periódica como $-9{,}1\\overline{35}$ queda fuera de los racionales.', a: false, explain: 'El Ejemplo 1.1 lo incluye explícitamente entre los números racionales.' },
        { id: 'tf2-9-5', q: 'El conjunto de los enteros es cerrado tanto para la suma como para la sustracción.', a: true, explain: 'Es el motivo de su construcción: permitir restar sin salirse del conjunto.' },
      ],
      mc: [
        {
          id: 'mc2-9-1',
          q: 'La condición que aparece en la definición del conjunto de los racionales y que no puede omitirse es:',
          options: [
            'Que el numerador sea positivo',
            'Que el denominador sea distinto de cero',
            'Que la fracción esté simplificada',
            'Que el numerador sea menor que el denominador',
          ],
          correctIndex: 1,
          explain: '$\\mathbb{Q} = \\left\\{ \\tfrac{a}{b} \\,/\\, a \\in \\mathbb{Z};\\ b \\in \\mathbb{Z};\\ b \\neq 0 \\right\\}$.',
        },
        {
          id: 'mc2-9-2',
          q: 'La justificación que da el apunte para decir que los naturales no tienen máximo es que:',
          options: [
            'La recta numérica no tiene extremo derecho dibujado',
            'Siempre puede definirse una fracción intermedia',
            'Los enteros negativos compensan a los positivos',
            'Sumando 1 a cualquier candidato se obtiene uno mayor',
          ],
          correctIndex: 3,
          explain: 'La operación de “añadir 1” alcanza para superar a cualquier número que creamos el mayor.',
        },
        {
          id: 'mc2-9-3',
          q: 'La relación “$n$ es menor que $m$” se define en el apunte como:',
          options: [
            'Existe $p \\in \\mathbb{N}$ tal que $n = m - p$',
            'Existe $p \\in \\mathbb{Z}$ tal que $n \\cdot p = m$',
            'Existe $p \\in \\mathbb{N}$ tal que $n = m + p$',
            'Existe $p \\in \\mathbb{Q}$ tal que $n / p = m$',
          ],
          correctIndex: 0,
          explain: 'Se define a través de la sustracción, con $p$ jugando el rol de la diferencia.',
        },
        {
          id: 'mc2-9-4',
          q: 'El papel del cero dentro de la suma se describe diciendo que:',
          options: [
            'Absorbe cualquier número con el que se opere',
            'Invierte el signo del número al que se suma',
            'Deja sin cambios al número al que se suma',
            'Duplica el valor del número al que se suma',
          ],
          correctIndex: 2,
          explain: 'Es el elemento neutro: sumar cero equivale a no moverse en la recta.',
        },
        {
          id: 'mc2-9-5',
          q: 'La cadena de inclusiones que enuncia la Observación 1 es:',
          options: [
            '$\\mathbb{Q} \\subset \\mathbb{Z} \\subset \\mathbb{N}$',
            '$\\mathbb{N} \\subset \\mathbb{Z} \\subset \\mathbb{Q}$',
            '$\\mathbb{Z} \\subset \\mathbb{N} \\subset \\mathbb{Q}$',
            '$\\mathbb{N} \\subset \\mathbb{Q} \\subset \\mathbb{Z}$',
          ],
          correctIndex: 1,
          explain: 'Cada conjunto de la cadena contiene al anterior.',
        },
      ],
      ms: [
        {
          id: 'ms2-9-1',
          q: '¿Qué hechos sobre los naturales enuncia el apunte?',
          options: [
            'Sirven para contar',
            'Son cerrados bajo la suma',
            'Su suma es conmutativa',
            'Tienen al cero como elemento neutro',
            'Todo natural tiene opuesto dentro de $\\mathbb{N}$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'El opuesto aparece recién al definir los enteros.',
        },
        {
          id: 'ms2-9-2',
          q: '¿Qué valores figuran en el Ejemplo 1.1 como números racionales?',
          options: ['$\\tfrac{1}{2}$', '$0{,}67$', '$-9{,}1\\overline{35}$', '$\\sqrt{3}$', '$\\pi$'],
          correctIndexes: [0, 1, 2],
          explain: 'Los dos últimos son irracionales y no aparecen en el ejemplo.',
        },
        {
          id: 'ms2-9-3',
          q: '¿Qué motivos da el apunte para construir el conjunto $\\mathbb{Z}$?',
          options: [
            'Permitir restar partiendo de cero',
            'Incorporar los opuestos de los naturales',
            'Cerrar la operación de sustracción',
            'Poder definir la relación de menor',
            'Poder dividir sin resto',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La división exacta no queda cubierta por $\\mathbb{Z}$: para eso hacen falta los racionales.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-9-1', front: 'Convención adoptada para $\\mathbb{N}$', back: 'Se cuenta desde cero: $\\mathbb{N} = \\{0, 1, 2, 3, \\dots\\}$.' },
      { id: 'fc2-9-2', front: '¿Por qué $\\mathbb{N}$ no tiene máximo?', back: 'Porque a cualquier candidato se le suma 1 y se obtiene uno más grande.' },
      { id: 'fc2-9-3', front: 'Conmutatividad de la suma', back: '$\\forall\\, n, m \\in \\mathbb{N},\\ n + m = m + n$: empezar por $n$ y dar $m$ pasos es lo mismo que al revés.' },
      { id: 'fc2-9-4', front: 'Límite de los naturales', back: 'No son cerrados bajo la sustracción: al llegar a cero el salto a la izquierda queda prohibido.' },
      { id: 'fc2-9-5', front: 'Significado de $-n$', back: 'El resultado de dar $n$ pasos a la izquierda desde cero; es el inverso de $n$ respecto de la suma.' },
      { id: 'fc2-9-6', front: 'Definir “menor” con la resta', back: '$n < m$ cuando existe $p \\in \\mathbb{N}$ con $n = m - p$.' },
      { id: 'fc2-9-7', front: 'Escritura formal de $\\mathbb{Q}$', back: '$\\left\\{ \\tfrac{a}{b} \\,/\\, a \\in \\mathbb{Z};\\ b \\in \\mathbb{Z};\\ b \\neq 0 \\right\\}$.' },
      { id: 'fc2-9-8', front: 'Observación 1', back: 'La cadena $\\mathbb{N} \\subset \\mathbb{Z} \\subset \\mathbb{Q}$.' },
    ],
  },
  '10': {
    quiz2: {
      tf: [
        { id: 'tf2-10-1', q: 'Decir que $b$ es múltiplo de $a$ equivale a decir que $a$ divide a $b$.', a: true, explain: 'Es la Observación 2: son dos formas de nombrar la misma relación.' },
        { id: 'tf2-10-2', q: 'Cualquier entero divide a cero.', a: true, explain: 'De $0 = a \\cdot 0$ se deduce $a \\mid 0$ para todo $a \\in \\mathbb{Z}$.' },
        { id: 'tf2-10-3', q: 'El resto de una división entera puede ser igual al valor absoluto del divisor.', a: false, explain: 'La condición del Teorema 1.1 es $0 \\leq r < |a|$: el resto queda estrictamente por debajo.' },
        { id: 'tf2-10-4', q: 'Dos enteros que difieren en un múltiplo de $m$ dejan el mismo resto al dividirlos por $m$.', a: true, explain: 'Es exactamente lo que enuncia la Proposición 1.' },
        { id: 'tf2-10-5', q: 'En la relación $b = ac$, solo $a$ puede considerarse divisor de $b$.', a: false, explain: 'La Observación 3 aclara que los roles de $a$ y $c$ son intercambiables: también $c$ divide a $b$.' },
      ],
      mc: [
        {
          id: 'mc2-10-1',
          q: 'El par $(q, r)$ que produce el algoritmo de división se caracteriza porque:',
          options: [
            'Existe siempre y es único bajo la condición $0 \\leq r < |a|$',
            'Existe siempre pero admite varias combinaciones válidas',
            'Existe solo cuando el divisor es positivo',
            'Existe solo cuando el dividendo es múltiplo del divisor',
          ],
          correctIndex: 0,
          explain: 'La unicidad es lo que permite razonar sin calcular, como en el ejemplo del $24k + 47$.',
        },
        {
          id: 'mc2-10-2',
          q: 'Un entero que excede en 47 a un múltiplo de 24 deja, al dividirlo por 6, un resto de:',
          options: ['3', '11', '5', '7'],
          correctIndex: 2,
          explain: 'Reescribiendo $m = 6(4k + 7) + 5$, el resto es 5.',
        },
        {
          id: 'mc2-10-3',
          q: 'La forma alternativa de la divisibilidad válida cuando $a \\neq 0$ se expresa como:',
          options: [
            '$a \\cdot b \\in \\mathbb{Z}$',
            '$a - b \\in \\mathbb{Z}$',
            '$a / b \\in \\mathbb{Z}$',
            '$b / a \\in \\mathbb{Z}$',
          ],
          correctIndex: 3,
          explain: 'El factor de divisibilidad es $c = b/a$, y tiene que ser entero.',
        },
        {
          id: 'mc2-10-4',
          q: 'Sobre el cero, el apunte concluye en la Observación 4 que:',
          options: [
            'No es múltiplo ni divisor de ningún entero',
            'Es divisor de todos los enteros y múltiplo solo de sí mismo',
            'Es múltiplo de todos los enteros y divisor solo de sí mismo',
            'Es a la vez múltiplo y divisor de todos los enteros',
          ],
          correctIndex: 2,
          explain: '$a \\mid 0$ para todo $a$, mientras que $0 \\mid b$ únicamente si $b = 0$.',
        },
        {
          id: 'mc2-10-5',
          q: 'La descripción informal del algoritmo de división lo presenta como el intento de:',
          options: [
            'Aproximar el dividendo lo mejor posible mediante un múltiplo del divisor',
            'Descomponer el dividendo en factores primos',
            'Buscar el mayor divisor común entre ambos números',
            'Igualar el dividendo y el divisor mediante sumas sucesivas',
          ],
          correctIndex: 0,
          explain: 'La diferencia entre el dividendo y ese múltiplo es lo que llamamos resto.',
        },
      ],
      ms: [
        {
          id: 'ms2-10-1',
          q: '¿Qué restos se obtienen para $m = 24k + 47$ al dividir por 4, 6 y 12?',
          options: ['3', '5', '11', '7', '1'],
          correctIndexes: [0, 1, 2],
          explain: 'Salen de las reescrituras $4(6k+11)+3$, $6(4k+7)+5$ y $12(2k+3)+11$.',
        },
        {
          id: 'ms2-10-2',
          q: '¿Qué elementos integran el enunciado del Teorema 1.1?',
          options: [
            'La hipótesis $a \\neq 0$',
            'La existencia de un par $(q, r)$',
            'La unicidad de ese par',
            'La condición $0 \\leq r < |a|$',
            'La condición de que $a$ y $b$ sean coprimos',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'No se exige nada sobre el máximo común divisor entre $a$ y $b$.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-10-1', front: 'Divisibilidad en una línea', back: '$a \\mid b$ cuando existe $c \\in \\mathbb{Z}$ con $b = ac$; equivale a decir que $b$ es múltiplo de $a$.' },
      { id: 'fc2-10-2', front: 'Roles intercambiables', back: 'Si $b = ac$, tanto $a$ como $c$ son divisores de $b$ (Observación 3).' },
      { id: 'fc2-10-3', front: 'El cero en la divisibilidad', back: 'Múltiplo de todos los enteros y divisor únicamente de sí mismo.' },
      { id: 'fc2-10-4', front: 'Condiciones del cociente y el resto', back: '$b = qa + r$ con $0 \\leq r < |a|$, y el par $(q, r)$ es único.' },
      { id: 'fc2-10-5', front: 'Notación del resto', back: '$r_m(x)$ denota el resto de dividir $x$ por el entero no nulo $m$ (Definición 2).' },
      { id: 'fc2-10-6', front: 'Detectar múltiplos con el resto', back: 'Con $a \\neq 0$: $a \\mid b$ si y solo si $r_a(b) = 0$.' },
      { id: 'fc2-10-7', front: 'Proposición 1', back: '$r_m(u) = r_m(v)$ exactamente cuando $u$ y $v$ difieren en un múltiplo de $m$.' },
      { id: 'fc2-10-8', front: 'Truco del ejemplo $24k + 47$', back: 'Como 24 es múltiplo de 4, 6 y 12, basta dividir 47 por cada uno y reagrupar: restos 3, 5 y 11.' },
    ],
  },
  '11': {
    quiz2: {
      tf: [
        { id: 'tf2-11-1', q: 'El máximo común divisor se define como el mayor de los divisores positivos comunes de dos enteros.', a: true, explain: 'Es la Definición 3, que introduce la notación $(a : b)$.' },
        { id: 'tf2-11-2', q: 'El algoritmo de Euclides termina cuando aparece el primer resto igual a cero.', a: true, explain: 'Y el resultado es el resto inmediatamente anterior, $r_{n-1}$.' },
        { id: 'tf2-11-3', q: 'Intercambiar el orden de los argumentos cambia el valor del máximo común divisor.', a: false, explain: 'La propiedad (1) de la Proposición 2 establece que $(a : b) = (b : a)$.' },
        { id: 'tf2-11-4', q: 'El máximo común divisor entre 24 y 132 vale 12.', a: true, explain: 'Los divisores comunes son 1, 2, 3, 4, 6 y 12; el mayor es 12.' },
        { id: 'tf2-11-5', q: 'Reemplazar $b$ por $b - a$ modifica el valor de $(a : b)$.', a: false, explain: 'La propiedad (4) afirma que $(a : b) = (a : b - a)$: los divisores comunes coinciden.' },
      ],
      mc: [
        {
          id: 'mc2-11-1',
          q: 'La cadena de divisiones que calcula $(3724 : 13818)$ concluye con el valor:',
          options: ['2646', '98', '490', '1078'],
          correctIndex: 1,
          explain: 'La última división exacta es $490 = 5 \\cdot 98 + 0$, así que el último resto no nulo es 98.',
        },
        {
          id: 'mc2-11-2',
          q: 'La propiedad que justifica cada iteración del algoritmo de Euclides establece que:',
          options: [
            '$(a : b) = (a : r_a(b))$ cuando $a \\neq 0$',
            '$(a : b) = (|a| : |b|)$',
            '$(a : b) = (b : a)$',
            '$a \\mid b$ si y solo si $(a : b) = |a|$',
          ],
          correctIndex: 0,
          explain: 'Cambiar $b$ por su resto módulo $a$ preserva el mcd, y así los números se achican en cada paso.',
        },
        {
          id: 'mc2-11-3',
          q: 'La razón por la que el algoritmo de Euclides no puede continuar indefinidamente es que:',
          options: [
            'Los cocientes crecen sin límite',
            'El dividendo se hace negativo en algún paso',
            'Una sucesión decreciente de naturales no puede ser infinita',
            'El divisor termina valiendo 1 en el segundo paso',
          ],
          correctIndex: 2,
          explain: 'Como $a > r_1 > r_2 > \\dots$, forzosamente algún resto llega a cero.',
        },
        {
          id: 'mc2-11-4',
          q: 'Entre los pares del ejercicio de práctica, el que arroja el máximo común divisor más grande es:',
          options: ['$(300 : 72)$', '$(252 : 198)$', '$(159 : 120)$', '$(234 : 117)$'],
          correctIndex: 3,
          explain: 'Da 117, porque $117 \\mid 234$; los otros dan 12, 18 y 3.',
        },
        {
          id: 'mc2-11-5',
          q: 'Si el primer resto del algoritmo ya es cero, la conclusión inmediata es que:',
          options: [
            'El máximo común divisor es el divisor $a$',
            'El máximo común divisor es 1',
            'El máximo común divisor es el dividendo $b$',
            'El algoritmo no puede aplicarse a ese par',
          ],
          correctIndex: 0,
          explain: 'Si $r_1 = 0$ entonces $a \\mid b$ y por lo tanto $(a : b) = a$.',
        },
      ],
      ms: [
        {
          id: 'ms2-11-1',
          q: '¿Qué igualdades componen la Proposición 2?',
          options: [
            '$(a : b) = (b : a)$',
            '$(a : b) = (|a| : |b|)$',
            '$(a : b) = (a : b - a)$',
            '$(a : b) = (a : r_a(b))$ con $a \\neq 0$',
            '$(a : b) = (a + b : a - b)$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La última no figura entre las cinco propiedades enunciadas.',
        },
        {
          id: 'ms2-11-2',
          q: 'Según los resultados publicados del ejercicio de práctica, ¿qué pares tienen mcd distinto de 1?',
          options: ['$(252 : 198)$', '$(300 : 72)$', '$(234 : 117)$', '$(159 : 120)$', '$(323 : 14)$'],
          correctIndexes: [0, 1, 2, 3],
          explain: '$(323 : 14) = 1$, igual que $(44 : 13)$ y $(42 : 11)$.',
        },
        {
          id: 'ms2-11-3',
          q: '¿Qué divisiones aparecen en el cálculo de $(3724 : 13818)$?',
          options: [
            '$13818 = 3 \\cdot 3724 + 2646$',
            '$2646 = 2 \\cdot 1078 + 490$',
            '$1078 = 2 \\cdot 490 + 98$',
            '$490 = 5 \\cdot 98 + 0$',
            '$3724 = 2 \\cdot 1862 + 0$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'El paso real con 3724 es $3724 = 1 \\cdot 2646 + 1078$.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-11-1', front: 'Notación del mcd', back: '$(a : b)$: el mayor de los divisores positivos comunes de $a$ y $b$.' },
      { id: 'fc2-11-2', front: 'Método por ensayo y error', back: 'Listar los divisores positivos de cada número y quedarse con el mayor común: así se obtiene $(24 : 132) = 12$.' },
      { id: 'fc2-11-3', front: 'Primer paso de Euclides', back: 'Dividir $b$ por $a$: $b = q_1 a + r_1$. Si $r_1 = 0$, entonces $(a : b) = a$.' },
      { id: 'fc2-11-4', front: 'Fórmula general de la iteración', back: '$r_i = q_{i+2} r_{i+1} + r_{i+2}$, con $r_{-1} = b$ y $r_0 = a$.' },
      { id: 'fc2-11-5', front: 'Resultado del algoritmo', back: '$(a : b) = r_{n-1}$: el último resto no nulo.' },
      { id: 'fc2-11-6', front: 'Garantía de terminación', back: 'La sucesión $a > r_1 > r_2 > \\dots$ es decreciente en $\\mathbb{N}$, y eso no puede seguir para siempre.' },
      { id: 'fc2-11-7', front: 'Caso $(234 : 117)$', back: 'Da 117, porque $117$ divide a $234$ y entonces el mcd es $|117|$ por la propiedad (3).' },
      { id: 'fc2-11-8', front: 'Pares coprimos del ejercicio', back: '$(44 : 13)$, $(42 : 11)$ y $(323 : 14)$, los tres con mcd igual a 1.' },
    ],
  },
  '12': {
    quiz2: {
      tf: [
        { id: 'tf2-12-1', q: 'Para verificar la divisibilidad por 8 hay que mirar las tres últimas cifras del número.', a: true, explain: 'Deben formar un múltiplo de 8; es la regla del 4 con una mitad extra.' },
        { id: 'tf2-12-2', q: 'El criterio del 9 se resuelve mirando únicamente la última cifra.', a: false, explain: 'Se suman todas las cifras y se verifica que el resultado sea 9 o múltiplo de 9.' },
        { id: 'tf2-12-3', q: 'Un entero compuesto puede escribirse como producto de dos o más números primos.', a: true, explain: 'Es la Definición 5 del apunte.' },
        { id: 'tf2-12-4', q: 'La regla del 11 compara la suma de las cifras de posiciones pares con la de posiciones impares.', a: true, explain: 'La diferencia debe dar 0, 11 o un múltiplo de 11.' },
        { id: 'tf2-12-5', q: 'Un entero es par cuando puede escribirse como $2k + 1$ con $k$ entero.', a: false, explain: 'Esa es la forma de los impares; los pares se escriben $a = 2 \\cdot b$.' },
      ],
      mc: [
        {
          id: 'mc2-12-1',
          q: 'El procedimiento del criterio del 7 consiste en:',
          options: [
            'Sumar todas las cifras y verificar si el total es múltiplo de 7',
            'Restar al número sin las unidades el doble de la cifra de las unidades',
            'Dividir el número por 7 y comparar con el cociente anterior',
            'Comparar las tres primeras cifras con las tres últimas',
          ],
          correctIndex: 1,
          explain: 'Si el resultado es 0 o múltiplo de 7, el número lo es; el proceso puede repetirse.',
        },
        {
          id: 'mc2-12-2',
          q: 'El apunte justifica el criterio del 4 diciendo que:',
          options: [
            'La mitad del número termina en cifra par',
            'La suma de las dos últimas cifras es par',
            'Todo múltiplo de 4 termina en 0, 4 u 8',
            'La cuarta parte del número es siempre entera',
          ],
          correctIndex: 0,
          explain: 'Por eso el criterio del 8 se explica como “la mitad de la mitad” termina en cifra par.',
        },
        {
          id: 'mc2-12-3',
          q: 'La Definición 4 caracteriza a los primos por tener:',
          options: [
            'Exactamente 2 divisores',
            'Exactamente 3 divisores',
            'Exactamente 4 divisores',
            'Una cantidad infinita de divisores',
          ],
          correctIndex: 2,
          explain: 'El apunte cuenta los divisores enteros: $1, -1, p$ y $-p$.',
        },
        {
          id: 'mc2-12-4',
          q: 'Al aplicar el criterio del 11 al número 71929 se obtiene:',
          options: ['$25 - 3 = 22$', '$28 - 3 = 25$', '$25 - 10 = 15$', '$18 - 7 = 11$'],
          correctIndex: 0,
          explain: '$7 + 9 + 9 = 25$ y $1 + 2 = 3$; la diferencia 22 es múltiplo de 11.',
        },
        {
          id: 'mc2-12-5',
          q: 'El Teorema fundamental de la aritmética afirma que todo entero positivo mayor que 1:',
          options: [
            'Es primo o bien un único producto de números primos',
            'Es par o bien múltiplo de un primo impar',
            'Admite exactamente cuatro divisores positivos',
            'Puede escribirse como suma de dos primos',
          ],
          correctIndex: 0,
          explain: 'Es el Teorema 1.2 tal como lo enuncia el apunte.',
        },
      ],
      ms: [
        {
          id: 'ms2-12-1',
          q: '¿Qué números aparecen como ejemplos del criterio de divisibilidad por 4?',
          options: ['104', '208', '312', '920', '125'],
          correctIndexes: [0, 1, 2, 3],
          explain: '125 pertenece a la lista de ejemplos del criterio del 5.',
        },
        {
          id: 'ms2-12-2',
          q: '¿Qué criterios requieren repetir el procedimiento si el resultado sigue siendo grande?',
          options: [
            'El del 3, sumando otra vez las cifras',
            'El del 9, sumando otra vez las cifras',
            'El del 7, repitiendo la resta del doble de las unidades',
            'El del 10, mirando de nuevo la última cifra',
            'El del 2, mirando de nuevo la última cifra',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'Los criterios del 2 y del 10 se resuelven de una sola mirada, sin iterar.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-12-1', front: 'Criterio del 2', back: 'El número termina en cero o en cifra par.' },
      { id: 'fc2-12-2', front: 'Criterio del 5 y del 10', back: 'Por 5: termina en 0 o en 5. Por 10: termina en 0.' },
      { id: 'fc2-12-3', front: 'Regla de las dos y tres últimas cifras', back: 'Por 4: las dos últimas forman múltiplo de 4. Por 8: las tres últimas forman múltiplo de 8.' },
      { id: 'fc2-12-4', front: 'Ejemplo del criterio del 7 con 2807', back: '$280 - 14 = 266$, luego $26 - 12 = 14 = 2 \\times 7$: es divisible por 7.' },
      { id: 'fc2-12-5', front: 'Ejemplo del criterio del 11 con 2816', back: '$8 + 6 = 14$, $2 + 1 = 3$, y $14 - 3 = 11$.' },
      { id: 'fc2-12-6', front: 'Definición de compuesto', back: 'Entero que puede escribirse como producto de 2 o más números primos.' },
      { id: 'fc2-12-7', front: 'Par vs. impar', back: 'Par: $a = 2 \\cdot b$ con $b \\in \\mathbb{Z}$. Impar: $a = 2 \\cdot k + 1$ con $k \\in \\mathbb{Z}$.' },
      { id: 'fc2-12-8', front: 'Criterio compuesto del 6', back: 'Se cumple cuando el número pasa a la vez el criterio del 2 y el del 3.' },
    ],
  },
  '13': {
    quiz2: {
      tf: [
        { id: 'tf2-13-1', q: 'Trasponer una matriz de $2 \\times 3$ produce una matriz de $3 \\times 2$.', a: true, explain: 'La transpuesta de una matriz de $m \\times n$ es de $n \\times m$.' },
        { id: 'tf2-13-2', q: 'El determinante de una matriz $2 \\times 2$ se obtiene sumando los productos de ambas diagonales.', a: false, explain: 'Se restan: $\\det A = a_{11} a_{22} - a_{21} a_{12}$.' },
        { id: 'tf2-13-3', q: 'La matriz inversa se define solo para matrices cuadradas.', a: true, explain: 'La Definición 10 parte de una matriz $A$ de $n \\times n$ y busca $A^{-1}$ también de $n \\times n$.' },
        { id: 'tf2-13-4', q: 'El desarrollo del determinante $3 \\times 3$ alterna los signos de los tres términos.', a: true, explain: 'Van $+b_{11}$, $-b_{12}$ y $+b_{13}$ multiplicando cada menor.' },
        { id: 'tf2-13-5', q: 'Una matriz de $1 \\times 1$ no se considera matriz según el apunte.', a: false, explain: 'Aparece entre los ejemplos de tamaños junto a las de $2 \\times 2$, $2 \\times 3$, $1 \\times 3$ y $3 \\times 3$.' },
      ],
      mc: [
        {
          id: 'mc2-13-1',
          q: 'La condición que debe cumplir $A^{-1}$ respecto de $A$ es:',
          options: [
            'Que su producto en cualquier orden dé la matriz identidad',
            'Que su suma dé la matriz identidad',
            'Que coincida con la transpuesta de $A$',
            'Que su determinante sea igual al de $A$',
          ],
          correctIndex: 0,
          explain: '$A A^{-1} = A^{-1} A = \\mathrm{Id}$; si existe, $A$ es invertible.',
        },
        {
          id: 'mc2-13-2',
          q: 'Cuando $A$ es invertible, el sistema $Ax = b$ tiene:',
          options: [
            'Infinitas soluciones parametrizadas',
            'Solución única dada por $x = A^{-1} b$',
            'Solución solo si $b$ es el vector nulo',
            'Ninguna solución garantizada',
          ],
          correctIndex: 1,
          explain: 'Es el Teorema 1.3, válido para cualquier $b \\in \\mathbb{R}^{n}$.',
        },
        {
          id: 'mc2-13-3',
          q: 'El resultado del cálculo del Ejemplo 1.4 es:',
          options: ['$-5$', '10', '5', '2'],
          correctIndex: 2,
          explain: '$5(2) + 3(-1) + 2(-1) = 10 - 3 - 2 = 5$.',
        },
        {
          id: 'mc2-13-4',
          q: 'Entre los determinantes publicados del ejercicio de práctica, el único no entero es:',
          options: ['$-8$', '$-26/3$', '15', '11'],
          correctIndex: 1,
          explain: 'Corresponde a la matriz que tiene la entrada $2/3$.',
        },
        {
          id: 'mc2-13-5',
          q: 'La transpuesta se construye tomando:',
          options: [
            'La diagonal principal como primera fila',
            'Las columnas en orden inverso',
            'La fila $i$ de $A$ como columna $i$ de $A^{t}$',
            'La fila $i$ de $A$ como fila $n - i$ de $A^{t}$',
          ],
          correctIndex: 2,
          explain: 'Y, simétricamente, la columna $j$ de $A$ pasa a ser la fila $j$ de $A^{t}$.',
        },
      ],
      ms: [
        {
          id: 'ms2-13-1',
          q: '¿Qué tamaños de matriz ejemplifica el apunte?',
          options: ['$2 \\times 2$', '$2 \\times 3$', '$1 \\times 3$', '$3 \\times 3$', '$4 \\times 4$'],
          correctIndexes: [0, 1, 2, 3],
          explain: 'Los cinco ejemplos son de $2 \\times 2$, $2 \\times 3$, $1 \\times 3$, $3 \\times 3$ y $1 \\times 1$.',
        },
        {
          id: 'ms2-13-2',
          q: 'Según los resultados publicados del ejercicio de determinantes, ¿qué valores aparecen?',
          options: ['16', '11', '0', '2', '7'],
          correctIndexes: [0, 1, 2, 3],
          explain: 'Los ocho resultados publicados son 16, 11, 0, 2, $-26/3$, 15, $-8$ y $-6$.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-13-1', front: 'Qué es una matriz', back: 'Un arreglo rectangular de números llamados entradas o elementos.' },
      { id: 'fc2-13-2', front: 'Convención de tamaño', back: 'Una matriz de $m \\times n$ tiene $m$ filas y $n$ columnas.' },
      { id: 'fc2-13-3', front: 'Cómo se arma la transpuesta', back: 'La fila $i$ de $A$ pasa a ser la columna $i$ de $A^{t}$, y la columna $j$ pasa a ser la fila $j$.' },
      { id: 'fc2-13-4', front: 'Condición de invertibilidad', back: 'Existe $A^{-1}$ de $n \\times n$ tal que $A A^{-1} = A^{-1} A = \\mathrm{Id}$.' },
      { id: 'fc2-13-5', front: 'Uso de la inversa en sistemas', back: 'Si $A$ es invertible, $Ax = b$ tiene la solución única $x = A^{-1} b$ para cualquier $b \\in \\mathbb{R}^{n}$.' },
      { id: 'fc2-13-6', front: 'Determinante de orden 2', back: '$a_{11} a_{22} - a_{21} a_{12}$: producto de la diagonal principal menos el de la secundaria.' },
      { id: 'fc2-13-7', front: 'Determinante de orden 3', back: 'Desarrollo por la primera fila con signos alternados $+, -, +$, multiplicando cada entrada por su menor de $2 \\times 2$.' },
      { id: 'fc2-13-8', front: 'Resultado del Ejemplo 1.4', back: '5, a partir de $5(2) + 3(-1) + 2(-1)$.' },
    ],
  },
  '1': {
    quiz2: {
      tf: [
        { id: 'tf2-1-1', q: 'La función hash del Ejemplo 2.1 asigna cada objeto a una caja según la cantidad de letras de su nombre en singular.', a: true, explain: 'Es el algoritmo elegido en el ejemplo: "gato" tiene 4 letras y va a la caja 4.' },
        { id: 'tf2-1-2', q: 'Dos objetos distintos con el mismo hashcode se guardan en cajas distintas.', a: false, explain: 'Con el mismo hashcode van a la misma caja; eso es una colisión y el apunte la contempla como algo normal.' },
        { id: 'tf2-1-3', q: 'El número inicial de cajas de una Hashtable se puede fijar al construirla.', a: true, explain: 'Se especifica un entero en la función de inicialización o constructor, lo que baja el promedio de objetos por caja.' },
        { id: 'tf2-1-4', q: 'Conociendo el hashcode de un objeto se puede reconstruir el objeto original.', a: false, explain: 'El apunte lo descarta con el ejemplo de Perro y $291564382$: el número no se puede convertir de vuelta.' },
        { id: 'tf2-1-5', q: 'Buscar dentro de una caja con varios objetos sigue siendo más rápido que la búsqueda lineal completa.', a: true, explain: 'Se compara contra los pocos objetos de esa caja en vez de contra toda la colección.' },
      ],
      mc: [
        {
          id: 'mc2-1-1',
          q: 'Con el algoritmo modificado del Ejemplo 2.1, un objeto cuyo nombre tiene 12 letras se guarda en la caja:',
          options: ['Caja 1', 'Caja 3', 'Caja 2', 'Caja 4'],
          correctIndex: 2,
          explain: 'La regla ajustada manda los de 11 letras a la caja 1, los de 12 a la caja 2, los de 13 a la caja 3, y así.',
        },
        {
          id: 'mc2-1-2',
          q: 'El apunte compara la tabla hash con el trabajo de una impresora porque:',
          options: [
            'Cada tipo de letra tiene su propio compartimento y se busca solo ahí',
            'Cada tipo de letra se imprime en el orden en que llega al cajón',
            'Cada tipo de letra se compara contra todos los demás antes de usarse',
            'Cada tipo de letra se guarda ordenado alfabéticamente en un cajón',
          ],
          correctIndex: 0,
          explain: 'La analogía es la del compartimento por tipo: se busca una A solo en el compartimento de las A.',
        },
        {
          id: 'mc2-1-3',
          q: 'En una tabla con 10 cajas, ¿qué códigos hash comparten casilla con el valor $218714508$?',
          options: [
            'Los códigos $80, 800, 8000$ y siguientes',
            'Los códigos $8, 18, 28$ y siguientes',
            'Los códigos $9, 19, 29$ y siguientes',
            'Los códigos $2, 12, 22$ y siguientes',
          ],
          correctIndex: 1,
          explain: 'Ese código cae en la casilla 8, igual que todos los que terminan en 8.',
        },
        {
          id: 'mc2-1-4',
          q: 'Según el apunte, el valor concreto del código hash para el programador es que:',
          options: [
            'Reduce el espacio que ocupa el objeto en memoria',
            'Permite recuperar los datos internos del objeto',
            'Garantiza que cada objeto quede en una caja distinta',
            'Funciona como id de búsqueda dentro de la tabla hash',
          ],
          correctIndex: 3,
          explain: 'El apunte es explícito: fuera de servir como índice de búsqueda, el hash no le aporta otra utilidad.',
        },
        {
          id: 'mc2-1-5',
          q: 'Si se planea guardar muchos elementos en una Hashtable, conviene:',
          options: [
            'Especificar un número menor de cajas al construirla',
            'Recalcular el hashcode de cada objeto al insertarlo',
            'Ordenar los objetos antes de calcular su hashcode',
            'Especificar un número mayor de cajas al construirla',
          ],
          correctIndex: 3,
          explain: 'Más cajas implica menos objetos promedio por caja, y por lo tanto búsquedas más cortas dentro de cada una.',
        },
      ],
      ms: [
        {
          id: 'ms2-1-1',
          q: '¿Qué características del código hash menciona el apunte?',
          options: [
            'Genera un número para cualquier objeto',
            'Puede repetirse entre objetos distintos',
            'Sirve como índice para ubicar el objeto',
            'Permite reconstruir el objeto original',
            'Ordena la colección de menor a mayor',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'Ni se puede invertir ni ordena nada: solo produce el número que decide la caja.',
        },
        {
          id: 'ms2-1-2',
          q: 'Con el algoritmo original del ejemplo (cantidad de letras en singular), ¿qué asignaciones son válidas?',
          options: [
            'perro va a la caja 5',
            'ballena va a la caja 7',
            'gato va a la caja 4',
            'perros va a la caja 6',
            'ballenas va a la caja 8',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'El nombre se toma siempre en singular, así que los plurales quedan fuera del algoritmo.',
        },
        {
          id: 'ms2-1-3',
          q: '¿Qué estructuras de las nombradas por el apunte se apoyan en el código hash?',
          options: [
            'HashMap',
            'ArrayList',
            'HashSet',
            'Hashtable',
            'LinkedList',
          ],
          correctIndexes: [0, 2, 3],
          explain: 'Las listas no usan hash: el apunte solo cita HashMap, HashSet y Hashtable.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-1-1', front: '¿Qué produce una función hashcode?', back: 'Un número asociado a cualquier objeto, que se usa para decidir en qué compartimento se guarda o se busca.' },
      { id: 'fc2-1-2', front: 'Colisión', back: 'Dos o más objetos con el mismo código hash comparten caja. Se resuelve comparando solo dentro de esa caja.' },
      { id: 'fc2-1-3', front: 'Regla del Ejemplo 2.1 para nombres largos', back: 'Los objetos de 11 letras van a la caja 1, los de 12 a la caja 2, y así siguiendo, porque solo hay cajas de 0 a 9.' },
      { id: 'fc2-1-4', front: 'Irreversibilidad del hash', back: 'Del objeto se obtiene el número, pero del número no se vuelve al objeto: Perro → $291564382$ no tiene vuelta.' },
      { id: 'fc2-1-5', front: 'Parámetro del constructor de una Hashtable', back: 'Un entero con la cantidad inicial de cajas; conviene agrandarlo si se van a guardar muchos elementos.' },
      { id: 'fc2-1-6', front: 'Comparación con la búsqueda lineal', back: 'La búsqueda lineal revisa toda la colección; con hash se revisa una sola caja, así que es mucho más ágil.' },
      { id: 'fc2-1-7', front: 'Analogía de la impresora', back: 'Los tipos A se guardan y se buscan en el compartimento de las A, en vez de revolver un cajón sin clasificar.' },
      { id: 'fc2-1-8', front: 'Relación del hash con la unidad', back: 'La caja se obtiene como resto de dividir el hash por la cantidad de cajas: es una congruencia módulo $n$.' },
    ],
  },
  '2': {
    quiz2: {
      tf: [
        { id: 'tf2-2-1', q: 'Una ecuación diofántica exige que los coeficientes $a$, $b$ y $c$ sean enteros.', a: true, explain: 'La definición 2.1 pide $a, b, c \\in \\mathbb{Z}$, además de buscar soluciones enteras.' },
        { id: 'tf2-2-2', q: 'La condición del teorema 2.1 es suficiente pero no necesaria.', a: false, explain: 'El enunciado es un "si y solo si": es necesaria y suficiente a la vez.' },
        { id: 'tf2-2-3', q: 'El máximo común divisor es el último cociente que devuelve el algoritmo de Euclides.', a: false, explain: 'Es el último <strong>resto</strong> no nulo: en el ejemplo con 110 y 97 ese resto es 1, y ese es el mcd.' },
        { id: 'tf2-2-4', q: 'La expresión $(a : b) \\mid c$ se lee "c divide al máximo común divisor entre a y b".', a: false, explain: 'Se lee al revés: el mcd entre $a$ y $b$ divide a $c$.' },
        { id: 'tf2-2-5', q: 'En $110x - 97y = 1042$ se verifica la condición de existencia antes de buscar la solución.', a: true, explain: 'Primero se calcula $(110 : 97) = 1$ con Euclides y recién ahí se afirma que admite al menos una solución.' },
      ],
      mc: [
        {
          id: 'mc2-2-1',
          q: 'La forma general de una ecuación diofántica según el apunte es:',
          options: [
            '$ax^2 + by = c$ con $a, b, c \\in \\mathbb{Z}$',
            '$ax + by = c$ con $a, b, c \\in \\mathbb{Z}$',
            '$ax + by = c$ con $a, b, c \\in \\mathbb{R}$',
            '$ax + by = 0$ con $a, b \\in \\mathbb{Z}$',
          ],
          correctIndex: 1,
          explain: 'Es la ecuación 2.1: primer grado, dos incógnitas y coeficientes enteros.',
        },
        {
          id: 'mc2-2-2',
          q: 'La ecuación $6x + 4y = 7$ no admite solución diofántica porque:',
          options: [
            '$(6 : 4) = 2$ y 2 no divide a 7',
            '$(6 : 4) = 1$ y 1 no divide a 7',
            '7 es un número primo mayor que 6',
            '6 y 4 no son coprimos entre sí',
          ],
          correctIndex: 0,
          explain: 'Aplicando el teorema 2.1: el mcd es 2, y 2 no divide a 7, así que no hay solución entera.',
        },
        {
          id: 'mc2-2-3',
          q: 'En el algoritmo de Euclides aplicado a 110 y 97, el paso que sigue a $110 = 1 \\cdot 97 + 13$ es:',
          options: [
            '$13 = 2 \\cdot 6 + 1$',
            '$110 = 8 \\cdot 13 + 6$',
            '$97 = 7 \\cdot 13 + 6$',
            '$97 = 1 \\cdot 13 + 84$',
          ],
          correctIndex: 2,
          explain: 'Se divide el divisor anterior (97) por el resto obtenido (13), y da cociente 7 con resto 6.',
        },
        {
          id: 'mc2-2-4',
          q: 'Verificada la condición del teorema 2.1, lo que queda garantizado es:',
          options: [
            'Que la ecuación tiene una única solución entera',
            'Que la solución se obtiene despejando directamente',
            'Que existe al menos una solución diofántica entera',
            'Que los coeficientes son coprimos entre sí',
          ],
          correctIndex: 2,
          explain: 'El teorema garantiza existencia, no unicidad ni un método de cálculo.',
        },
        {
          id: 'mc2-2-5',
          q: 'Las soluciones diofánticas de $ax + by = c$ son:',
          options: [
            'Valores $x_0, y_0 \\in \\mathbb{Z}$ que verifican la ecuación',
            'Valores $x_0, y_0 \\in \\mathbb{R}$ que verifican la ecuación',
            'Valores $x_0, y_0 \\in \\mathbb{N}$ que verifican la ecuación',
            'Valores $x_0, y_0$ que anulan el término independiente',
          ],
          correctIndex: 0,
          explain: 'Se pide que sean enteros, no solo naturales ni reales cualesquiera.',
        },
      ],
      ms: [
        {
          id: 'ms2-2-1',
          q: '¿Cuáles de estas ecuaciones admiten solución diofántica según el teorema 2.1?',
          options: [
            '$5x + 3y = 8$',
            '$4x + 6y = 9$',
            '$110x - 97y = 1042$',
            '$27x + 83y = 17$',
            '$9x + 6y = 4$',
          ],
          correctIndexes: [0, 2, 3],
          explain: 'En la segunda el mcd es 2 y no divide a 9; en la última el mcd es 3 y no divide a 4.',
        },
        {
          id: 'ms2-2-2',
          q: '¿Qué se usa en la verificación de existencia del ejemplo $110x - 97y = 1042$?',
          options: [
            'El algoritmo de Euclides',
            'El máximo común divisor entre 110 y 97',
            'La condición $(110 : 97) \\mid 1042$',
            'La fórmula de la solución general',
            'La reducción de coeficientes módulo 97',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'La solución general y la reducción modular aparecen en secciones posteriores, no en la verificación.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-2-1', front: 'Ecuación 2.1', back: '$ax + by = c$ con $a, b, c \\in \\mathbb{Z}$: la forma general de una ecuación diofántica.' },
      { id: 'fc2-2-2', front: '¿Qué se busca en una diofántica?', back: 'Soluciones diofánticas: pares $(x_0, y_0)$ de números enteros que verifican la ecuación.' },
      { id: 'fc2-2-3', front: 'Condición de existencia', back: 'Existe solución si y solo si el máximo común divisor entre $a$ y $b$ divide al término independiente: $(a : b) \\mid c$.' },
      { id: 'fc2-2-4', front: 'Lectura de $(a : b) \\mid c$', back: '"El mcd entre $a$ y $b$ divide a $c$". La barra $\\mid$ significa "divide a".' },
      { id: 'fc2-2-5', front: 'Algoritmo de Euclides — qué devuelve', back: 'El máximo común divisor: se divide sucesivamente quedándose con los restos, y el último resto no nulo es el mcd.' },
      { id: 'fc2-2-6', front: 'Caso $110x - 97y = 1042$', back: '$(110 : 97) = 1$ y $1 \\mid 1042$: la ecuación admite al menos una solución diofántica.' },
      { id: 'fc2-2-7', front: '¿Qué NO garantiza el teorema 2.1?', back: 'No dice cuál es la solución ni cuántas hay: solo asegura que existe al menos una.' },
    ],
  },
  '3': {
    quiz2: {
      tf: [
        { id: 'tf2-3-1', q: 'En el método de los tanteos se prueban valores enteros hasta obtener un resultado entero.', a: true, explain: 'Se despeja una incógnita y se le dan valores a la otra hasta que el cociente dé entero.' },
        { id: 'tf2-3-2', q: 'El método de divisiones sucesivas parte de despejar la incógnita de coeficiente mayor.', a: false, explain: 'Se despeja la de coeficiente de <strong>menor</strong> valor absoluto.' },
        { id: 'tf2-3-3', q: 'La ecuación auxiliar que se obtiene tiene coeficientes menores que la original.', a: true, explain: 'Esa es la razón del método: $r_1 y + a z = c$ es más chica y el proceso se puede repetir.' },
        { id: 'tf2-3-4', q: 'La solución del Ejemplo 2 ($5x - 8y = 2$) es $(x_0, y_0) = (2, 1)$.', a: true, explain: 'Con $y = 1$ resulta $x = 10/5 = 2$, el primer valor entero de la tabla de tanteos.' },
        { id: 'tf2-3-5', q: 'En el Ejemplo 4 alcanza con una sola reducción para llegar a la solución.', a: false, explain: 'Hacen falta dos: primero $13x - 97z = 72$ y después $13w - 6z = 7$.' },
      ],
      mc: [
        {
          id: 'mc2-3-1',
          q: 'En el Ejemplo 1 ($5x + 3y = 8$), tanteando con $x = 2$ se obtiene:',
          options: ['$y = 1$', '$y = -2/3$', '$y = 8/3$', '$y = 2$'],
          correctIndex: 1,
          explain: 'Reemplazando en $y = \\dfrac{8 - 5x}{3}$ queda $-2/3$, que no es entero; el valor útil es $x = 1$.',
        },
        {
          id: 'mc2-3-2',
          q: 'Tras dividir $b$ por $a$ y reemplazar, la incógnita despejada se escribe como:',
          options: [
            '$x = q_1 y + \\dfrac{c + r_1 y}{a}$',
            '$x = -q_1 y + \\dfrac{c - r_1 y}{a}$',
            '$x = -r_1 y + \\dfrac{c - q_1 y}{a}$',
            '$x = q_1 y - \\dfrac{c - r_1 y}{b}$',
          ],
          correctIndex: 1,
          explain: 'De ahí sale la definición $z = \\dfrac{c - r_1 y}{a}$ y la ecuación auxiliar $r_1 y + a z = c$.',
        },
        {
          id: 'mc2-3-3',
          q: 'En el Ejemplo 3 la ecuación auxiliar que se plantea es:',
          options: [
            '$2z + 27y = 17$',
            '$27z + 2y = 17$',
            '$83z + 27y = 17$',
            '$27z + 3y = 17$',
          ],
          correctIndex: 1,
          explain: 'Se define $z = \\dfrac{17 - 2y}{27}$, de donde $27z + 2y = 17$.',
        },
        {
          id: 'mc2-3-4',
          q: 'En el Ejemplo 3, al pasar de $(z_0, y_0) = (1, -5)$ a la ecuación original se obtiene:',
          options: [
            '$(x_0, y_0) = (1, -5)$',
            '$(x_0, y_0) = (5, -16)$',
            '$(x_0, y_0) = (16, -5)$',
            '$(x_0, y_0) = (-5, 16)$',
          ],
          correctIndex: 2,
          explain: 'Se deshace el reemplazo con $x = -3y + z = 15 + 1 = 16$, manteniendo $y = -5$.',
        },
        {
          id: 'mc2-3-5',
          q: 'En el Ejemplo 4, la segunda ecuación auxiliar que aparece es:',
          options: [
            '$13w - 6z = 7$',
            '$6w - 13z = 7$',
            '$13w - 97z = 72$',
            '$97w - 13z = 6$',
          ],
          correctIndex: 0,
          explain: 'Se define $w = \\dfrac{6z + 7}{13}$, de donde $13w - 6z = 7$, y con $w = 1$ resulta $z = 1$.',
        },
      ],
      ms: [
        {
          id: 'ms2-3-1',
          q: '¿Qué condiciones se asumen al desarrollar el método general de divisiones sucesivas?',
          options: [
            'Que $a$ y $b$ son positivos',
            'Que $a$ es menor que $b$',
            'Que $b = a \\cdot q_1 + r_1$ con $r_1 < a$',
            'Que $c$ es divisible por $a$',
            'Que $a$ y $b$ son coprimos',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'Ni la divisibilidad de $c$ ni la coprimalidad se piden: el método funciona igual mientras exista solución.',
        },
        {
          id: 'ms2-3-2',
          q: '¿Qué pares son soluciones diofánticas halladas en los ejemplos del apunte?',
          options: [
            '$(1, 1)$ para $5x + 3y = 8$',
            '$(2, 1)$ para $5x - 8y = 2$',
            '$(16, -5)$ para $27x + 83y = 17$',
            '$(13, 4)$ para $110x - 97y = 1042$',
            '$(3, 2)$ para $27x + 83y = 17$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'El último par no verifica la ecuación: $27 \\cdot 3 + 83 \\cdot 2 = 247$, no 17.',
        },
        {
          id: 'ms2-3-3',
          q: '¿Qué divisiones se usan en el desarrollo del Ejemplo 4?',
          options: [
            '$110 = 97 + 13$',
            '$1042 = 97 \\cdot 10 + 72$',
            '$97 = 13 \\cdot 7 + 6$',
            '$72 = 13 \\cdot 5 + 7$',
            '$83 = 27 \\cdot 3 + 2$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La división de 83 por 27 pertenece al Ejemplo 3, no al 4.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-3-1', front: 'Tanteos — procedimiento', back: 'Despejar una incógnita y darle a la otra valores enteros sucesivos hasta que el resultado sea entero.' },
      { id: 'fc2-3-2', front: '¿Hasta qué valor conviene tantear?', back: 'Hasta el valor del denominador: por ejemplo, en $x = \\dfrac{2 + 8y}{5}$ alcanza con probar $y$ menor que 5.' },
      { id: 'fc2-3-3', front: 'Divisiones sucesivas — primer paso', back: 'Despejar la incógnita de coeficiente de menor valor absoluto y dividir el otro coeficiente por él.' },
      { id: 'fc2-3-4', front: 'Ecuación auxiliar del método general', back: '$r_1 y + a z = c$, con $z = \\dfrac{c - r_1 y}{a}$; tiene coeficientes menores que la original.' },
      { id: 'fc2-3-5', front: 'Ejemplo 3 en dos pasos', back: '$27x + 83y = 17$ se reduce a $27z + 2y = 17$; sale $(z_0, y_0) = (1, -5)$ y de vuelta $(x_0, y_0) = (16, -5)$.' },
      { id: 'fc2-3-6', front: 'Ejemplo 4 en tres pasos', back: '$110x - 97y = 1042 \\to 13x - 97z = 72 \\to 13w - 6z = 7$; con $(w_0, z_0) = (1, 1)$ se llega a $(x_0, y_0) = (13, 4)$.' },
      { id: 'fc2-3-7', front: '¿Cómo se vuelve a las incógnitas originales?', back: 'Deshaciendo los reemplazos en orden inverso, sustituyendo cada variable auxiliar por su expresión.' },
      { id: 'fc2-3-8', front: 'Verificación de una solución', back: 'Se reemplaza en la ecuación original: $110 \\cdot 13 - 97 \\cdot 4 = 1042$ confirma el resultado del Ejemplo 4.' },
    ],
  },
  '4': {
    quiz2: {
      tf: [
        { id: 'tf2-4-1', q: 'La cantidad de soluciones diofánticas de una ecuación resoluble es infinita.', a: true, explain: 'Hay una solución por cada valor entero del parámetro $t$.' },
        { id: 'tf2-4-2', q: 'En la solución general, el término que acompaña a $x$ es $a t$.', a: false, explain: 'Los coeficientes se cruzan: $x = x_0 - b t$ e $y = y_0 + a t$.' },
        { id: 'tf2-4-3', q: 'La deducción parte de que ya se conoce una solución particular $(x_0, y_0)$.', a: true, explain: 'Se reemplaza $c = a x_0 + b y_0$ para llegar a $a(x - x_0) + b(y - y_0) = 0$.' },
        { id: 'tf2-4-4', q: 'La recta $ax + by = c$ pasa por infinitos puntos de coordenadas enteras cuando la ecuación es resoluble.', a: true, explain: 'Cada $t \\in \\mathbb{Z}$ da un punto entero distinto sobre esa recta.' },
        { id: 'tf2-4-5', q: 'El parámetro $t$ de la solución general recorre los números naturales.', a: false, explain: 'Recorre $\\mathbb{Z}$, así que también toma valores negativos.' },
      ],
      mc: [
        {
          id: 'mc2-4-1',
          q: 'La igualdad que se obtiene antes de introducir el parámetro es:',
          options: [
            '$\\dfrac{x - x_0}{y - y_0} = \\dfrac{-b}{a}$',
            '$\\dfrac{x - x_0}{y - y_0} = \\dfrac{-a}{b}$',
            '$\\dfrac{y - y_0}{x - x_0} = \\dfrac{-b}{a}$',
            '$\\dfrac{x + x_0}{y + y_0} = \\dfrac{-b}{a}$',
          ],
          correctIndex: 0,
          explain: 'Sale de despejar el cociente en $a(x - x_0) + b(y - y_0) = 0$.',
        },
        {
          id: 'mc2-4-2',
          q: 'La solución general de $ax + by = c$ se escribe como:',
          options: [
            '$x = x_0 + bt$, $y = y_0 - at$',
            '$x = x_0 - at$, $y = y_0 + bt$',
            '$x = x_0 - bt$, $y = y_0 + at$',
            '$x = x_0 + at$, $y = y_0 - bt$',
          ],
          correctIndex: 2,
          explain: 'Sale de $x - x_0 = -bt$ e $y - y_0 = at$, con $t$ entero.',
        },
        {
          id: 'mc2-4-3',
          q: 'El argumento que justifica introducir el parámetro $t$ es que:',
          options: [
            'Toda recta del plano corta siempre al eje de abscisas',
            'Dos fracciones son iguales si sus términos son múltiplos',
            'Todo número entero es cociente de otros dos enteros',
            'El máximo común divisor divide al término independiente',
          ],
          correctIndex: 1,
          explain: 'Es la frase textual del apunte: por eso se escribe cada numerador como un múltiplo común.',
        },
        {
          id: 'mc2-4-4',
          q: 'La lectura geométrica de una ecuación diofántica es:',
          options: [
            'Buscar el punto donde la recta corta al eje vertical',
            'Buscar la pendiente que tiene la recta en el plano',
            'Buscar la distancia entre la recta y el origen',
            'Buscar el cruce de la recta con el espacio de los enteros',
          ],
          correctIndex: 3,
          explain: 'La recta vive en $\\mathbb{R}^2$; las soluciones son los puntos donde cae sobre coordenadas enteras.',
        },
        {
          id: 'mc2-4-5',
          q: 'En la figura del apunte, el punto $A$ señalado sobre la recta representa:',
          options: [
            'El origen del sistema de coordenadas',
            'El punto de corte con el eje vertical',
            'El valor del máximo común divisor',
            'Una solución entera de la ecuación',
          ],
          correctIndex: 3,
          explain: 'La leyenda de la figura dice "Solución de la ecuación" y apunta a ese nodo de la grilla.',
        },
      ],
      ms: [
        {
          id: 'ms2-4-1',
          q: '¿Qué pasos integran la deducción de la solución general?',
          options: [
            'Reemplazar $c$ por $a x_0 + b y_0$',
            'Agrupar los términos en $a(x - x_0) + b(y - y_0) = 0$',
            'Igualar el cociente de diferencias a $\\dfrac{-b}{a}$',
            'Parametrizar con $t \\in \\mathbb{Z}$',
            'Reducir los coeficientes módulo $c$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La reducción modular corresponde a las ecuaciones de congruencia, no a esta deducción.',
        },
        {
          id: 'ms2-4-2',
          q: 'Si $(1, 1)$ resuelve $5x + 3y = 8$, ¿qué pares también son soluciones según la fórmula general?',
          options: [
            '$(-2, 6)$',
            '$(4, -4)$',
            '$(1, 1)$',
            '$(7, -9)$',
            '$(2, 2)$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'Con $x = 1 - 3t$ e $y = 1 + 5t$: $t = 1$ da $(-2, 6)$, $t = -1$ da $(4, -4)$ y $t = -2$ da $(7, -9)$. El par $(2, 2)$ da 16, no 8.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-4-1', front: 'Fórmula de la solución general', back: '$x = x_0 - bt$ e $y = y_0 + at$, con $t \\in \\mathbb{Z}$.' },
      { id: 'fc2-4-2', front: '¿Qué se necesita para aplicarla?', back: 'Conocer una solución particular $(x_0, y_0)$ de la ecuación.' },
      { id: 'fc2-4-3', front: 'Primer paso de la deducción', back: 'Sustituir $c$ por $a x_0 + b y_0$ y agrupar: $a(x - x_0) + b(y - y_0) = 0$.' },
      { id: 'fc2-4-4', front: 'Justificación del parámetro', back: 'Dos fracciones son iguales cuando sus términos son múltiplos, de ahí $x - x_0 = -bt$ e $y - y_0 = at$.' },
      { id: 'fc2-4-5', front: 'Cantidad de soluciones', back: 'Infinitas, una por cada entero $t$, siempre que exista al menos una.' },
      { id: 'fc2-4-6', front: 'Lectura geométrica', back: 'La ecuación es una recta en $\\mathbb{R}^2$ y las soluciones diofánticas son sus puntos de coordenadas enteras.' },
      { id: 'fc2-4-7', front: 'Figura de la sección', back: 'Una recta sobre una grilla con el punto $A$ marcado y rotulado como solución de la ecuación.' },
    ],
  },
  '5': {
    quiz2: {
      tf: [
        { id: 'tf2-5-1', q: 'Los restos de dividir los enteros por $m$ se repiten con período $m$.', a: true, explain: 'Forman el ciclo $0; 1; \\dots; (m-1)$ que vuelve a empezar cada $m$ pasos.' },
        { id: 'tf2-5-2', q: 'La congruencia $a \\equiv b\\ (m)$ equivale a que $m$ divida a la suma $a + b$.', a: false, explain: 'Equivale a que $m$ divida a la <strong>diferencia</strong> $(b - a)$.' },
        { id: 'tf2-5-3', q: 'De $a \\equiv b\\ (n)$ se deduce que $a + r \\equiv b\\ (n)$ para todo entero $r$.', a: false, explain: 'La propiedad exige sumar $r$ en los dos miembros: lo que vale es $a + r \\equiv b + r\\ (n)$.' },
        { id: 'tf2-5-4', q: 'La Proposición 1 habilita a dividir miembro a miembro dos congruencias del mismo módulo.', a: false, explain: 'Las operaciones listadas son suma, resta, producto, potencia y producto o suma por un entero; la división no figura.' },
        { id: 'tf2-5-5', q: 'Para hallar el resto de una potencia grande se busca un exponente que dé congruencia con 1.', a: true, explain: 'Encontrado ese $n$, la potencia se descompone y solo sobrevive el sobrante del exponente.' },
      ],
      mc: [
        {
          id: 'mc2-5-1',
          q: 'La definición de congruencia módulo $m$ del apunte establece que:',
          options: [
            '$a \\equiv b\\ (m)$ si $(b - a) \\mid m$',
            '$a \\equiv b\\ (m)$ si $m \\mid (b - a)$',
            '$a \\equiv b\\ (m)$ si $m \\mid (b \\cdot a)$',
            '$a \\equiv b\\ (m)$ si $b \\mid (m - a)$',
          ],
          correctIndex: 1,
          explain: 'Es la Definición 2, con $m \\in \\mathbb{N}$ y $a, b \\in \\mathbb{Z}$.',
        },
        {
          id: 'mc2-5-2',
          q: 'La tercera formulación equivalente de la congruencia dice que:',
          options: [
            '$a = b \\cdot km$ para algún $k$ entero',
            '$a = b - km^2$ para algún $k$ entero',
            '$a = b + km$ para algún $k$ entero',
            '$a = km$ para algún $k$ entero',
          ],
          correctIndex: 2,
          explain: 'Uno es el otro más un múltiplo del módulo, lo que es otra forma de decir que tienen el mismo resto.',
        },
        {
          id: 'mc2-5-3',
          q: 'En el cálculo del resto de $11^{1243}$ por 7, el exponente hallado es:',
          options: ['$n = 2$', '$n = 3$', '$n = 4$', '$n = 7$'],
          correctIndex: 1,
          explain: 'Se prueba $n = 1$, $n = 2$ y $n = 3$, y recién ahí resulta $11^3 \\equiv 1\\ (7)$.',
        },
        {
          id: 'mc2-5-4',
          q: 'La división que se hace con el exponente 1243 en ese ejemplo es:',
          options: [
            '$1243 = 177 \\cdot 7 + 4$',
            '$1243 = 621 \\cdot 2 + 1$',
            '$1243 = 113 \\cdot 11 + 0$',
            '$1243 = 414 \\cdot 3 + 1$',
          ],
          correctIndex: 3,
          explain: 'Se divide el exponente por el $n$ hallado, que es 3, y sobra 1.',
        },
        {
          id: 'mc2-5-5',
          q: 'En el Ejemplo 2.2, la congruencia de partida para trabajar con $7^{135}$ es:',
          options: [
            '$7^2 \\equiv 1\\ (8)$',
            '$7^3 \\equiv 1\\ (8)$',
            '$7^2 \\equiv 7\\ (8)$',
            '$7^4 \\equiv 1\\ (8)$',
          ],
          correctIndex: 0,
          explain: 'Con $7^2 \\equiv 1\\ (8)$ y $135 = 2 \\cdot 67 + 1$, el residuo termina siendo 7.',
        },
      ],
      ms: [
        {
          id: 'ms2-5-1',
          q: '¿Qué operaciones entre congruencias del mismo módulo autoriza la Proposición 1?',
          options: [
            'Sumarlas miembro a miembro',
            'Restarlas miembro a miembro',
            'Multiplicarlas miembro a miembro',
            'Elevar ambos miembros a una potencia natural',
            'Dividirlas miembro a miembro',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La división no está entre las propiedades enunciadas.',
        },
        {
          id: 'ms2-5-2',
          q: '¿Qué congruencias intermedias aparecen al calcular el resto de $11^{1243}$ por 7?',
          options: [
            '$(11)^1 \\equiv 4\\ (7)$',
            '$(11)^2 \\equiv 2\\ (7)$',
            '$(11)^3 \\equiv 1\\ (7)$',
            '$(11)^4 \\equiv 4\\ (7)$',
            '$(11)^2 \\equiv 4\\ (7)$',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'El apunte solo calcula hasta $n = 3$; la cuarta potencia no se desarrolla y la última contradice el cálculo de $16 \\equiv 2$.',
        },
        {
          id: 'ms2-5-3',
          q: '¿Cuáles de estas afirmaciones son verdaderas para $m = 5$?',
          options: [
            '$12 \\equiv 2\\ (5)$',
            '$7 \\equiv 2\\ (5)$',
            '$9 \\equiv 4\\ (5)$',
            '$13 \\equiv 2\\ (5)$',
            '$11 \\equiv 2\\ (5)$',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'Dividiendo por 5: $12$ y $7$ dejan resto 2, y $9$ deja resto 4. En cambio $13$ deja resto 3 y $11$ deja resto 1, así que esas dos congruencias son falsas.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-5-1', front: 'Definición de congruencia', back: 'Con $m \\in \\mathbb{N}$ y $a, b \\in \\mathbb{Z}$: $a \\equiv b\\ (m) \\iff m \\mid (b - a)$.' },
      { id: 'fc2-5-2', front: 'Ciclo de restos módulo $m$', back: 'La secuencia $0; 1; 2; \\dots; (m-1)$ se repite indefinidamente, con período exactamente $m$.' },
      { id: 'fc2-5-3', front: 'Formulación con múltiplo', back: '$a = b + km$ para algún $k \\in \\mathbb{Z}$: equivale a decir que $a$ y $b$ son congruentes módulo $m$.' },
      { id: 'fc2-5-4', front: 'Formulación con restos', back: '$r_m(a) = r_m(b)$: ambos dejan el mismo resto al dividirlos por $m$.' },
      { id: 'fc2-5-5', front: 'Fórmula 2.2', back: '$\\forall\\, r, s \\in \\mathbb{Z}$: $ar + cs \\equiv br + ds\\ (n)$, que condensa las seis propiedades de la Proposición 1.' },
      { id: 'fc2-5-6', front: 'Estrategia para restos de potencias', back: 'Hallar el menor $n$ con $a^n \\equiv 1\\ (m)$, dividir el exponente por $n$ y quedarse con el resto de $a$ elevado al sobrante.' },
      { id: 'fc2-5-7', front: '$11^{1243}$ módulo 7', back: 'Con $11^3 \\equiv 1\\ (7)$ y $1243 = 414 \\cdot 3 + 1$, el resto es 4.' },
      { id: 'fc2-5-8', front: '$7^{135}$ módulo 8', back: 'Con $7^2 \\equiv 1\\ (8)$ y $135 = 2 \\cdot 67 + 1$, el residuo es 7.' },
    ],
  },
  '6': {
    quiz2: {
      tf: [
        { id: 'tf2-6-1', q: 'Una ecuación lineal de congruencia se puede reescribir como una ecuación diofántica.', a: true, explain: 'Es la Observación 1: $aX \\equiv b\\ (m)$ equivale a $aX - mt = b$ con $t$ entero.' },
        { id: 'tf2-6-2', q: 'La resolubilidad de $aX \\equiv b\\ (m)$ depende de que $b$ divida a $(a : m)$.', a: false, explain: 'Es al revés: hace falta que $(a : m)$ divida a $b$.' },
        { id: 'tf2-6-3', q: 'En una ecuación de congruencia solo se puede reducir módulo $m$ el término independiente.', a: false, explain: 'Se reducen todos los coeficientes: por eso $152X \\equiv -88\\ (36)$ pasa a $8X \\equiv 20\\ (36)$.' },
        { id: 'tf2-6-4', q: 'La Proposición 3 mantiene el módulo original al simplificar por un divisor común.', a: false, explain: 'El módulo también se divide por $d$: queda $\\dfrac{m}{d}$.' },
        { id: 'tf2-6-5', q: 'Si $a$ y $m$ son coprimos, la ecuación tiene solución para cualquier valor de $b$.', a: true, explain: 'Con $(a : m) = 1$, ese 1 divide a todo $b$, así que la condición se cumple siempre.' },
      ],
      mc: [
        {
          id: 'mc2-6-1',
          q: 'La cantidad de soluciones en $\\mathbb{Z}_{36}$ de $8X \\equiv 20\\ (36)$ es:',
          options: ['9 soluciones', '2 soluciones', '4 soluciones', '20 soluciones'],
          correctIndex: 2,
          explain: 'Coincide con $d = (8 : 36) = 4$, el máximo común divisor entre el coeficiente y el módulo.',
        },
        {
          id: 'mc2-6-2',
          q: 'La combinación lineal que da Euclides en el Ejemplo 2.3 es:',
          options: [
            '$4 = 8 \\cdot 4 - 36 \\cdot 1$',
            '$4 = 8(-5) + 36 \\cdot 1$',
            '$4 = 8(-4) + 36 \\cdot 1$',
            '$4 = 8 \\cdot 1 - 36(-4)$',
          ],
          correctIndex: 2,
          explain: 'Multiplicada por 5 da $20 = 8(-20) + 36 \\cdot 5$, de donde $-20$ es solución.',
        },
        {
          id: 'mc2-6-3',
          q: 'Las soluciones del Ejemplo 2.3 se generan a partir de $-20$ sumando:',
          options: ['4 cada vez', '36 cada vez', '20 cada vez', '9 cada vez'],
          correctIndex: 3,
          explain: 'Se suma $m/d = 36/4 = 9$, obteniendo $-20, -11, -2$ y $7$.',
        },
        {
          id: 'mc2-6-4',
          q: 'Un entero $X$ verifica $152X \\equiv -88\\ (36)$ exactamente cuando su resto módulo 36 es:',
          options: [
            '$7, 16, 25$ o $34$',
            '$4, 13, 22$ o $31$',
            '$0, 9, 18$ o $27$',
            '$8, 17, 26$ o $35$',
          ],
          correctIndex: 0,
          explain: 'Son los representantes canónicos de las cuatro clases solución.',
        },
        {
          id: 'mc2-6-5',
          q: 'La demostración de la Proposición 2 se apoya en:',
          options: [
            'La fórmula de la solución general de una diofántica',
            'El ciclo de restos de período $m$ en los enteros',
            'La equivalencia con la diofántica $ax + my = b$',
            'La reducción de los coeficientes módulo $m$',
          ],
          correctIndex: 2,
          explain: 'Al ser equivalentes, se aplica la condición de existencia ya probada para diofánticas.',
        },
      ],
      ms: [
        {
          id: 'ms2-6-1',
          q: '¿Qué hipótesis pide la Proposición 3 sobre el entero $d$?',
          options: [
            'Que $d$ sea mayor que cero',
            'Que $d$ divida a $a$',
            'Que $d$ divida a $b$',
            'Que $d$ divida a $m$',
            'Que $d$ sea coprimo con $m$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'Si $d$ divide a $m$ no puede ser coprimo con él (salvo $d = 1$), así que la última opción contradice a las otras.',
        },
        {
          id: 'ms2-6-2',
          q: '¿Cuáles de estas ecuaciones de congruencia son resolubles?',
          options: [
            '$8X \\equiv 20\\ (36)$',
            '$6X \\equiv 4\\ (9)$',
            '$5X \\equiv 3\\ (7)$',
            '$4X \\equiv 6\\ (8)$',
            '$3X \\equiv 5\\ (6)$',
          ],
          correctIndexes: [0, 2],
          explain: 'En la segunda $(6 : 9) = 3$ y $3 \\nmid 4$; en la cuarta $(4 : 8) = 4$ y $4 \\nmid 6$; en la quinta $(3 : 6) = 3$ y $3 \\nmid 5$.',
        },
        {
          id: 'ms2-6-3',
          q: '¿Qué afirma el apunte sobre el conjunto de soluciones de una ecuación modular?',
          options: [
            'Todo entero congruente con una solución también es solución',
            'La cantidad de clases solución coincide con $(a : m)$',
            'Las soluciones se pueden escribir con representantes canónicos',
            'Una solución particular se obtiene con el algoritmo de Euclides',
            'El conjunto de soluciones siempre tiene un único elemento',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'Nunca hay un único elemento: si existe una solución, cada clase módulo $m$ aporta infinitos enteros.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-6-1', front: 'Ecuación 2.5', back: '$aX \\equiv b\\ (m)$, con $a, b \\in \\mathbb{Z}$ y $m \\in \\mathbb{N}$: la ecuación lineal de congruencia.' },
      { id: 'fc2-6-2', front: 'Puente con las diofánticas', back: 'Si $X$ es solución, existe $t \\in \\mathbb{Z}$ con $aX = b + mt$, o sea $aX - mt = b$.' },
      { id: 'fc2-6-3', front: 'Criterio de resolubilidad', back: 'La ecuación $aX \\equiv b\\ (m)$ tiene solución si y solo si $(a : m) \\mid b$.' },
      { id: 'fc2-6-4', front: '¿Cuántas soluciones hay en $\\mathbb{Z}_m$?', back: 'Tantas como el valor de $d = (a : m)$; en el ejemplo con módulo 36 y $d = 4$, son cuatro.' },
      { id: 'fc2-6-5', front: 'Reducción de coeficientes', back: 'Se pueden reemplazar $a$ y $b$ por sus restos módulo $m$: $152X \\equiv -88\\ (36)$ pasa a $8X \\equiv 20\\ (36)$.' },
      { id: 'fc2-6-6', front: 'Cómo se halla una solución particular', back: 'Con Euclides se escribe $(a : m)$ como combinación lineal y se ajusta el factor: $4 = 8(-4) + 36 \\cdot 1$, por 5 da $-20$.' },
      { id: 'fc2-6-7', front: 'Paso entre soluciones', back: 'Se suma $m/d$: en el ejemplo, $9$, generando $-20, -11, -2, 7$.' },
      { id: 'fc2-6-8', front: 'Proposición 3', back: 'Si $d > 0$ divide a $a$, $b$ y $m$, entonces $aX \\equiv b\\ (m)$ es resoluble si y solo si lo es $\\dfrac{a}{d}X \\equiv \\dfrac{b}{d}\\ \\left(\\dfrac{m}{d}\\right)$.' },
    ],
  },
  '7': {
    quiz2: {
      tf: [
        { id: 'tf2-7-1', q: 'El apunte presenta los sistemas lineales como un problema reciente de la matemática.', a: false, explain: 'Los describe como uno de los <strong>más antiguos</strong> de la matemática.' },
        { id: 'tf2-7-2', q: 'La información sísmica de la exploración petrolera se recoge con geófonos.', a: true, explain: 'Están conectados a extensos cables instalados debajo del barco.' },
        { id: 'tf2-7-3', q: 'Los modelos de programación lineal de las aerolíneas manejan cientos de variables.', a: true, explain: 'Y sobre ellos se toman decisiones administrativas importantes.' },
        { id: 'tf2-7-4', q: 'Los microchips que menciona el apunte incluyen miles de transistores.', a: false, explain: 'Habla de circuitos y microchips con <strong>millones</strong> de transistores.' },
        { id: 'tf2-7-5', q: 'Entre las aplicaciones listadas figura la aproximación de problemas no lineales de análisis numérico.', a: true, explain: 'Aparece en la enumeración inicial, junto con señales, análisis estructural, estimación y predicción.' },
      ],
      mc: [
        {
          id: 'mc2-7-1',
          q: 'Las ondas usadas en la exploración petrolera se generan mediante:',
          options: [
            'Explosiones con pistolas de aire',
            'Pulsos emitidos por boyas de superficie',
            'Vibraciones del casco del barco',
            'Descargas eléctricas submarinas',
          ],
          correctIndex: 0,
          explain: 'Las ondas de choque submarinas se crean con pistolas de aire y rebotan en las rocas del fondo.',
        },
        {
          id: 'mc2-7-2',
          q: 'La cantidad de sistemas que resuelven a diario las computadoras del barco es del orden de:',
          options: ['Decenas', 'Centenas', 'Millares', 'Unidades'],
          correctIndex: 2,
          explain: 'El apunte dice que resuelven miles de sistemas de ecuaciones lineales por separado.',
        },
        {
          id: 'mc2-7-3',
          q: 'Entre los usos aeronáuticos que enumera el apunte NO figura:',
          options: [
            'Crear itinerarios de tripulaciones de vuelo',
            'Planear servicios de mantenimiento y terminal',
            'Monitorear las ubicaciones de los aviones',
            'Calcular la carga de combustible por vuelo',
          ],
          correctIndex: 3,
          explain: 'Los tres primeros son textuales del apunte; el cálculo de combustible no aparece.',
        },
        {
          id: 'mc2-7-4',
          q: 'Las técnicas que emplean los programas de simulación de circuitos son de:',
          options: [
            'Estadística descriptiva y muestreo aleatorio',
            'Álgebra lineal y sistemas de ecuaciones',
            'Cálculo diferencial de varias variables',
            'Teoría de grafos y algoritmos de flujo',
          ],
          correctIndex: 1,
          explain: 'Es la frase con la que cierra la sección sobre redes eléctricas.',
        },
        {
          id: 'mc2-7-5',
          q: 'La sección de aplicaciones desarrolla en detalle:',
          options: [
            'Dos casos de la vida real',
            'Cinco casos de la vida real',
            'Cuatro casos de la vida real',
            'Tres casos de la vida real',
          ],
          correctIndex: 3,
          explain: 'Exploración petrolera, programación lineal y redes eléctricas.',
        },
      ],
      ms: [
        {
          id: 'ms2-7-1',
          q: '¿Qué campos de aplicación enumera la introducción de la sección?',
          options: [
            'Procesamiento digital de señales',
            'Análisis estructural',
            'Estimación y predicción',
            'Programación lineal',
            'Diseño de algoritmos de compresión',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La compresión de datos no está en la lista del apunte.',
        },
        {
          id: 'ms2-7-2',
          q: '¿Qué elementos intervienen en el caso de la exploración petrolera?',
          options: [
            'Ondas de choque submarinas',
            'Pistolas de aire',
            'Geófonos conectados a cables',
            'Rocas bajo la superficie marina',
            'Satélites de posicionamiento',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'Los satélites no se mencionan; todo el registro se hace con los geófonos remolcados por el barco.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-7-1', front: 'Antigüedad del problema', back: 'Los sistemas lineales de ecuaciones son uno de los problemas más antiguos de la matemática.' },
      { id: 'fc2-7-2', front: 'Campos de aplicación generales', back: 'Procesamiento digital de señales, análisis estructural, estimación, predicción, programación lineal y análisis numérico no lineal.' },
      { id: 'fc2-7-3', front: 'Método de la exploración petrolera', back: 'Explosiones con pistolas de aire generan ondas que rebotan en las rocas; los geófonos las miden y con esos datos se arman las ecuaciones.' },
      { id: 'fc2-7-4', front: 'Escala del cálculo en el barco', back: 'Miles de sistemas de ecuaciones lineales resueltos por separado cada día.' },
      { id: 'fc2-7-5', front: 'Usos aeronáuticos', back: 'Itinerarios de tripulaciones, monitoreo de ubicación de aviones y planificación de mantenimiento y operaciones en terminal.' },
      { id: 'fc2-7-6', front: 'Escala de los microchips', back: 'Circuitos y microchips con millones de transistores, simulados con técnicas de álgebra lineal.' },
      { id: 'fc2-7-7', front: 'Los tres casos desarrollados', back: 'Exploración petrolera, programación lineal y redes eléctricas.' },
    ],
  },
  '14': {
    quiz2: {
      tf: [
        { id: 'tf2-14-1', q: 'El ciclo FOR del ejemplo acumula en una variable la suma de los primeros veinte números.', a: true, explain: 'Parte de cero y en cada paso $i$ le agrega $i$.' },
        { id: 'tf2-14-2', q: 'El costo del ciclo se describe como 20 evaluaciones por tres líneas de código.', a: true, explain: 'Ese costo es lo que motiva buscar una fórmula cerrada.' },
        { id: 'tf2-14-3', q: 'Cambiar el nombre del índice de una sumatoria altera el valor del resultado.', a: false, explain: 'El índice es mudo: el apunte lo muestra usando “pepe” como nombre de índice.' },
        { id: 'tf2-14-4', q: 'La sumatoria funciona como un ciclo <code>for</code> que arranca con total inicial cero.', a: true, explain: 'A cada valor del índice se asocia una cantidad que se suma al total acumulado.' },
        { id: 'tf2-14-5', q: 'La suma $1 + 2 + 4 + 8 + \\dots + 2^{n}$ se escribe con índice arrancando en 1.', a: false, explain: 'Arranca en 0, porque el primer término es $2^{0} = 1$: $\\sum_{m=0}^{n} 2^{m}$.' },
      ],
      mc: [
        {
          id: 'mc2-14-1',
          q: 'La fórmula que el apunte propone como alternativa al ciclo FOR es:',
          options: [
            '$\\dfrac{n(n+1)}{2}$',
            '$\\dfrac{n(n-1)}{2}$',
            '$\\dfrac{n(2n+1)}{6}$',
            '$n^{2} + n$',
          ],
          correctIndex: 0,
          explain: 'Resuelve la suma de los primeros $n$ números en una sola operación.',
        },
        {
          id: 'mc2-14-2',
          q: 'La pregunta con la que el apunte cierra la sección del ciclo FOR apunta a:',
          options: [
            'Cuántas variables hacen falta para escribir el ciclo',
            'Si verificar unos pocos casos alcanza como comprobación',
            'Qué lenguaje de programación conviene usar',
            'Cómo optimizar la asignación de memoria',
          ],
          correctIndex: 1,
          explain: 'Esa duda es la puerta de entrada al principio de inducción matemática.',
        },
        {
          id: 'mc2-14-3',
          q: 'El valor de la sumatoria del índice desde 1 hasta 5 del propio índice es:',
          options: ['10', '14', '15', '21'],
          correctIndex: 2,
          explain: '$1 + 2 + 3 + 4 + 5 = 15$, el primer resultado del Ejemplo 1.',
        },
        {
          id: 'mc2-14-4',
          q: 'La expresión $1 \\cdot 5 + 2 \\cdot 4 + 3 \\cdot 3 + 4 \\cdot 2 + 5 \\cdot 1$ se escribe como:',
          options: [
            '$\\sum_{k=1}^{5} k \\ast (5 - k)$',
            '$\\sum_{k=0}^{4} k \\ast (6 - k)$',
            '$\\sum_{k=1}^{5} (6 - k)^{2}$',
            '$\\sum_{k=1}^{5} k \\ast (6 - k)$',
          ],
          correctIndex: 3,
          explain: 'En cada término los dos factores suman 6.',
        },
        {
          id: 'mc2-14-5',
          q: 'La lectura correcta del símbolo de sumatoria con índice $m$ de 0 a $n$ es:',
          options: [
            'Sumatoria sobre un índice $m$ desde 0 hasta $n$',
            'Producto sobre un índice $m$ desde 0 hasta $n$',
            'Promedio de los valores entre 0 y $n$',
            'Cantidad de términos entre 0 y $n$',
          ],
          correctIndex: 0,
          explain: 'Genera un contador que recorre los naturales acumulando en cada paso.',
        },
      ],
      ms: [
        {
          id: 'ms2-14-1',
          q: '¿Qué resultados corresponden al Ejemplo 1 de sumatorias?',
          options: ['15', '14', '$5n^2$', '20', '$n^2$'],
          correctIndexes: [0, 1, 2],
          explain: 'La solución publicada es exactamente “15, 14 (el índice es mudo), $5n^2$”.',
        },
        {
          id: 'ms2-14-2',
          q: '¿Qué características del ciclo FOR describe el apunte?',
          options: [
            'La variable se inicializa en cero',
            'El paso $i$ agrega la cantidad $i$',
            'El total resultante es la suma de los primeros 20 números',
            'Evalúa 20 veces por cada ciclo',
            'Usa recursión en lugar de iteración',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'No hay recursión en ningún punto: es un ciclo iterativo simple.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-14-1', front: 'Costo del ciclo FOR del ejemplo', back: '20 evaluaciones por cada ciclo, sobre tres líneas de código.' },
      { id: 'fc2-14-2', front: 'Fórmula cerrada buscada', back: '$\\text{suma}(n) = \\dfrac{n(n+1)}{2}$, que hace en una operación lo que el ciclo hace en 20 pasos.' },
      { id: 'fc2-14-3', front: 'La pregunta que abre la unidad', back: '¿Alcanza con verificar la fórmula para los primeros 5 números? De ahí nace la necesidad de la inducción.' },
      { id: 'fc2-14-4', front: 'Sumatoria como ciclo', back: 'A cada valor del índice se le asocia una cantidad que se suma al total previo, empezando en cero.' },
      { id: 'fc2-14-5', front: 'Índice mudo', back: 'El nombre del índice no cambia el resultado de la sumatoria.' },
      { id: 'fc2-14-6', front: 'Sumatoria de potencias de 2', back: '$1 + 2 + 4 + \\dots + 2^{n} = \\sum_{m=0}^{n} 2^{m}$, con el índice arrancando en 0.' },
      { id: 'fc2-14-7', front: 'Truco del producto cruzado', back: 'En $1\\cdot5 + 2\\cdot4 + \\dots + 5\\cdot1$ los factores suman 6 en cada término: $\\sum_{k=1}^{5} k \\ast (6-k)$.' },
    ],
  },
  '15': {
    quiz2: {
      tf: [
        { id: 'tf2-15-1', q: 'El paso base puede verificarse en un entero $N$ distinto de 1.', a: true, explain: 'El apunte dice “por lo general $N = 1$”, dejando abierta otra elección.' },
        { id: 'tf2-15-2', q: 'Escribir explícitamente la hipótesis inductiva es un formalismo que se puede omitir.', a: false, explain: 'El apunte aclara que parece banal pero es necesario porque ayuda en la demostración.' },
        { id: 'tf2-15-3', q: 'La demostración se construye partiendo del primer miembro de la tesis.', a: true, explain: 'Y usando la hipótesis inductiva se llega al segundo miembro.' },
        { id: 'tf2-15-4', q: 'Con dos pasos la inducción cubre una cantidad infinita de casos.', a: true, explain: 'Esa es la ventaja que el apunte destaca como “una magnífica idea”.' },
        { id: 'tf2-15-5', q: 'La sumatoria de Gauss se demuestra sin recurrir al principio de inducción.', a: false, explain: 'El Ejemplo 3.2 la demuestra siguiendo los cuatro pasos del método.' },
      ],
      mc: [
        {
          id: 'mc2-15-1',
          q: 'El nombre que recibe la suposición de que la afirmación vale para $k$ es:',
          options: ['Tesis inductiva', 'Paso base', 'Hipótesis de inducción', 'Paso de inducción'],
          correctIndex: 2,
          explain: 'El paso de inducción es el uso posterior de esa hipótesis para llegar a $k+1$.',
        },
        {
          id: 'mc2-15-2',
          q: 'La reescritura que permite aplicar la hipótesis en el Ejemplo 3.1 es:',
          options: [
            '$2^{k+1} = 2 \\cdot 2^{k} = 2^{k} + 2^{k}$',
            '$2^{k+1} = 2^{k} \\cdot k$',
            '$2^{k+1} = (k+1)^{2}$',
            '$2^{k+1} = 2^{k} + 1$',
          ],
          correctIndex: 0,
          explain: 'Con $2^{k} > k$ se sigue $2^{k} + 2^{k} > k + k > k + 1$.',
        },
        {
          id: 'mc2-15-3',
          q: 'El paso 3 del método consiste en:',
          options: [
            'Verificar el caso inicial',
            'Enunciar la afirmación para $k+1$',
            'Suponer válido el caso $k$',
            'Cerrar la demostración con la conclusión general',
          ],
          correctIndex: 1,
          explain: 'Es la tesis; recién en el paso 4 se la demuestra.',
        },
        {
          id: 'mc2-15-4',
          q: 'Al separar el último término, $\\sum_{j=1}^{k+1} j$ se reescribe como:',
          options: [
            '$\\sum_{j=1}^{k} j \\cdot (k+1)$',
            '$\\sum_{j=1}^{k+1} (j - 1) + 1$',
            '$\\sum_{j=1}^{k} j + (k+1)$',
            '$\\sum_{j=0}^{k} j + k$',
          ],
          correctIndex: 2,
          explain: 'Eso deja a la vista la sumatoria hasta $k$, donde entra la hipótesis inductiva.',
        },
        {
          id: 'mc2-15-5',
          q: 'Según el apunte, resolver algunos casos numéricos de una fórmula:',
          options: [
            'Equivale a demostrarla para todo $n$',
            'Solo persuade, sin llegar a probar la afirmación',
            'Invalida la necesidad del paso base',
            'Reemplaza a la hipótesis inductiva',
          ],
          correctIndex: 1,
          explain: 'Es lo que señala la Observación 1 sobre la fórmula 3.3.',
        },
      ],
      ms: [
        {
          id: 'ms2-15-1',
          q: '¿Qué nombres asigna el apunte a las etapas del razonamiento?',
          options: ['Paso base', 'Hipótesis de inducción', 'Paso de inducción', 'Tesis', 'Contraejemplo'],
          correctIndexes: [0, 1, 2, 3],
          explain: 'El contraejemplo no forma parte del método de inducción descripto.',
        },
        {
          id: 'ms2-15-2',
          q: '¿Qué expresiones aparecen en la demostración de la sumatoria de Gauss?',
          options: [
            '$\\dfrac{(1)(1+1)}{2} = 1$',
            '$\\sum_{j=1}^{k} j = \\dfrac{k(k+1)}{2}$',
            '$\\dfrac{k(k+1) + 2(k+1)}{2}$',
            '$\\dfrac{(k+1)(k+2)}{2}$',
            '$\\dfrac{k(k+1)(2k+1)}{6}$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La última pertenece al ejemplo de la suma de cuadrados, no al de Gauss.',
        },
        {
          id: 'ms2-15-3',
          q: '¿Qué afirma el apunte sobre la dificultad relativa de los pasos?',
          options: [
            'El paso 1 suele ser sencillo',
            'El paso 2 suele ser el más difícil',
            'La inducción puede resultar difícil a primera vista',
            'En el ejemplo de Gauss el paso 1 se resuelve reemplazando $n = 1$',
            'El paso 4 es siempre trivial',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'El paso 4 es donde va todo el trabajo algebraico: nunca se lo califica de trivial.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-15-1', front: 'Qué prueba la inducción', back: 'Que una afirmación o ecuación se cumple para todo entero positivo mayor o igual que el $N$ del paso base.' },
      { id: 'fc2-15-2', front: 'Paso 1 y paso 2', back: 'Base inductiva: verificar $\\mathcal{A}(N)$. Hipótesis inductiva: suponer $\\mathcal{A}(k)$ cierta para $k \\geq N$.' },
      { id: 'fc2-15-3', front: 'Paso 3 y paso 4', back: 'Tesis: escribir $\\mathcal{A}(k+1)$. Demostración: partir del primer miembro y llegar al segundo usando la hipótesis.' },
      { id: 'fc2-15-4', front: 'Implicación central del método', back: '$\\mathcal{A}(k) \\longrightarrow \\mathcal{A}(k+1)$.' },
      { id: 'fc2-15-5', front: 'Por qué escribir la hipótesis', back: 'Parece banal, pero explicitarla es lo que después permite usarla en la demostración.' },
      { id: 'fc2-15-6', front: 'Cadena del Ejemplo 3.1', back: '$2^{k+1} = 2 \\cdot 2^{k} = 2^{k} + 2^{k} > k + k > k + 1$.' },
      { id: 'fc2-15-7', front: 'Sumatoria de Gauss', back: '$\\sum_{j=1}^{n} j = \\dfrac{n(n+1)}{2}$, demostrada en el Ejemplo 3.2.' },
      { id: 'fc2-15-8', front: 'Alcance de los ejemplos numéricos', back: 'Persuaden de que la fórmula funciona, pero no prueban nada (Observación 1).' },
    ],
  },
  '16': {
    quiz2: {
      tf: [
        { id: 'tf2-16-1', q: 'La fórmula de la suma de los primeros cuadrados lleva un 6 en el denominador.', a: true, explain: '$\\sum_{j=1}^{n} j^{2} = \\dfrac{n(n+1)(2n+1)}{6}$.' },
        { id: 'tf2-16-2', q: 'En el paso inductivo de la suma de cuadrados se saca factor común $(k+1)/6$.', a: true, explain: 'Ese factor común es el que deja el corchete $[\\,k(2k+1) + 6(k+1)\\,]$.' },
        { id: 'tf2-16-3', q: 'El razonamiento sobre los caballos llega a una conclusión verdadera.', a: false, explain: 'Concluye que todos los caballos tienen el mismo color, lo cual es falso: el ejercicio pide hallar el error.' },
        { id: 'tf2-16-4', q: 'En el ejercicio de práctica, la desigualdad $2^{n} < n!$ se plantea a partir de $n > 4$.', a: true, explain: 'Por eso su paso base no puede tomarse en $n = 1$.' },
        { id: 'tf2-16-5', q: 'La suma de los primeros $n$ números impares equivale a $n(n+1)$.', a: false, explain: 'Equivale a $n^{2}$; $n(n+1)$ corresponde a la suma de los primeros $n$ pares.' },
      ],
      mc: [
        {
          id: 'mc2-16-1',
          q: 'El polinomio que aparece dentro del corchete en el paso inductivo se factoriza como:',
          options: [
            '$(2k+1)(k+3)$',
            '$(k+1)(2k+6)$',
            '$(2k+3)(k+2)$',
            '$(k+2)(k+3)$',
          ],
          correctIndex: 2,
          explain: '$2k^{2} + 7k + 6 = (2k+3)(k+2)$, que es la forma requerida por la tesis.',
        },
        {
          id: 'mc2-16-2',
          q: 'En el razonamiento sobre los caballos, los subconjuntos auxiliares se construyen para que:',
          options: [
            'Cada uno tenga exactamente $k$ elementos',
            'Cada uno tenga exactamente un elemento',
            'Su unión tenga $k$ elementos',
            'Su intersección sea vacía',
          ],
          correctIndex: 0,
          explain: 'Solo así se les puede aplicar la hipótesis inductiva del caso $k$.',
        },
        {
          id: 'mc2-16-3',
          q: 'La suma $2 + 5 + 8 + \\dots + (3n-1)$ del ejercicio de práctica equivale a:',
          options: [
            '$\\dfrac{n(3n+1)}{2}$',
            '$\\dfrac{n(3n-1)}{2}$',
            '$n(n+1)$',
            '$\\dfrac{n(n+1)}{2}$',
          ],
          correctIndex: 0,
          explain: 'Es el segundo punto de la Pregunta 1 de la guía.',
        },
        {
          id: 'mc2-16-4',
          q: 'La verificación del caso inicial en la suma de cuadrados da:',
          options: [
            '$\\dfrac{1 \\cdot 2 \\cdot 3}{6} = 1 = 1^{2}$',
            '$\\dfrac{1 \\cdot 2}{2} = 1 = 1^{2}$',
            '$\\dfrac{1 \\cdot 2 \\cdot 3}{6} = 6$',
            '$\\dfrac{2 \\cdot 3 \\cdot 5}{6} = 5$',
          ],
          correctIndex: 0,
          explain: 'Reemplazando $n = 1$ en la fórmula 3.4 se obtiene 1, que coincide con $1^{2}$.',
        },
        {
          id: 'mc2-16-5',
          q: 'La suma $1 + 2 + 4 + 8 + \\dots + 2^{n}$ del ejercicio de práctica equivale a:',
          options: ['$2^{n} - 1$', '$2^{n+1} - 1$', '$2^{n+1}$', '$2n + 1$'],
          correctIndex: 1,
          explain: 'Es el sexto punto de la Pregunta 1 de la guía.',
        },
      ],
      ms: [
        {
          id: 'ms2-16-1',
          q: '¿Qué expresiones intervienen en el paso inductivo de la suma de cuadrados?',
          options: [
            '$\\sum_{j=1}^{k} j^{2} + (k+1)^{2}$',
            '$\\dfrac{k(k+1)(2k+1) + 6(k+1)^{2}}{6}$',
            '$\\dfrac{(k+1)}{6}[\\,2k^{2} + 7k + 6\\,]$',
            '$\\dfrac{(k+1)(k+2)[\\,2(k+1)+1\\,]}{6}$',
            '$\\dfrac{(k+1)(k+2)}{2}$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La última corresponde al cierre de la sumatoria de Gauss, no al de cuadrados.',
        },
        {
          id: 'ms2-16-2',
          q: '¿Qué enunciados figuran en la Pregunta 1 de la guía de ejercitación?',
          options: [
            '$2 + 4 + \\dots + 2n = n(n+1)$',
            '$1 + 3 + \\dots + (2n-1) = n^{2}$',
            '$\\left(\\dfrac{1}{2}\\right)^{n} < \\dfrac{1}{n}$',
            '$2^{n} < n!$ para $n > 4$',
            '$n^{3} - n$ es múltiplo de 6',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'El enunciado sobre múltiplos de 6 no aparece en la guía.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-16-1', front: 'Suma de los primeros cuadrados', back: '$\\sum_{j=1}^{n} j^{2} = \\dfrac{n(n+1)(2n+1)}{6}$ (ecuación 3.4).' },
      { id: 'fc2-16-2', front: 'Primer movimiento del paso inductivo', back: 'Separar el último término: $\\sum_{j=1}^{k+1} j^{2} = \\sum_{j=1}^{k} j^{2} + (k+1)^{2}$.' },
      { id: 'fc2-16-3', front: 'Factorización necesaria', back: '$2k^{2} + 7k + 6 = (2k+3)(k+2)$, para reconocer la forma de la tesis.' },
      { id: 'fc2-16-4', front: 'El ejercicio de los caballos', back: 'Una demostración inductiva aparente de que todos los caballos de un conjunto comparten color; el ejercicio consiste en detectar la falla.' },
      { id: 'fc2-16-5', front: 'Construcción de $S_1$ y $S_2$', back: 'Dos subconjuntos de $k$ caballos cada uno, solapados, tomados de los $k+1$ del conjunto $S$.' },
      { id: 'fc2-16-6', front: 'Sumas de la guía', back: 'Pares: $n(n+1)$. Impares: $n^{2}$. Progresión $3n-1$: $\\dfrac{n(3n+1)}{2}$. Potencias de 2: $2^{n+1}-1$.' },
      { id: 'fc2-16-7', front: 'Desigualdades de la guía', back: '$\\left(\\dfrac{1}{2}\\right)^{n} < \\dfrac{1}{n}$, y $2^{n} < n!$ restringida a $n > 4$.' },
    ],
  },
};
