/**
 * Banco NUEVO (anti-spoiler) — algebra-lineal
 *
 * Mapa { [sectionId]: { quiz2: { tf, mc, ms }, flashcards2: [...] } }.
 * content.js mergea esto sobre las secciones por id (sec.quiz2 / sec.flashcards2).
 * Generado para autoevaluación: opciones homogéneas, sin pistas de forma.
 */
export default {
  '1': {
    quiz2: {
      tf: [
        { id: 'tf2-1-1', q: 'La función hash del Ejemplo 2.1 asigna cada objeto a una caja según la cantidad de letras de su nombre en singular.', a: true, explain: 'Es el algoritmo elegido en el ejemplo: "gato" tiene 4 letras y va a la caja 4.' },
        { id: 'tf2-1-2', q: 'Dos objetos distintos con el mismo hashcode se guardan en cajas distintas.', a: false, explain: 'Con el mismo hashcode van a la misma caja; eso es una colisión y el apunte la contempla como algo normal.' },
        { id: 'tf2-1-3', q: 'El número inicial de cajas de una Hashtable se puede fijar al construirla.', a: true, explain: 'Se especifica un entero en la función de inicialización o constructor, lo que baja el promedio de objetos por caja.' },
        { id: 'tf2-1-4', q: 'Conociendo el hashcode de un objeto se puede reconstruir el objeto original.', a: false, explain: 'El apunte lo descarta con el ejemplo de Perro y $291564382$: el número no se puede convertir de vuelta.' },
        { id: 'tf2-1-5', q: 'Buscar dentro de una caja con varios objetos sigue siendo más rápido que la búsqueda lineal completa.', a: true, explain: 'Se compara contra los pocos objetos de esa caja en vez de contra toda la colección.' },
      ],
      mc: [
        {
          id: 'mc2-1-1',
          q: 'Con el algoritmo modificado del Ejemplo 2.1, un objeto cuyo nombre tiene 12 letras se guarda en la caja:',
          options: ['Caja 1', 'Caja 3', 'Caja 2', 'Caja 4'],
          correctIndex: 2,
          explain: 'La regla ajustada manda los de 11 letras a la caja 1, los de 12 a la caja 2, los de 13 a la caja 3, y así.',
        },
        {
          id: 'mc2-1-2',
          q: 'El apunte compara la tabla hash con el trabajo de una impresora porque:',
          options: [
            'Cada tipo de letra tiene su propio compartimento y se busca solo ahí',
            'Cada tipo de letra se imprime en el orden en que llega al cajón',
            'Cada tipo de letra se compara contra todos los demás antes de usarse',
            'Cada tipo de letra se guarda ordenado alfabéticamente en un cajón',
          ],
          correctIndex: 0,
          explain: 'La analogía es la del compartimento por tipo: se busca una A solo en el compartimento de las A.',
        },
        {
          id: 'mc2-1-3',
          q: 'En una tabla con 10 cajas, ¿qué códigos hash comparten casilla con el valor $218714508$?',
          options: [
            'Los códigos $80, 800, 8000$ y siguientes',
            'Los códigos $8, 18, 28$ y siguientes',
            'Los códigos $9, 19, 29$ y siguientes',
            'Los códigos $2, 12, 22$ y siguientes',
          ],
          correctIndex: 1,
          explain: 'Ese código cae en la casilla 8, igual que todos los que terminan en 8.',
        },
        {
          id: 'mc2-1-4',
          q: 'Según el apunte, el valor concreto del código hash para el programador es que:',
          options: [
            'Reduce el espacio que ocupa el objeto en memoria',
            'Permite recuperar los datos internos del objeto',
            'Garantiza que cada objeto quede en una caja distinta',
            'Funciona como id de búsqueda dentro de la tabla hash',
          ],
          correctIndex: 3,
          explain: 'El apunte es explícito: fuera de servir como índice de búsqueda, el hash no le aporta otra utilidad.',
        },
        {
          id: 'mc2-1-5',
          q: 'Si se planea guardar muchos elementos en una Hashtable, conviene:',
          options: [
            'Especificar un número menor de cajas al construirla',
            'Recalcular el hashcode de cada objeto al insertarlo',
            'Ordenar los objetos antes de calcular su hashcode',
            'Especificar un número mayor de cajas al construirla',
          ],
          correctIndex: 3,
          explain: 'Más cajas implica menos objetos promedio por caja, y por lo tanto búsquedas más cortas dentro de cada una.',
        },
      ],
      ms: [
        {
          id: 'ms2-1-1',
          q: '¿Qué características del código hash menciona el apunte?',
          options: [
            'Genera un número para cualquier objeto',
            'Puede repetirse entre objetos distintos',
            'Sirve como índice para ubicar el objeto',
            'Permite reconstruir el objeto original',
            'Ordena la colección de menor a mayor',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'Ni se puede invertir ni ordena nada: solo produce el número que decide la caja.',
        },
        {
          id: 'ms2-1-2',
          q: 'Con el algoritmo original del ejemplo (cantidad de letras en singular), ¿qué asignaciones son válidas?',
          options: [
            'perro va a la caja 5',
            'ballena va a la caja 7',
            'gato va a la caja 4',
            'perros va a la caja 6',
            'ballenas va a la caja 8',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'El nombre se toma siempre en singular, así que los plurales quedan fuera del algoritmo.',
        },
        {
          id: 'ms2-1-3',
          q: '¿Qué estructuras de las nombradas por el apunte se apoyan en el código hash?',
          options: [
            'HashMap',
            'ArrayList',
            'HashSet',
            'Hashtable',
            'LinkedList',
          ],
          correctIndexes: [0, 2, 3],
          explain: 'Las listas no usan hash: el apunte solo cita HashMap, HashSet y Hashtable.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-1-1', front: '¿Qué produce una función hashcode?', back: 'Un número asociado a cualquier objeto, que se usa para decidir en qué compartimento se guarda o se busca.' },
      { id: 'fc2-1-2', front: 'Colisión', back: 'Dos o más objetos con el mismo código hash comparten caja. Se resuelve comparando solo dentro de esa caja.' },
      { id: 'fc2-1-3', front: 'Regla del Ejemplo 2.1 para nombres largos', back: 'Los objetos de 11 letras van a la caja 1, los de 12 a la caja 2, y así siguiendo, porque solo hay cajas de 0 a 9.' },
      { id: 'fc2-1-4', front: 'Irreversibilidad del hash', back: 'Del objeto se obtiene el número, pero del número no se vuelve al objeto: Perro → $291564382$ no tiene vuelta.' },
      { id: 'fc2-1-5', front: 'Parámetro del constructor de una Hashtable', back: 'Un entero con la cantidad inicial de cajas; conviene agrandarlo si se van a guardar muchos elementos.' },
      { id: 'fc2-1-6', front: 'Comparación con la búsqueda lineal', back: 'La búsqueda lineal revisa toda la colección; con hash se revisa una sola caja, así que es mucho más ágil.' },
      { id: 'fc2-1-7', front: 'Analogía de la impresora', back: 'Los tipos A se guardan y se buscan en el compartimento de las A, en vez de revolver un cajón sin clasificar.' },
      { id: 'fc2-1-8', front: 'Relación del hash con la unidad', back: 'La caja se obtiene como resto de dividir el hash por la cantidad de cajas: es una congruencia módulo $n$.' },
    ],
  },
  '2': {
    quiz2: {
      tf: [
        { id: 'tf2-2-1', q: 'Una ecuación diofántica exige que los coeficientes $a$, $b$ y $c$ sean enteros.', a: true, explain: 'La definición 2.1 pide $a, b, c \\in \\mathbb{Z}$, además de buscar soluciones enteras.' },
        { id: 'tf2-2-2', q: 'La condición del teorema 2.1 es suficiente pero no necesaria.', a: false, explain: 'El enunciado es un "si y solo si": es necesaria y suficiente a la vez.' },
        { id: 'tf2-2-3', q: 'El máximo común divisor es el último cociente que devuelve el algoritmo de Euclides.', a: false, explain: 'Es el último <strong>resto</strong> no nulo: en el ejemplo con 110 y 97 ese resto es 1, y ese es el mcd.' },
        { id: 'tf2-2-4', q: 'La expresión $(a : b) \\mid c$ se lee "c divide al máximo común divisor entre a y b".', a: false, explain: 'Se lee al revés: el mcd entre $a$ y $b$ divide a $c$.' },
        { id: 'tf2-2-5', q: 'En $110x - 97y = 1042$ se verifica la condición de existencia antes de buscar la solución.', a: true, explain: 'Primero se calcula $(110 : 97) = 1$ con Euclides y recién ahí se afirma que admite al menos una solución.' },
      ],
      mc: [
        {
          id: 'mc2-2-1',
          q: 'La forma general de una ecuación diofántica según el apunte es:',
          options: [
            '$ax^2 + by = c$ con $a, b, c \\in \\mathbb{Z}$',
            '$ax + by = c$ con $a, b, c \\in \\mathbb{Z}$',
            '$ax + by = c$ con $a, b, c \\in \\mathbb{R}$',
            '$ax + by = 0$ con $a, b \\in \\mathbb{Z}$',
          ],
          correctIndex: 1,
          explain: 'Es la ecuación 2.1: primer grado, dos incógnitas y coeficientes enteros.',
        },
        {
          id: 'mc2-2-2',
          q: 'La ecuación $6x + 4y = 7$ no admite solución diofántica porque:',
          options: [
            '$(6 : 4) = 2$ y 2 no divide a 7',
            '$(6 : 4) = 1$ y 1 no divide a 7',
            '7 es un número primo mayor que 6',
            '6 y 4 no son coprimos entre sí',
          ],
          correctIndex: 0,
          explain: 'Aplicando el teorema 2.1: el mcd es 2, y 2 no divide a 7, así que no hay solución entera.',
        },
        {
          id: 'mc2-2-3',
          q: 'En el algoritmo de Euclides aplicado a 110 y 97, el paso que sigue a $110 = 1 \\cdot 97 + 13$ es:',
          options: [
            '$13 = 2 \\cdot 6 + 1$',
            '$110 = 8 \\cdot 13 + 6$',
            '$97 = 7 \\cdot 13 + 6$',
            '$97 = 1 \\cdot 13 + 84$',
          ],
          correctIndex: 2,
          explain: 'Se divide el divisor anterior (97) por el resto obtenido (13), y da cociente 7 con resto 6.',
        },
        {
          id: 'mc2-2-4',
          q: 'Verificada la condición del teorema 2.1, lo que queda garantizado es:',
          options: [
            'Que la ecuación tiene una única solución entera',
            'Que la solución se obtiene despejando directamente',
            'Que existe al menos una solución diofántica entera',
            'Que los coeficientes son coprimos entre sí',
          ],
          correctIndex: 2,
          explain: 'El teorema garantiza existencia, no unicidad ni un método de cálculo.',
        },
        {
          id: 'mc2-2-5',
          q: 'Las soluciones diofánticas de $ax + by = c$ son:',
          options: [
            'Valores $x_0, y_0 \\in \\mathbb{Z}$ que verifican la ecuación',
            'Valores $x_0, y_0 \\in \\mathbb{R}$ que verifican la ecuación',
            'Valores $x_0, y_0 \\in \\mathbb{N}$ que verifican la ecuación',
            'Valores $x_0, y_0$ que anulan el término independiente',
          ],
          correctIndex: 0,
          explain: 'Se pide que sean enteros, no solo naturales ni reales cualesquiera.',
        },
      ],
      ms: [
        {
          id: 'ms2-2-1',
          q: '¿Cuáles de estas ecuaciones admiten solución diofántica según el teorema 2.1?',
          options: [
            '$5x + 3y = 8$',
            '$4x + 6y = 9$',
            '$110x - 97y = 1042$',
            '$27x + 83y = 17$',
            '$9x + 6y = 4$',
          ],
          correctIndexes: [0, 2, 3],
          explain: 'En la segunda el mcd es 2 y no divide a 9; en la última el mcd es 3 y no divide a 4.',
        },
        {
          id: 'ms2-2-2',
          q: '¿Qué se usa en la verificación de existencia del ejemplo $110x - 97y = 1042$?',
          options: [
            'El algoritmo de Euclides',
            'El máximo común divisor entre 110 y 97',
            'La condición $(110 : 97) \\mid 1042$',
            'La fórmula de la solución general',
            'La reducción de coeficientes módulo 97',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'La solución general y la reducción modular aparecen en secciones posteriores, no en la verificación.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-2-1', front: 'Ecuación 2.1', back: '$ax + by = c$ con $a, b, c \\in \\mathbb{Z}$: la forma general de una ecuación diofántica.' },
      { id: 'fc2-2-2', front: '¿Qué se busca en una diofántica?', back: 'Soluciones diofánticas: pares $(x_0, y_0)$ de números enteros que verifican la ecuación.' },
      { id: 'fc2-2-3', front: 'Condición de existencia', back: 'Existe solución si y solo si el máximo común divisor entre $a$ y $b$ divide al término independiente: $(a : b) \\mid c$.' },
      { id: 'fc2-2-4', front: 'Lectura de $(a : b) \\mid c$', back: '"El mcd entre $a$ y $b$ divide a $c$". La barra $\\mid$ significa "divide a".' },
      { id: 'fc2-2-5', front: 'Algoritmo de Euclides — qué devuelve', back: 'El máximo común divisor: se divide sucesivamente quedándose con los restos, y el último resto no nulo es el mcd.' },
      { id: 'fc2-2-6', front: 'Caso $110x - 97y = 1042$', back: '$(110 : 97) = 1$ y $1 \\mid 1042$: la ecuación admite al menos una solución diofántica.' },
      { id: 'fc2-2-7', front: '¿Qué NO garantiza el teorema 2.1?', back: 'No dice cuál es la solución ni cuántas hay: solo asegura que existe al menos una.' },
    ],
  },
  '3': {
    quiz2: {
      tf: [
        { id: 'tf2-3-1', q: 'En el método de los tanteos se prueban valores enteros hasta obtener un resultado entero.', a: true, explain: 'Se despeja una incógnita y se le dan valores a la otra hasta que el cociente dé entero.' },
        { id: 'tf2-3-2', q: 'El método de divisiones sucesivas parte de despejar la incógnita de coeficiente mayor.', a: false, explain: 'Se despeja la de coeficiente de <strong>menor</strong> valor absoluto.' },
        { id: 'tf2-3-3', q: 'La ecuación auxiliar que se obtiene tiene coeficientes menores que la original.', a: true, explain: 'Esa es la razón del método: $r_1 y + a z = c$ es más chica y el proceso se puede repetir.' },
        { id: 'tf2-3-4', q: 'La solución del Ejemplo 2 ($5x - 8y = 2$) es $(x_0, y_0) = (2, 1)$.', a: true, explain: 'Con $y = 1$ resulta $x = 10/5 = 2$, el primer valor entero de la tabla de tanteos.' },
        { id: 'tf2-3-5', q: 'En el Ejemplo 4 alcanza con una sola reducción para llegar a la solución.', a: false, explain: 'Hacen falta dos: primero $13x - 97z = 72$ y después $13w - 6z = 7$.' },
      ],
      mc: [
        {
          id: 'mc2-3-1',
          q: 'En el Ejemplo 1 ($5x + 3y = 8$), tanteando con $x = 2$ se obtiene:',
          options: ['$y = 1$', '$y = -2/3$', '$y = 8/3$', '$y = 2$'],
          correctIndex: 1,
          explain: 'Reemplazando en $y = \\dfrac{8 - 5x}{3}$ queda $-2/3$, que no es entero; el valor útil es $x = 1$.',
        },
        {
          id: 'mc2-3-2',
          q: 'Tras dividir $b$ por $a$ y reemplazar, la incógnita despejada se escribe como:',
          options: [
            '$x = q_1 y + \\dfrac{c + r_1 y}{a}$',
            '$x = -q_1 y + \\dfrac{c - r_1 y}{a}$',
            '$x = -r_1 y + \\dfrac{c - q_1 y}{a}$',
            '$x = q_1 y - \\dfrac{c - r_1 y}{b}$',
          ],
          correctIndex: 1,
          explain: 'De ahí sale la definición $z = \\dfrac{c - r_1 y}{a}$ y la ecuación auxiliar $r_1 y + a z = c$.',
        },
        {
          id: 'mc2-3-3',
          q: 'En el Ejemplo 3 la ecuación auxiliar que se plantea es:',
          options: [
            '$2z + 27y = 17$',
            '$27z + 2y = 17$',
            '$83z + 27y = 17$',
            '$27z + 3y = 17$',
          ],
          correctIndex: 1,
          explain: 'Se define $z = \\dfrac{17 - 2y}{27}$, de donde $27z + 2y = 17$.',
        },
        {
          id: 'mc2-3-4',
          q: 'En el Ejemplo 3, al pasar de $(z_0, y_0) = (1, -5)$ a la ecuación original se obtiene:',
          options: [
            '$(x_0, y_0) = (1, -5)$',
            '$(x_0, y_0) = (5, -16)$',
            '$(x_0, y_0) = (16, -5)$',
            '$(x_0, y_0) = (-5, 16)$',
          ],
          correctIndex: 2,
          explain: 'Se deshace el reemplazo con $x = -3y + z = 15 + 1 = 16$, manteniendo $y = -5$.',
        },
        {
          id: 'mc2-3-5',
          q: 'En el Ejemplo 4, la segunda ecuación auxiliar que aparece es:',
          options: [
            '$13w - 6z = 7$',
            '$6w - 13z = 7$',
            '$13w - 97z = 72$',
            '$97w - 13z = 6$',
          ],
          correctIndex: 0,
          explain: 'Se define $w = \\dfrac{6z + 7}{13}$, de donde $13w - 6z = 7$, y con $w = 1$ resulta $z = 1$.',
        },
      ],
      ms: [
        {
          id: 'ms2-3-1',
          q: '¿Qué condiciones se asumen al desarrollar el método general de divisiones sucesivas?',
          options: [
            'Que $a$ y $b$ son positivos',
            'Que $a$ es menor que $b$',
            'Que $b = a \\cdot q_1 + r_1$ con $r_1 < a$',
            'Que $c$ es divisible por $a$',
            'Que $a$ y $b$ son coprimos',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'Ni la divisibilidad de $c$ ni la coprimalidad se piden: el método funciona igual mientras exista solución.',
        },
        {
          id: 'ms2-3-2',
          q: '¿Qué pares son soluciones diofánticas halladas en los ejemplos del apunte?',
          options: [
            '$(1, 1)$ para $5x + 3y = 8$',
            '$(2, 1)$ para $5x - 8y = 2$',
            '$(16, -5)$ para $27x + 83y = 17$',
            '$(13, 4)$ para $110x - 97y = 1042$',
            '$(3, 2)$ para $27x + 83y = 17$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'El último par no verifica la ecuación: $27 \\cdot 3 + 83 \\cdot 2 = 247$, no 17.',
        },
        {
          id: 'ms2-3-3',
          q: '¿Qué divisiones se usan en el desarrollo del Ejemplo 4?',
          options: [
            '$110 = 97 + 13$',
            '$1042 = 97 \\cdot 10 + 72$',
            '$97 = 13 \\cdot 7 + 6$',
            '$72 = 13 \\cdot 5 + 7$',
            '$83 = 27 \\cdot 3 + 2$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La división de 83 por 27 pertenece al Ejemplo 3, no al 4.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-3-1', front: 'Tanteos — procedimiento', back: 'Despejar una incógnita y darle a la otra valores enteros sucesivos hasta que el resultado sea entero.' },
      { id: 'fc2-3-2', front: '¿Hasta qué valor conviene tantear?', back: 'Hasta el valor del denominador: por ejemplo, en $x = \\dfrac{2 + 8y}{5}$ alcanza con probar $y$ menor que 5.' },
      { id: 'fc2-3-3', front: 'Divisiones sucesivas — primer paso', back: 'Despejar la incógnita de coeficiente de menor valor absoluto y dividir el otro coeficiente por él.' },
      { id: 'fc2-3-4', front: 'Ecuación auxiliar del método general', back: '$r_1 y + a z = c$, con $z = \\dfrac{c - r_1 y}{a}$; tiene coeficientes menores que la original.' },
      { id: 'fc2-3-5', front: 'Ejemplo 3 en dos pasos', back: '$27x + 83y = 17$ se reduce a $27z + 2y = 17$; sale $(z_0, y_0) = (1, -5)$ y de vuelta $(x_0, y_0) = (16, -5)$.' },
      { id: 'fc2-3-6', front: 'Ejemplo 4 en tres pasos', back: '$110x - 97y = 1042 \\to 13x - 97z = 72 \\to 13w - 6z = 7$; con $(w_0, z_0) = (1, 1)$ se llega a $(x_0, y_0) = (13, 4)$.' },
      { id: 'fc2-3-7', front: '¿Cómo se vuelve a las incógnitas originales?', back: 'Deshaciendo los reemplazos en orden inverso, sustituyendo cada variable auxiliar por su expresión.' },
      { id: 'fc2-3-8', front: 'Verificación de una solución', back: 'Se reemplaza en la ecuación original: $110 \\cdot 13 - 97 \\cdot 4 = 1042$ confirma el resultado del Ejemplo 4.' },
    ],
  },
  '4': {
    quiz2: {
      tf: [
        { id: 'tf2-4-1', q: 'La cantidad de soluciones diofánticas de una ecuación resoluble es infinita.', a: true, explain: 'Hay una solución por cada valor entero del parámetro $t$.' },
        { id: 'tf2-4-2', q: 'En la solución general, el término que acompaña a $x$ es $a t$.', a: false, explain: 'Los coeficientes se cruzan: $x = x_0 - b t$ e $y = y_0 + a t$.' },
        { id: 'tf2-4-3', q: 'La deducción parte de que ya se conoce una solución particular $(x_0, y_0)$.', a: true, explain: 'Se reemplaza $c = a x_0 + b y_0$ para llegar a $a(x - x_0) + b(y - y_0) = 0$.' },
        { id: 'tf2-4-4', q: 'La recta $ax + by = c$ pasa por infinitos puntos de coordenadas enteras cuando la ecuación es resoluble.', a: true, explain: 'Cada $t \\in \\mathbb{Z}$ da un punto entero distinto sobre esa recta.' },
        { id: 'tf2-4-5', q: 'El parámetro $t$ de la solución general recorre los números naturales.', a: false, explain: 'Recorre $\\mathbb{Z}$, así que también toma valores negativos.' },
      ],
      mc: [
        {
          id: 'mc2-4-1',
          q: 'La igualdad que se obtiene antes de introducir el parámetro es:',
          options: [
            '$\\dfrac{x - x_0}{y - y_0} = \\dfrac{-b}{a}$',
            '$\\dfrac{x - x_0}{y - y_0} = \\dfrac{-a}{b}$',
            '$\\dfrac{y - y_0}{x - x_0} = \\dfrac{-b}{a}$',
            '$\\dfrac{x + x_0}{y + y_0} = \\dfrac{-b}{a}$',
          ],
          correctIndex: 0,
          explain: 'Sale de despejar el cociente en $a(x - x_0) + b(y - y_0) = 0$.',
        },
        {
          id: 'mc2-4-2',
          q: 'La solución general de $ax + by = c$ se escribe como:',
          options: [
            '$x = x_0 + bt$, $y = y_0 - at$',
            '$x = x_0 - at$, $y = y_0 + bt$',
            '$x = x_0 - bt$, $y = y_0 + at$',
            '$x = x_0 + at$, $y = y_0 - bt$',
          ],
          correctIndex: 2,
          explain: 'Sale de $x - x_0 = -bt$ e $y - y_0 = at$, con $t$ entero.',
        },
        {
          id: 'mc2-4-3',
          q: 'El argumento que justifica introducir el parámetro $t$ es que:',
          options: [
            'Toda recta del plano corta siempre al eje de abscisas',
            'Dos fracciones son iguales si sus términos son múltiplos',
            'Todo número entero es cociente de otros dos enteros',
            'El máximo común divisor divide al término independiente',
          ],
          correctIndex: 1,
          explain: 'Es la frase textual del apunte: por eso se escribe cada numerador como un múltiplo común.',
        },
        {
          id: 'mc2-4-4',
          q: 'La lectura geométrica de una ecuación diofántica es:',
          options: [
            'Buscar el punto donde la recta corta al eje vertical',
            'Buscar la pendiente que tiene la recta en el plano',
            'Buscar la distancia entre la recta y el origen',
            'Buscar el cruce de la recta con el espacio de los enteros',
          ],
          correctIndex: 3,
          explain: 'La recta vive en $\\mathbb{R}^2$; las soluciones son los puntos donde cae sobre coordenadas enteras.',
        },
        {
          id: 'mc2-4-5',
          q: 'En la figura del apunte, el punto $A$ señalado sobre la recta representa:',
          options: [
            'El origen del sistema de coordenadas',
            'El punto de corte con el eje vertical',
            'El valor del máximo común divisor',
            'Una solución entera de la ecuación',
          ],
          correctIndex: 3,
          explain: 'La leyenda de la figura dice "Solución de la ecuación" y apunta a ese nodo de la grilla.',
        },
      ],
      ms: [
        {
          id: 'ms2-4-1',
          q: '¿Qué pasos integran la deducción de la solución general?',
          options: [
            'Reemplazar $c$ por $a x_0 + b y_0$',
            'Agrupar los términos en $a(x - x_0) + b(y - y_0) = 0$',
            'Igualar el cociente de diferencias a $\\dfrac{-b}{a}$',
            'Parametrizar con $t \\in \\mathbb{Z}$',
            'Reducir los coeficientes módulo $c$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La reducción modular corresponde a las ecuaciones de congruencia, no a esta deducción.',
        },
        {
          id: 'ms2-4-2',
          q: 'Si $(1, 1)$ resuelve $5x + 3y = 8$, ¿qué pares también son soluciones según la fórmula general?',
          options: [
            '$(-2, 6)$',
            '$(4, -4)$',
            '$(1, 1)$',
            '$(7, -9)$',
            '$(2, 2)$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'Con $x = 1 - 3t$ e $y = 1 + 5t$: $t = 1$ da $(-2, 6)$, $t = -1$ da $(4, -4)$ y $t = -2$ da $(7, -9)$. El par $(2, 2)$ da 16, no 8.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-4-1', front: 'Fórmula de la solución general', back: '$x = x_0 - bt$ e $y = y_0 + at$, con $t \\in \\mathbb{Z}$.' },
      { id: 'fc2-4-2', front: '¿Qué se necesita para aplicarla?', back: 'Conocer una solución particular $(x_0, y_0)$ de la ecuación.' },
      { id: 'fc2-4-3', front: 'Primer paso de la deducción', back: 'Sustituir $c$ por $a x_0 + b y_0$ y agrupar: $a(x - x_0) + b(y - y_0) = 0$.' },
      { id: 'fc2-4-4', front: 'Justificación del parámetro', back: 'Dos fracciones son iguales cuando sus términos son múltiplos, de ahí $x - x_0 = -bt$ e $y - y_0 = at$.' },
      { id: 'fc2-4-5', front: 'Cantidad de soluciones', back: 'Infinitas, una por cada entero $t$, siempre que exista al menos una.' },
      { id: 'fc2-4-6', front: 'Lectura geométrica', back: 'La ecuación es una recta en $\\mathbb{R}^2$ y las soluciones diofánticas son sus puntos de coordenadas enteras.' },
      { id: 'fc2-4-7', front: 'Figura de la sección', back: 'Una recta sobre una grilla con el punto $A$ marcado y rotulado como solución de la ecuación.' },
    ],
  },
  '5': {
    quiz2: {
      tf: [
        { id: 'tf2-5-1', q: 'Los restos de dividir los enteros por $m$ se repiten con período $m$.', a: true, explain: 'Forman el ciclo $0; 1; \\dots; (m-1)$ que vuelve a empezar cada $m$ pasos.' },
        { id: 'tf2-5-2', q: 'La congruencia $a \\equiv b\\ (m)$ equivale a que $m$ divida a la suma $a + b$.', a: false, explain: 'Equivale a que $m$ divida a la <strong>diferencia</strong> $(b - a)$.' },
        { id: 'tf2-5-3', q: 'De $a \\equiv b\\ (n)$ se deduce que $a + r \\equiv b\\ (n)$ para todo entero $r$.', a: false, explain: 'La propiedad exige sumar $r$ en los dos miembros: lo que vale es $a + r \\equiv b + r\\ (n)$.' },
        { id: 'tf2-5-4', q: 'La Proposición 1 habilita a dividir miembro a miembro dos congruencias del mismo módulo.', a: false, explain: 'Las operaciones listadas son suma, resta, producto, potencia y producto o suma por un entero; la división no figura.' },
        { id: 'tf2-5-5', q: 'Para hallar el resto de una potencia grande se busca un exponente que dé congruencia con 1.', a: true, explain: 'Encontrado ese $n$, la potencia se descompone y solo sobrevive el sobrante del exponente.' },
      ],
      mc: [
        {
          id: 'mc2-5-1',
          q: 'La definición de congruencia módulo $m$ del apunte establece que:',
          options: [
            '$a \\equiv b\\ (m)$ si $(b - a) \\mid m$',
            '$a \\equiv b\\ (m)$ si $m \\mid (b - a)$',
            '$a \\equiv b\\ (m)$ si $m \\mid (b \\cdot a)$',
            '$a \\equiv b\\ (m)$ si $b \\mid (m - a)$',
          ],
          correctIndex: 1,
          explain: 'Es la Definición 2, con $m \\in \\mathbb{N}$ y $a, b \\in \\mathbb{Z}$.',
        },
        {
          id: 'mc2-5-2',
          q: 'La tercera formulación equivalente de la congruencia dice que:',
          options: [
            '$a = b \\cdot km$ para algún $k$ entero',
            '$a = b - km^2$ para algún $k$ entero',
            '$a = b + km$ para algún $k$ entero',
            '$a = km$ para algún $k$ entero',
          ],
          correctIndex: 2,
          explain: 'Uno es el otro más un múltiplo del módulo, lo que es otra forma de decir que tienen el mismo resto.',
        },
        {
          id: 'mc2-5-3',
          q: 'En el cálculo del resto de $11^{1243}$ por 7, el exponente hallado es:',
          options: ['$n = 2$', '$n = 3$', '$n = 4$', '$n = 7$'],
          correctIndex: 1,
          explain: 'Se prueba $n = 1$, $n = 2$ y $n = 3$, y recién ahí resulta $11^3 \\equiv 1\\ (7)$.',
        },
        {
          id: 'mc2-5-4',
          q: 'La división que se hace con el exponente 1243 en ese ejemplo es:',
          options: [
            '$1243 = 177 \\cdot 7 + 4$',
            '$1243 = 621 \\cdot 2 + 1$',
            '$1243 = 113 \\cdot 11 + 0$',
            '$1243 = 414 \\cdot 3 + 1$',
          ],
          correctIndex: 3,
          explain: 'Se divide el exponente por el $n$ hallado, que es 3, y sobra 1.',
        },
        {
          id: 'mc2-5-5',
          q: 'En el Ejemplo 2.2, la congruencia de partida para trabajar con $7^{135}$ es:',
          options: [
            '$7^2 \\equiv 1\\ (8)$',
            '$7^3 \\equiv 1\\ (8)$',
            '$7^2 \\equiv 7\\ (8)$',
            '$7^4 \\equiv 1\\ (8)$',
          ],
          correctIndex: 0,
          explain: 'Con $7^2 \\equiv 1\\ (8)$ y $135 = 2 \\cdot 67 + 1$, el residuo termina siendo 7.',
        },
      ],
      ms: [
        {
          id: 'ms2-5-1',
          q: '¿Qué operaciones entre congruencias del mismo módulo autoriza la Proposición 1?',
          options: [
            'Sumarlas miembro a miembro',
            'Restarlas miembro a miembro',
            'Multiplicarlas miembro a miembro',
            'Elevar ambos miembros a una potencia natural',
            'Dividirlas miembro a miembro',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La división no está entre las propiedades enunciadas.',
        },
        {
          id: 'ms2-5-2',
          q: '¿Qué congruencias intermedias aparecen al calcular el resto de $11^{1243}$ por 7?',
          options: [
            '$(11)^1 \\equiv 4\\ (7)$',
            '$(11)^2 \\equiv 2\\ (7)$',
            '$(11)^3 \\equiv 1\\ (7)$',
            '$(11)^4 \\equiv 4\\ (7)$',
            '$(11)^2 \\equiv 4\\ (7)$',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'El apunte solo calcula hasta $n = 3$; la cuarta potencia no se desarrolla y la última contradice el cálculo de $16 \\equiv 2$.',
        },
        {
          id: 'ms2-5-3',
          q: '¿Cuáles de estas afirmaciones son verdaderas para $m = 5$?',
          options: [
            '$12 \\equiv 2\\ (5)$',
            '$7 \\equiv 2\\ (5)$',
            '$9 \\equiv 4\\ (5)$',
            '$13 \\equiv 2\\ (5)$',
            '$11 \\equiv 2\\ (5)$',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'Dividiendo por 5: $12$ y $7$ dejan resto 2, y $9$ deja resto 4. En cambio $13$ deja resto 3 y $11$ deja resto 1, así que esas dos congruencias son falsas.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-5-1', front: 'Definición de congruencia', back: 'Con $m \\in \\mathbb{N}$ y $a, b \\in \\mathbb{Z}$: $a \\equiv b\\ (m) \\iff m \\mid (b - a)$.' },
      { id: 'fc2-5-2', front: 'Ciclo de restos módulo $m$', back: 'La secuencia $0; 1; 2; \\dots; (m-1)$ se repite indefinidamente, con período exactamente $m$.' },
      { id: 'fc2-5-3', front: 'Formulación con múltiplo', back: '$a = b + km$ para algún $k \\in \\mathbb{Z}$: equivale a decir que $a$ y $b$ son congruentes módulo $m$.' },
      { id: 'fc2-5-4', front: 'Formulación con restos', back: '$r_m(a) = r_m(b)$: ambos dejan el mismo resto al dividirlos por $m$.' },
      { id: 'fc2-5-5', front: 'Fórmula 2.2', back: '$\\forall\\, r, s \\in \\mathbb{Z}$: $ar + cs \\equiv br + ds\\ (n)$, que condensa las seis propiedades de la Proposición 1.' },
      { id: 'fc2-5-6', front: 'Estrategia para restos de potencias', back: 'Hallar el menor $n$ con $a^n \\equiv 1\\ (m)$, dividir el exponente por $n$ y quedarse con el resto de $a$ elevado al sobrante.' },
      { id: 'fc2-5-7', front: '$11^{1243}$ módulo 7', back: 'Con $11^3 \\equiv 1\\ (7)$ y $1243 = 414 \\cdot 3 + 1$, el resto es 4.' },
      { id: 'fc2-5-8', front: '$7^{135}$ módulo 8', back: 'Con $7^2 \\equiv 1\\ (8)$ y $135 = 2 \\cdot 67 + 1$, el residuo es 7.' },
    ],
  },
  '6': {
    quiz2: {
      tf: [
        { id: 'tf2-6-1', q: 'Una ecuación lineal de congruencia se puede reescribir como una ecuación diofántica.', a: true, explain: 'Es la Observación 1: $aX \\equiv b\\ (m)$ equivale a $aX - mt = b$ con $t$ entero.' },
        { id: 'tf2-6-2', q: 'La resolubilidad de $aX \\equiv b\\ (m)$ depende de que $b$ divida a $(a : m)$.', a: false, explain: 'Es al revés: hace falta que $(a : m)$ divida a $b$.' },
        { id: 'tf2-6-3', q: 'En una ecuación de congruencia solo se puede reducir módulo $m$ el término independiente.', a: false, explain: 'Se reducen todos los coeficientes: por eso $152X \\equiv -88\\ (36)$ pasa a $8X \\equiv 20\\ (36)$.' },
        { id: 'tf2-6-4', q: 'La Proposición 3 mantiene el módulo original al simplificar por un divisor común.', a: false, explain: 'El módulo también se divide por $d$: queda $\\dfrac{m}{d}$.' },
        { id: 'tf2-6-5', q: 'Si $a$ y $m$ son coprimos, la ecuación tiene solución para cualquier valor de $b$.', a: true, explain: 'Con $(a : m) = 1$, ese 1 divide a todo $b$, así que la condición se cumple siempre.' },
      ],
      mc: [
        {
          id: 'mc2-6-1',
          q: 'La cantidad de soluciones en $\\mathbb{Z}_{36}$ de $8X \\equiv 20\\ (36)$ es:',
          options: ['9 soluciones', '2 soluciones', '4 soluciones', '20 soluciones'],
          correctIndex: 2,
          explain: 'Coincide con $d = (8 : 36) = 4$, el máximo común divisor entre el coeficiente y el módulo.',
        },
        {
          id: 'mc2-6-2',
          q: 'La combinación lineal que da Euclides en el Ejemplo 2.3 es:',
          options: [
            '$4 = 8 \\cdot 4 - 36 \\cdot 1$',
            '$4 = 8(-5) + 36 \\cdot 1$',
            '$4 = 8(-4) + 36 \\cdot 1$',
            '$4 = 8 \\cdot 1 - 36(-4)$',
          ],
          correctIndex: 2,
          explain: 'Multiplicada por 5 da $20 = 8(-20) + 36 \\cdot 5$, de donde $-20$ es solución.',
        },
        {
          id: 'mc2-6-3',
          q: 'Las soluciones del Ejemplo 2.3 se generan a partir de $-20$ sumando:',
          options: ['4 cada vez', '36 cada vez', '20 cada vez', '9 cada vez'],
          correctIndex: 3,
          explain: 'Se suma $m/d = 36/4 = 9$, obteniendo $-20, -11, -2$ y $7$.',
        },
        {
          id: 'mc2-6-4',
          q: 'Un entero $X$ verifica $152X \\equiv -88\\ (36)$ exactamente cuando su resto módulo 36 es:',
          options: [
            '$7, 16, 25$ o $34$',
            '$4, 13, 22$ o $31$',
            '$0, 9, 18$ o $27$',
            '$8, 17, 26$ o $35$',
          ],
          correctIndex: 0,
          explain: 'Son los representantes canónicos de las cuatro clases solución.',
        },
        {
          id: 'mc2-6-5',
          q: 'La demostración de la Proposición 2 se apoya en:',
          options: [
            'La fórmula de la solución general de una diofántica',
            'El ciclo de restos de período $m$ en los enteros',
            'La equivalencia con la diofántica $ax + my = b$',
            'La reducción de los coeficientes módulo $m$',
          ],
          correctIndex: 2,
          explain: 'Al ser equivalentes, se aplica la condición de existencia ya probada para diofánticas.',
        },
      ],
      ms: [
        {
          id: 'ms2-6-1',
          q: '¿Qué hipótesis pide la Proposición 3 sobre el entero $d$?',
          options: [
            'Que $d$ sea mayor que cero',
            'Que $d$ divida a $a$',
            'Que $d$ divida a $b$',
            'Que $d$ divida a $m$',
            'Que $d$ sea coprimo con $m$',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'Si $d$ divide a $m$ no puede ser coprimo con él (salvo $d = 1$), así que la última opción contradice a las otras.',
        },
        {
          id: 'ms2-6-2',
          q: '¿Cuáles de estas ecuaciones de congruencia son resolubles?',
          options: [
            '$8X \\equiv 20\\ (36)$',
            '$6X \\equiv 4\\ (9)$',
            '$5X \\equiv 3\\ (7)$',
            '$4X \\equiv 6\\ (8)$',
            '$3X \\equiv 5\\ (6)$',
          ],
          correctIndexes: [0, 2],
          explain: 'En la segunda $(6 : 9) = 3$ y $3 \\nmid 4$; en la cuarta $(4 : 8) = 4$ y $4 \\nmid 6$; en la quinta $(3 : 6) = 3$ y $3 \\nmid 5$.',
        },
        {
          id: 'ms2-6-3',
          q: '¿Qué afirma el apunte sobre el conjunto de soluciones de una ecuación modular?',
          options: [
            'Todo entero congruente con una solución también es solución',
            'La cantidad de clases solución coincide con $(a : m)$',
            'Las soluciones se pueden escribir con representantes canónicos',
            'Una solución particular se obtiene con el algoritmo de Euclides',
            'El conjunto de soluciones siempre tiene un único elemento',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'Nunca hay un único elemento: si existe una solución, cada clase módulo $m$ aporta infinitos enteros.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-6-1', front: 'Ecuación 2.5', back: '$aX \\equiv b\\ (m)$, con $a, b \\in \\mathbb{Z}$ y $m \\in \\mathbb{N}$: la ecuación lineal de congruencia.' },
      { id: 'fc2-6-2', front: 'Puente con las diofánticas', back: 'Si $X$ es solución, existe $t \\in \\mathbb{Z}$ con $aX = b + mt$, o sea $aX - mt = b$.' },
      { id: 'fc2-6-3', front: 'Criterio de resolubilidad', back: 'La ecuación $aX \\equiv b\\ (m)$ tiene solución si y solo si $(a : m) \\mid b$.' },
      { id: 'fc2-6-4', front: '¿Cuántas soluciones hay en $\\mathbb{Z}_m$?', back: 'Tantas como el valor de $d = (a : m)$; en el ejemplo con módulo 36 y $d = 4$, son cuatro.' },
      { id: 'fc2-6-5', front: 'Reducción de coeficientes', back: 'Se pueden reemplazar $a$ y $b$ por sus restos módulo $m$: $152X \\equiv -88\\ (36)$ pasa a $8X \\equiv 20\\ (36)$.' },
      { id: 'fc2-6-6', front: 'Cómo se halla una solución particular', back: 'Con Euclides se escribe $(a : m)$ como combinación lineal y se ajusta el factor: $4 = 8(-4) + 36 \\cdot 1$, por 5 da $-20$.' },
      { id: 'fc2-6-7', front: 'Paso entre soluciones', back: 'Se suma $m/d$: en el ejemplo, $9$, generando $-20, -11, -2, 7$.' },
      { id: 'fc2-6-8', front: 'Proposición 3', back: 'Si $d > 0$ divide a $a$, $b$ y $m$, entonces $aX \\equiv b\\ (m)$ es resoluble si y solo si lo es $\\dfrac{a}{d}X \\equiv \\dfrac{b}{d}\\ \\left(\\dfrac{m}{d}\\right)$.' },
    ],
  },
  '7': {
    quiz2: {
      tf: [
        { id: 'tf2-7-1', q: 'El apunte presenta los sistemas lineales como un problema reciente de la matemática.', a: false, explain: 'Los describe como uno de los <strong>más antiguos</strong> de la matemática.' },
        { id: 'tf2-7-2', q: 'La información sísmica de la exploración petrolera se recoge con geófonos.', a: true, explain: 'Están conectados a extensos cables instalados debajo del barco.' },
        { id: 'tf2-7-3', q: 'Los modelos de programación lineal de las aerolíneas manejan cientos de variables.', a: true, explain: 'Y sobre ellos se toman decisiones administrativas importantes.' },
        { id: 'tf2-7-4', q: 'Los microchips que menciona el apunte incluyen miles de transistores.', a: false, explain: 'Habla de circuitos y microchips con <strong>millones</strong> de transistores.' },
        { id: 'tf2-7-5', q: 'Entre las aplicaciones listadas figura la aproximación de problemas no lineales de análisis numérico.', a: true, explain: 'Aparece en la enumeración inicial, junto con señales, análisis estructural, estimación y predicción.' },
      ],
      mc: [
        {
          id: 'mc2-7-1',
          q: 'Las ondas usadas en la exploración petrolera se generan mediante:',
          options: [
            'Explosiones con pistolas de aire',
            'Pulsos emitidos por boyas de superficie',
            'Vibraciones del casco del barco',
            'Descargas eléctricas submarinas',
          ],
          correctIndex: 0,
          explain: 'Las ondas de choque submarinas se crean con pistolas de aire y rebotan en las rocas del fondo.',
        },
        {
          id: 'mc2-7-2',
          q: 'La cantidad de sistemas que resuelven a diario las computadoras del barco es del orden de:',
          options: ['Decenas', 'Centenas', 'Millares', 'Unidades'],
          correctIndex: 2,
          explain: 'El apunte dice que resuelven miles de sistemas de ecuaciones lineales por separado.',
        },
        {
          id: 'mc2-7-3',
          q: 'Entre los usos aeronáuticos que enumera el apunte NO figura:',
          options: [
            'Crear itinerarios de tripulaciones de vuelo',
            'Planear servicios de mantenimiento y terminal',
            'Monitorear las ubicaciones de los aviones',
            'Calcular la carga de combustible por vuelo',
          ],
          correctIndex: 3,
          explain: 'Los tres primeros son textuales del apunte; el cálculo de combustible no aparece.',
        },
        {
          id: 'mc2-7-4',
          q: 'Las técnicas que emplean los programas de simulación de circuitos son de:',
          options: [
            'Estadística descriptiva y muestreo aleatorio',
            'Álgebra lineal y sistemas de ecuaciones',
            'Cálculo diferencial de varias variables',
            'Teoría de grafos y algoritmos de flujo',
          ],
          correctIndex: 1,
          explain: 'Es la frase con la que cierra la sección sobre redes eléctricas.',
        },
        {
          id: 'mc2-7-5',
          q: 'La sección de aplicaciones desarrolla en detalle:',
          options: [
            'Dos casos de la vida real',
            'Cinco casos de la vida real',
            'Cuatro casos de la vida real',
            'Tres casos de la vida real',
          ],
          correctIndex: 3,
          explain: 'Exploración petrolera, programación lineal y redes eléctricas.',
        },
      ],
      ms: [
        {
          id: 'ms2-7-1',
          q: '¿Qué campos de aplicación enumera la introducción de la sección?',
          options: [
            'Procesamiento digital de señales',
            'Análisis estructural',
            'Estimación y predicción',
            'Programación lineal',
            'Diseño de algoritmos de compresión',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La compresión de datos no está en la lista del apunte.',
        },
        {
          id: 'ms2-7-2',
          q: '¿Qué elementos intervienen en el caso de la exploración petrolera?',
          options: [
            'Ondas de choque submarinas',
            'Pistolas de aire',
            'Geófonos conectados a cables',
            'Rocas bajo la superficie marina',
            'Satélites de posicionamiento',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'Los satélites no se mencionan; todo el registro se hace con los geófonos remolcados por el barco.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-7-1', front: 'Antigüedad del problema', back: 'Los sistemas lineales de ecuaciones son uno de los problemas más antiguos de la matemática.' },
      { id: 'fc2-7-2', front: 'Campos de aplicación generales', back: 'Procesamiento digital de señales, análisis estructural, estimación, predicción, programación lineal y análisis numérico no lineal.' },
      { id: 'fc2-7-3', front: 'Método de la exploración petrolera', back: 'Explosiones con pistolas de aire generan ondas que rebotan en las rocas; los geófonos las miden y con esos datos se arman las ecuaciones.' },
      { id: 'fc2-7-4', front: 'Escala del cálculo en el barco', back: 'Miles de sistemas de ecuaciones lineales resueltos por separado cada día.' },
      { id: 'fc2-7-5', front: 'Usos aeronáuticos', back: 'Itinerarios de tripulaciones, monitoreo de ubicación de aviones y planificación de mantenimiento y operaciones en terminal.' },
      { id: 'fc2-7-6', front: 'Escala de los microchips', back: 'Circuitos y microchips con millones de transistores, simulados con técnicas de álgebra lineal.' },
      { id: 'fc2-7-7', front: 'Los tres casos desarrollados', back: 'Exploración petrolera, programación lineal y redes eléctricas.' },
    ],
  },
};
