/**
 * Banco NUEVO (anti-spoiler) — laboratorio-1
 *
 * Mapa { [sectionId]: { quiz2: { tf, mc, ms }, flashcards2: [...] } }.
 * content.js mergea esto sobre las secciones por id (sec.quiz2 / sec.flashcards2).
 * Generado para autoevaluación: opciones homogéneas, sin pistas de forma.
 *
 * Cubre las secciones 21-27 (unidades 'jvm', 'jdk' y 'actividades') y las
 * secciones 28-34 (unidad 'diseno-clases').
 */
export default {
  '21': {
    quiz2: {
      tf: [
        { id: 'tf2-21-1', q: 'El JRE alcanza para correr programas Java, pero no trae el compilador.', a: true, explain: 'El JRE sirve para ejecutar código Java. El compilador y el motor de documentación vienen con el JDK.' },
        { id: 'tf2-21-2', q: 'La máquina virtual se ubica entre el lenguaje y el sistema operativo.', a: true, explain: 'Es la definición textual de JVM del apunte.' },
        { id: 'tf2-21-3', q: 'En Java hay que volver a compilar el código en cada plataforma donde se lo quiera ejecutar.', a: false, explain: 'Eso pasa en C. En Java se compila una vez y el resultado corre en cualquier máquina virtual de cualquier plataforma.' },
        { id: 'tf2-21-4', q: 'Instalar el kit de desarrollo implica quedarse sin entorno de ejecución.', a: false, explain: 'El JDK involucra tanto la JVM como el JRE, así que instalarlo trae el entorno de ejecución incluido.' },
        { id: 'tf2-21-5', q: 'El apunte considera a .Net como otro caso de plataforma con máquina virtual.', a: true, explain: 'Lo menciona al pasar cuando compara el modelo de compilación: "como es en el caso de Java (o .Net para el caso)".' },
      ],
      mc: [
        {
          id: 'mc2-21-1',
          q: '¿Qué elemento es distinto en cada plataforma donde corre un programa Java?',
          options: [
            'El archivo compilado que produce el compilador',
            'La máquina virtual que se instala con el JRE',
            'El código fuente escrito por el programador',
            'El lenguaje de máquina que genera el compilador',
          ],
          correctIndex: 1,
          explain: 'Lo que se instala para diferentes plataformas es la máquina virtual. El compilado se hace una sola vez y no genera lenguaje de máquina.',
        },
        {
          id: 'mc2-21-2',
          q: '¿Qué herramientas de desarrollo menciona el apunte como contenido del kit?',
          options: [
            'El compilador y el motor para hacer documentación',
            'El recolector de basura y el manejador de errores',
            'El cargador de clases y el administrador de memoria',
            'El intérprete de sintaxis y el editor de texto',
          ],
          correctIndex: 0,
          explain: 'El JDK tiene muchas herramientas de desarrollo, "como ser el compilador, el motor para hacer documentación, etc.". Los demás son módulos internos del JRE.',
        },
        {
          id: 'mc2-21-3',
          q: 'En el modelo de C que usa el apunte como contraste, ¿a qué se compila el código fuente?',
          options: [
            'Al lenguaje de una máquina virtual instalada aparte',
            'A un formato binario portable entre plataformas',
            'A lenguaje de máquina del sistema operativo destino',
            'A instrucciones en lenguaje natural en inglés',
          ],
          correctIndex: 2,
          explain: 'En C, cuando se compila se hace en lenguaje de máquina: si tengo Linux, debo compilar en C para Linux.',
        },
      ],
      ms: [
        {
          id: 'ms2-21-1',
          q: '¿Qué afirmaciones sobre las tres siglas se corresponden con el apunte?',
          options: [
            'El JDK involucra tanto la JVM como el JRE',
            'El JRE sirve para ejecutar código Java',
            'La JVM corre entre el lenguaje y el sistema operativo',
            'Cuando se instala Java se instala el JRE y la JVM',
            'La JVM se distribuye por separado del JRE en cada sistema',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'El apunte dice que cuando se instala Java se instala el JRE (y la JVM): vienen juntos, no por separado.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-21-1', front: '¿Qué sigla nombra el entorno de desarrollo completo?', back: 'El JDK, Java Development Kit, que involucra tanto la JVM como el JRE y agrega herramientas como el compilador y el motor de documentación.' },
      { id: 'fc2-21-2', front: '¿Para qué sirve el JRE?', back: 'Para ejecutar código Java, para correr programas Java. Se instala para Linux, Windows o Mac.' },
      { id: 'fc2-21-3', front: '¿Dónde se ubica la máquina virtual?', back: 'Entre el lenguaje y el sistema operativo. Por eso el código Java no se compila a código de máquina.' },
      { id: 'fc2-21-4', front: '¿Por qué Java es portable?', back: 'Porque se compila para el lenguaje de la máquina virtual, no para lenguaje de máquina. Lo que cambia en cada plataforma es la VM, no el compilado.' },
      { id: 'fc2-21-5', front: '¿Qué pasa en C cuando cambia el sistema operativo?', back: 'Hay que compilar de nuevo: en C se compila en lenguaje de máquina, así que en Linux se compila para Linux, y lo mismo con Windows o Mac.' },
    ],
  },
  '22': {
    quiz2: {
      tf: [
        { id: 'tf2-22-1', q: 'El apunte clasifica a Java junto a C dentro de los lenguajes compilados.', a: false, explain: 'C es el ejemplo de compilado y PHP o Pearl los de interpretado. Java no es ninguna de las dos cosas.' },
        { id: 'tf2-22-2', q: 'El código fuente consiste en instrucciones en lenguaje natural, en inglés.', a: true, explain: 'Es la definición del primer punto del procedimiento.' },
        { id: 'tf2-22-3', q: 'La liberación de memoria en Java hay que pedirla explícitamente al terminar de usar cada objeto.', a: false, explain: 'El Garbage Collector la libera automáticamente; por eso no hacen falta ni malloc ni liberación manual.' },
        { id: 'tf2-22-4', q: 'El módulo que atiende los errores lanzados durante la ejecución es el Exception Handler.', a: true, explain: 'Es el último módulo que enumera la segunda parte del procedimiento.' },
        { id: 'tf2-22-5', q: 'El Memory Manager puede necesitar hablar con la plataforma para paginar.', a: true, explain: 'El apunte dice que habla tanto con la memoria física de la máquina como con la plataforma si es que necesita paginar.' },
      ],
      mc: [
        {
          id: 'mc2-22-1',
          q: '¿En qué momento entra en juego el Just In Time compiler?',
          options: [
            'Al escribirse el archivo de código fuente en el editor',
            'Al analizarse la sintaxis y detectarse los errores',
            'Al empaquetarse las clases compiladas como librería',
            'Al correr el programa, sobre los archivos en Bytecode',
          ],
          correctIndex: 3,
          explain: 'Cuando el programa corre, el JRE toma los archivos en Bytecode y los pasa por el JIT para procesarlos y enviarlos al lenguaje que entiende la JVM.',
        },
        {
          id: 'mc2-22-2',
          q: '¿Qué módulo se ocupa de levantar a memoria las clases y objetos necesarios?',
          options: [
            'El ClassLoader, valiéndose del Memory Manager',
            'El Garbage Collector, antes de liberar espacio',
            'El Exception Handler, al detectar una falla',
            'El compilador del JDK, durante la traducción',
          ],
          correctIndex: 0,
          explain: 'El ClassLoader levanta a memoria todo lo necesario para poder correr el programa mediante el módulo de Memory Manager.',
        },
        {
          id: 'mc2-22-3',
          q: '¿Qué característica tiene el archivo que produce el compilador?',
          options: [
            'Es texto plano en lenguaje natural que la VM lee de a una línea',
            'Es un binario en Bytecode que la JVM no interpreta directamente',
            'Es código de máquina propio del sistema operativo destino',
            'Es un paquete comprimido en formato zip con extensión propia',
          ],
          correctIndex: 1,
          explain: 'El archivo compilado que está en Bytecode es un archivo binario; no es código de máquina y la JVM no lo interpreta directamente.',
        },
      ],
      ms: [
        {
          id: 'ms2-22-1',
          q: '¿Qué tareas están correctamente asignadas a su módulo?',
          options: [
            'JIT: procesar el Bytecode y enviarlo al lenguaje que entiende la JVM',
            'ClassLoader: levantar a memoria clases y objetos',
            'Memory Manager: hablar con la memoria física y con la plataforma',
            'Garbage Collector: eliminar automáticamente lo que ya no se usa',
            'Exception Handler: optimizar las sentencias de control ineficientes',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'El Exception Handler maneja los errores lanzados durante la ejecución; no optimiza nada.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-22-1', front: '¿En qué categoría cae Java: compilado o interpretado?', back: 'En ninguna. PHP y Pearl son interpretados, C es compilado, y el apunte aclara que Java no es un lenguaje interpretado ni compilado.' },
      { id: 'fc2-22-2', front: '¿Qué produce el compilador del JDK?', back: 'Código en Bytecode: un archivo binario que no es código de máquina y que la JVM no ejecuta ni interpreta en forma directa.' },
      { id: 'fc2-22-3', front: '¿Qué hace el JRE con el Bytecode al correr el programa?', back: 'Lo pasa por el JIT (Just In Time compiler) para procesarlo y enviarlo al lenguaje que entiende la JVM.' },
      { id: 'fc2-22-4', front: '¿Qué módulo evita tener que usar malloc?', back: 'El Garbage Collector: al liberar automáticamente lo que ya no se usa, no hace falta reserva previa ni liberación manual de memoria.' },
      { id: 'fc2-22-5', front: '¿Quién atiende los errores en tiempo de ejecución?', back: 'El Exception Handler, el módulo que maneja los posibles errores que puedan llegar a lanzarse durante la ejecución del programa.' },
    ],
  },
  '23': {
    quiz2: {
      tf: [
        { id: 'tf2-23-1', q: 'Los valores de las variables estáticas viven en el área de CLASS.', a: true, explain: 'El área de CLASS maneja los valores de variables que son "de Clase", también llamadas estáticas.' },
        { id: 'tf2-23-2', q: 'La pila de llamadas guarda solamente qué función llamó a cuál, sin los argumentos.', a: false, explain: 'El STACK guarda además los argumentos que se pasan entre funciones y los valores retornados por cada una.' },
        { id: 'tf2-23-3', q: 'Un programa Java puede acceder al disco rígido sin intervención de la máquina virtual.', a: false, explain: 'El programa nunca interactuará con los recursos directamente: siempre mediante la VM.' },
        { id: 'tf2-23-4', q: 'La variable de entorno del classpath viene con un valor por defecto.', a: true, explain: 'Por defecto su valor es el "directorio actual".' },
        { id: 'tf2-23-5', q: 'Los controladores de bases de datos figuran entre las librerías que pueden vivir en el classpath.', a: true, explain: 'El apunte los incluye junto con frameworks web, utilidades de audio, librerías de estadísticas y frameworks de persistencia.' },
      ],
      mc: [
        {
          id: 'mc2-23-1',
          q: '¿Qué área de memoria contiene los objetos que se están ejecutando en un momento dado?',
          options: [
            'El área de CLASS, junto a las variables estáticas',
            'El STACK, junto a la pila de llamadas',
            'El HEAP, definido como el "montón" de datos',
            'El classpath, definido en el sistema operativo',
          ],
          correctIndex: 2,
          explain: 'El HEAP es, como la palabra lo dice, el "montón" de objetos y demás datos que están ejecutándose en un momento determinado.',
        },
        {
          id: 'mc2-23-2',
          q: '¿Qué memoria usa efectivamente nuestro programa Java?',
          options: [
            'Un área de memoria que la máquina virtual administra',
            'La memoria física de la máquina, en forma directa',
            'La memoria que el sistema operativo pagina a disco',
            'La memoria reservada por el compilador al compilar',
          ],
          correctIndex: 0,
          explain: 'La que usa la memoria física es la VM; nuestro programa usa un área de memoria que la VM administra.',
        },
        {
          id: 'mc2-23-3',
          q: '¿Quién suele encargarse del classpath en la práctica diaria?',
          options: [
            'El compilador, que lo deduce de las dependencias',
            'Los IDE, que por lo general lo manejan por nosotros',
            'El Garbage Collector, al liberar librerías sin uso',
            'El sistema operativo, que lo fija en la instalación',
          ],
          correctIndex: 1,
          explain: 'Establecer la variable a mano no es muy práctico; existen muchas herramientas para el problema y los IDE por lo general lo manejan por nosotros.',
        },
      ],
      ms: [
        {
          id: 'ms2-23-1',
          q: '¿Qué guarda el área de STACK según el apunte?',
          options: [
            'Qué función llama a qué otra función',
            'Los argumentos que se van pasando entre funciones',
            'Los valores retornados por cada función',
            'Los objetos que están ejecutándose en ese momento',
            'Los valores de las variables de clase',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'Los objetos en ejecución van al HEAP y las variables de clase al área de CLASS.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-23-1', front: '¿En cuántas partes divide la JVM la memoria que reserva?', back: 'En tres: HEAP, el área de STACK y el área de CLASS.' },
      { id: 'fc2-23-2', front: '¿Qué guarda la pila de llamadas?', back: 'Qué función llama a qué otra función, los argumentos que se van pasando entre ellas y los valores retornados por cada una.' },
      { id: 'fc2-23-3', front: '¿Dónde viven las variables estáticas?', back: 'En el área de CLASS, que maneja los valores de las variables "de Clase" o estáticas.' },
      { id: 'fc2-23-4', front: '¿Cómo llega el programa a los recursos del sistema?', back: 'Nunca en forma directa: el JRE junto con la JVM interactúan con el disco rígido, otros recursos, el SO y la plataforma, siempre mediante la VM.' },
      { id: 'fc2-23-5', front: '¿Qué define el classpath?', back: 'El espacio del SO, accedido por el JRE, donde están todas las librerías del lenguaje y las de utilidades que agreguemos, para que corra la JVM, funcione el JRE y se ejecuten nuestros programas.' },
    ],
  },
  '24': {
    quiz2: {
      tf: [
        { id: 'tf2-24-1', q: 'El compilador de Java creado por IBM se llama jikes.', a: true, explain: 'El apunte lo usa como el mejor ejemplo de compilador que sí hace optimizaciones, a diferencia de javac.' },
        { id: 'tf2-24-2', q: 'La optimización del código termina siendo tarea de la máquina virtual, mediante el JIT.', a: true, explain: 'javac no optimiza, pero la VM, antes de ejecutar el código y mediante el JIT, sí hace optimizaciones de todo tipo.' },
        { id: 'tf2-24-3', q: 'Al ejecutar hay que indicarle al comando el nombre del archivo compilado.', a: false, explain: 'Se le pasa el nombre de la clase, no el del archivo: "java Auto" y no "java Auto.class".' },
        { id: 'tf2-24-4', q: 'El compilador puede recibir por argumento dónde tomar las fuentes y dónde dejar los compilados.', a: true, explain: 'Es lo que generalmente hacen los IDE cuando usan javac; por defecto deja los compilados donde se ejecuta.' },
        { id: 'tf2-24-5', q: 'Al usar librerías no hace falta informarle nada al compilador.', a: false, explain: 'En caso de usar librerías es necesario pasarle al compilador la ubicación de estas para evitar errores.' },
      ],
      mc: [
        {
          id: 'mc2-24-1',
          q: 'Si un programa supera el límite superior de memoria configurado, ¿qué ocurre?',
          options: [
            'Se lanza un java.lang.OutOfMemoryError',
            'El Garbage Collector amplía el heap sin avisar',
            'El compilador rechaza la clase en la próxima compilación',
            'La JVM aplica el algoritmo ergonómico y continúa',
          ],
          correctIndex: 0,
          explain: 'Si la ejecución excede el valor de Xmx, se lanza java.lang.OutOfMemoryError. El algoritmo "ergonómico" solo define valores por defecto cuando no se especifican los parámetros.',
        },
        {
          id: 'mc2-24-2',
          q: 'Si la clase Auto depende de la clase Motor, ¿qué hace el compilador?',
          options: [
            'Falla y pide compilar Motor por separado primero',
            'Compila también Motor, resolviendo las dependencias',
            'Empaqueta ambas en un único archivo con extensión jar',
            'Ignora Motor hasta que se la invoque en ejecución',
          ],
          correctIndex: 1,
          explain: 'javac compila las dependencias de cada clase según sea necesario. El resultado de compilar Auto.java es Auto.class.',
        },
        {
          id: 'mc2-24-3',
          q: '¿Qué hace concretamente el compilador con el código fuente?',
          options: [
            'Reordena las sentencias para que el resultado sea eficiente',
            'Lo traduce a lenguaje de máquina del sistema operativo',
            'Analiza la sintaxis y lo pasa a un estado "ejecutable"',
            'Lo conecta con el classpath y lo carga en el heap',
          ],
          correctIndex: 2,
          explain: 'javac hace lo que hacen todos los compiladores: analizar la sintaxis y, si es correcta, pasar el código a un estado "ejecutable"; de lo contrario muestra los errores.',
        },
      ],
      ms: [
        {
          id: 'ms2-24-1',
          q: '¿Qué parámetros del comando de ejecución destaca el apunte como los más importantes?',
          options: [
            'classpath',
            'Xms',
            'Xmx',
            '-help',
            '-X',
          ],
          correctIndexes: [0, 1, 2],
          explain: '-help y -X son opciones para consultar la configuración del compilador javac, no parámetros del comando java.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-24-1', front: '¿Qué significa la sigla javac?', back: 'Java compiler. Toma los archivos de código fuente y los pasa a código que la máquina virtual puede utilizar.' },
      { id: 'fc2-24-2', front: '¿Qué compilador se cita como ejemplo de uno que sí optimiza?', back: 'jikes, el compilador de Java creado por IBM. javac, en cambio, no hace optimizaciones sobre el código.' },
      { id: 'fc2-24-3', front: '¿Qué se le pasa al comando de ejecución?', back: 'El nombre de la clase, no el del archivo compilado: si compilamos Auto.java y obtuvimos Auto.class, corremos con ">java Auto".' },
      { id: 'fc2-24-4', front: '¿Para qué sirven Xms y Xmx?', back: 'Controlan los límites de la memoria física del programa: Xms indica de cuánta memoria dispondrá el heap y Xmx hasta cuánto podrá crecer.' },
      { id: 'fc2-24-5', front: '¿Cómo se consultan las opciones del compilador?', back: 'Con ">javac -help" para la variedad de opciones y ">javac -X" para la serie "extendida" de configuraciones disponibles.' },
      { id: 'fc2-24-6', front: '¿Qué pasa si el código fuente es ineficiente?', back: 'El resultado compilado será ineficiente, porque javac no optimiza. Por fortuna la VM sí optimiza antes de ejecutar, mediante el JIT.' },
    ],
  },
  '25': {
    quiz2: {
      tf: [
        { id: 'tf2-25-1', q: 'Un archivo empaquetado con la herramienta de empaquetado puede abrirse con WinZip.', a: true, explain: 'El formato de empaquetado y compresión es zip estándar; solo cambia la extensión, que pasa a ser .jar.' },
        { id: 'tf2-25-2', q: 'La herramienta de análisis del kit está escrita en Java.', a: true, explain: 'El apunte lo remarca al mostrar JConsole analizando la ejecución de sí misma: "como es de esperarse, JConsole está programado en Java".' },
        { id: 'tf2-25-3', q: 'Los comentarios que empiezan con doble barra alcanzan para generar la documentación.', a: false, explain: 'Hacen falta comentarios especiales, que comienzan siempre con "/**".' },
        { id: 'tf2-25-4', q: 'La generación manual de documentación de todo un sistema puede ser compleja o tediosa.', a: true, explain: 'Por eso el apunte recomienda que lo mejor, hoy en día, es utilizar un IDE para estas tareas.' },
        { id: 'tf2-25-5', q: 'Las herramientas para firmar clases y paquetes forman parte del contenido evaluado de la materia.', a: false, explain: 'El apunte las menciona, pero aclara que escapan al scope de la materia.' },
      ],
      mc: [
        {
          id: 'mc2-25-1',
          q: '¿En qué formato entrega la documentación la herramienta correspondiente?',
          options: [
            'Un documento de texto plano con los comentarios extraídos',
            'Un sitio en HTML dividido en frames para navegarlo',
            'Un paquete comprimido listo para distribuir como librería',
            'Una vista gráfica conectada al proceso en ejecución',
          ],
          correctIndex: 1,
          explain: 'javadoc genera documentación en formato HTML y también un "sitio" con la misma, dividida en frames para facilitar la navegación.',
        },
        {
          id: 'mc2-25-2',
          q: '¿Con qué se compara al paquete generado cuando incluye la clase principal?',
          options: [
            'Con un archivo .exe de Windows que contiene todo el programa',
            'Con un archivo de código fuente listo para compilar',
            'Con una variable de entorno que apunta a las librerías',
            'Con una imagen de la máquina virtual lista para instalar',
          ],
          correctIndex: 0,
          explain: 'El apunte hace la analogía con Windows: sería como generar un ".exe" con todo nuestro programa.',
        },
        {
          id: 'mc2-25-3',
          q: '¿Qué muestra la herramienta gráfica de análisis del kit?',
          options: [
            'Los errores de sintaxis que devuelve el compilador',
            'La estructura de paquetes y clases del proyecto',
            'El uso de memoria heap, de procesador y de hilos',
            'El contenido de los paquetes empaquetados en zip',
          ],
          correctIndex: 2,
          explain: 'JConsole se conecta a un proceso java en ejecución y muestra información sobre el uso de memoria (heap), de procesador, de hilos de ejecución, etc.',
        },
      ],
      ms: [
        {
          id: 'ms2-25-1',
          q: '¿Qué usos tiene la herramienta de empaquetado según el apunte?',
          options: [
            'Empaquetar clases compiladas en forma de librerías',
            'Empaquetar todo un programa junto con su clase principal',
            'Indicar cuál es la clase que se usa para iniciar el programa',
            'Mandar a ejecutar el paquete generado',
            'Generar la documentación HTML del proyecto',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La documentación HTML es tarea de javadoc, no de jar.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-25-1', front: '¿Qué comentarios dispara la generación de documentación?', back: 'Los "comentarios especiales": comentarios regulares que comienzan siempre con "/**". El IDE los pinta de un color distinto de los comentarios de código.' },
      { id: 'fc2-25-2', front: '¿Cómo recorre el proyecto la herramienta de documentación?', back: 'Igual que el compilador: se le pasa la clase con los comentarios y va recorriendo las otras clases que esta utiliza según sea necesario.' },
      { id: 'fc2-25-3', front: '¿Qué formato tiene por dentro un .jar?', back: 'Zip estándar (con compresión si se configura); solo cambia la extensión, así que se puede abrir con WinZip o cualquier herramienta similar.' },
      { id: 'fc2-25-4', front: 'Secuencia para compilar, empaquetar y ejecutar', back: '>javac Auto.java, luego >jar -cvf MiProgramaAuto.jar Auto.class, y por último >jar MiProgramaAuto.' },
      { id: 'fc2-25-5', front: '¿Qué es el profiling en el kit de Java?', back: 'Lo que hace JConsole: una herramienta gráfica que se conecta a un proceso java en ejecución y permite analizar aspectos básicos de la performance del programa.' },
      { id: 'fc2-25-6', front: '¿Qué herramientas quedan fuera del alcance de la materia?', back: 'Las de generar pares de claves pública/privada, firmar clases, firmar paquetes (jars generados), generar web services, entre otras.' },
    ],
  },
  '26': {
    quiz2: {
      tf: [
        { id: 'tf2-26-1', q: 'El comportamiento típico que se le pide a la rueda es girar.', a: true, explain: 'El ejercicio 1 lo pide expresamente, junto a radio, color y tipo de material.' },
        { id: 'tf2-26-2', q: 'Se pueden usar referencias entre proyectos de Eclipse para reutilizar las clases del ejercicio previo.', a: false, explain: 'La consigna dice que no se vieron referencias entre proyectos y pide copiar y pegar las clases.' },
        { id: 'tf2-26-3', q: 'El auto puede tener una o varias ruedas según el modelo del ejercicio.', a: true, explain: 'El ejercicio 4 dice que el auto está compuesto por un motor, una caja de velocidades y una o varias ruedas.' },
        { id: 'tf2-26-4', q: 'El reglamento pide realizar validaciones de valores en cada clase.', a: false, explain: 'Al contrario: el objetivo es la práctica de código y no es necesario ni recomendado hacer operaciones complejas ni validaciones.' },
        { id: 'tf2-26-5', q: 'La devolución se da en forma global a través de la plataforma de la materia.', a: true, explain: 'El punto 11 del reglamento: se hace hincapié en los puntos flojos comunes y se remarcan los puntos correctos.' },
      ],
      mc: [
        {
          id: 'mc2-26-1',
          q: '¿Qué característica del motor se ejemplifica con los valores "1600 o 1.6"?',
          options: [
            'Los caballos de fuerza del motor',
            'La cantidad de marchas disponibles',
            'La cilindrada del motor',
            'La velocidad de giro del motor',
          ],
          correctIndex: 2,
          explain: 'El ejercicio 3 pide marca, hp (caballos de fuerza) y cilindrada, y ejemplifica la cilindrada con "1600 o 1.6".',
        },
        {
          id: 'mc2-26-2',
          q: '¿Qué valores puede tomar el tipo de relación de la caja de velocidades?',
          options: [
            'Larga, mediana o corta (L-M-C)',
            'Acero, aleación u otro material',
            'Manual, automática o secuencial',
            'Alta, media o baja según la marcha',
          ],
          correctIndex: 0,
          explain: 'El enunciado especifica el tipo de relación como larga-mediana-corta o L-M-C.',
        },
        {
          id: 'mc2-26-3',
          q: '¿Qué nombres de variables ejemplifica el reglamento como aceptables?',
          options: [
            '"x", "nom" y "val", por ser breves y directos',
            '"incógnita", "nombre" y "valorDeRetorno"',
            'Los que repitan el nombre de la clase como prefijo',
            'Los escritos en mayúsculas y separados con guiones bajos',
          ],
          correctIndex: 1,
          explain: 'El reglamento pide que el código se documente por sí mismo, y contrapone "x", "nom" y "val" con "incógnita", "nombre" y "valorDeRetorno".',
        },
      ],
      ms: [
        {
          id: 'ms2-26-1',
          q: '¿Qué características se piden para el Auto del último ejercicio?',
          options: [
            'Marca',
            'Modelo',
            'Cantidad de puertas',
            'Aire acondicionado como opcional',
            'Tipo de relación de marchas',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'El tipo de relación es una característica de la caja de velocidades, no del auto.',
        },
        {
          id: 'ms2-26-2',
          q: '¿Qué condiciones pueden dejar la actividad como "no entregada"?',
          options: [
            'Que los programas no compilen y corran correctamente',
            'Que se ignoren las convenciones de código de los módulos teóricos',
            'Que se use nombres de variables poco descriptivos',
            'Que se acople la salida de los métodos a la consola sin justificar',
            'Que la nota numérica quede por debajo del mínimo',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'No hay nota numérica: la actividad no está calificada numéricamente y su valoración es "entregada" o "no entregada".',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-26-1', front: '¿Qué características tiene la rueda del ejercicio 1?', back: 'Radio, color y tipo de material que la compone (acero, aleación, etc.), con "girar" como comportamiento típico.' },
      { id: 'fc2-26-2', front: '¿Qué comportamiento se le pide a la caja de velocidades?', back: 'Cambiar de marcha. Sus características son fabricante, cantidad de marchas y tipo de relación (larga-mediana-corta o L-M-C).' },
      { id: 'fc2-26-3', front: '¿Qué se le debe poder hacer al motor?', back: 'Hacerlo arrancar y detener. Sus características son marca, hp (caballos de fuerza) y cilindrada (1600 o 1.6).' },
      { id: 'fc2-26-4', front: '¿Cómo se compone el auto?', back: 'Por un motor, una caja de velocidades y una o varias ruedas; además tiene marca, modelo, cantidad de puertas y el opcional de aire acondicionado.' },
      { id: 'fc2-26-5', front: '¿Cómo se organiza la entrega en el IDE?', back: 'Cada ejercicio en su propio "Java Project", copiando y pegando las clases del ejercicio anterior cuando hagan falta; la entrega es un paquete exportado desde Eclipse o del IDE que se use.' },
      { id: 'fc2-26-6', front: '¿Cómo se valora la actividad?', back: 'Sin nota numérica: "entregada" o "no entregada", con una sola entrega admitida y sin reevaluación por parte del docente.' },
    ],
  },
  '27': {
    quiz2: {
      tf: [
        { id: 'tf2-27-1', q: 'La letra L identifica a las computadoras de tipo Laptop.', a: true, explain: 'Los tipos son D para desktop, A para All-in-one y L para Laptop.' },
        { id: 'tf2-27-2', q: 'La velocidad del procesador se expresa en RPM.', a: false, explain: 'La velocidad del procesador va en gigahertz; las RPM son la velocidad de operación del disco rígido.' },
        { id: 'tf2-27-3', q: 'El ejercicio de componentes compartidos pide anotar los resultados como comentarios en el código.', a: true, explain: 'La consigna lo pide y hasta recuerda que los comentarios, tal cual en C, son con "//" o "/* ....... */".' },
        { id: 'tf2-27-4', q: 'Al implementar el apagado hay que poder consultar el estado de los componentes.', a: true, explain: 'El ejercicio 3 pide agregar los atributos y comportamientos necesarios para preguntarle a la computadora y a sus componentes si están encendidos.' },
        { id: 'tf2-27-5', q: 'Las tres características básicas de la computadora dependen de su tipo.', a: false, explain: 'El enunciado aclara que cada computadora posee 3 características básicas independientemente de su tipo: disco rígido, procesador y memoria.' },
      ],
      mc: [
        {
          id: 'mc2-27-1',
          q: '¿Qué escenario plantea el ejercicio de componentes compartidos?',
          options: [
            'Que cada computadora tenga su propio disco de igual marca',
            'Que una Laptop y una Desktop tengan el mismo disco',
            'Que una computadora cambie de disco al encenderse',
            'Que los discos se agrupen dentro de una única PC',
          ],
          correctIndex: 1,
          explain: 'La consigna dice: si tengo un Samsung de 500gb, tanto una Laptop como una Desktop tengan el mismo disco. Después hay que alterarle los valores y volver a imprimir.',
        },
        {
          id: 'mc2-27-2',
          q: '¿Qué debe ocurrir cuando la computadora ejecuta su comportamiento de encendido?',
          options: [
            'Se enciende su procesador y su disco rígido',
            'Se libera la memoria ocupada por sus componentes',
            'Se imprime automáticamente el detalle de sus valores',
            'Se construyen los componentes que aún no existen',
          ],
          correctIndex: 0,
          explain: 'El ejercicio 3 dice que cuando una computadora enciende, se enciende su procesador y su disco rígido.',
        },
        {
          id: 'mc2-27-3',
          q: '¿Qué datos tiene el disco rígido según el enunciado?',
          options: [
            'Marca, modelo y velocidad en gigahertz',
            'Marca, capacidad en gigabytes y velocidad en RPM',
            'Marca, año de fabricación y tipo asignado',
            'Capacidad en gigabytes, color y cantidad de memoria',
          ],
          correctIndex: 1,
          explain: 'Marca, modelo y velocidad en gigahertz son del procesador. El disco tiene marca, capacidad en gigabytes y velocidad de operación en RPM.',
        },
      ],
      ms: [
        {
          id: 'ms2-27-1',
          q: '¿Qué elementos aparecen en la línea de ejemplo que debe poder imprimir una computadora?',
          options: [
            'La marca y el modelo de la computadora',
            'La marca del procesador',
            'La capacidad del disco',
            'La cantidad de memoria RAM',
            'El año de fabricación',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'El ejemplo es "Toshiba G480 -- Procesador: AMD -- Disco: 500gb -- Ram:4gb": no incluye el año de fabricación.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-27-1', front: '¿Qué letras distinguen los tipos de computadora?', back: 'D para desktop, A para All-in-one y L para Laptop.' },
      { id: 'fc2-27-2', front: '¿Qué tres componentes tiene toda computadora del ejercicio?', back: 'Un disco rígido, un procesador y una cierta cantidad de memoria, independientemente de su tipo.' },
      { id: 'fc2-27-3', front: '¿Cómo se describe el disco rígido y cómo el procesador?', back: 'Disco: marca, capacidad en gigabytes y velocidad de operación en RPM. Procesador: marca, modelo y velocidad en gigahertz.' },
      { id: 'fc2-27-4', front: 'Ejemplo de configuración a construir', back: 'Una Laptop Toshiba, G480, modelo 2013, con Procesador Intel de 1,5 GHz, 4 gb de RAM y un disco de 500gb.' },
      { id: 'fc2-27-5', front: '¿Qué hay que observar al compartir un componente entre dos computadoras?', back: 'Se le alteran los valores al componente compartido, se vuelven a imprimir los valores de la computadora y se anotan los resultados como comentarios en el código.' },
      { id: 'fc2-27-6', front: '¿Qué comportamientos pide el último ejercicio?', back: 'Encender (que enciende también procesador y disco rígido) y apagar, más los atributos y comportamientos necesarios para preguntar si la computadora y sus componentes están encendidos.' },
    ],
  },
  '28': {
    quiz2: {
      tf: [
        { id: 'tf2-28-1', q: 'La abstracción define clases con sus atributos y operaciones a partir del dominio observado.', a: true, explain: 'Del proceso de abstracción salen las partes del universo, cómo interactúan y, con eso, las clases con sus atributos y operaciones.' },
        { id: 'tf2-28-2', q: 'Las clases más genéricas se ubican en el nivel inferior de la jerarquía.', a: false, explain: 'Lo común va en la parte superior y lo diferente en la inferior.' },
        { id: 'tf2-28-3', q: 'Establecer qué debe hacer cada parte para resolver el problema es definir responsabilidades.', a: true, explain: 'Es la definición textual de responsabilidades de clases del apunte.' },
        { id: 'tf2-28-4', q: 'Un caniche y un Pug Carlino ladran exactamente del mismo modo según el apunte.', a: false, explain: 'El apunte dice que el Pug también ladra y juega, aunque lo hace muy distinto al caniche.' },
        { id: 'tf2-28-5', q: 'Los atributos de las clases deberían ser privados y accederse mediante operaciones.', a: true, explain: 'Por eso se habla siempre del comportamiento: lo que la clase tiene es irrelevante frente a lo que hace.' },
      ],
      mc: [
        {
          id: 'mc2-28-1',
          q: '¿Qué criterio usa el apunte para agrupar clases en una jerarquía?',
          options: [
            'La cantidad de instancias que se esperan de cada clase',
            'Las similitudes y diferencias entre atributos y operaciones',
            'El orden alfabético de los nombres de todas las clases del dominio',
            'La cantidad de atributos privados declarados',
          ],
          correctIndex: 1,
          explain: 'Según las similitudes y diferencias se agrupan los atributos y operaciones en común y se separan las diferencias.',
        },
        {
          id: 'mc2-28-2',
          q: 'El conjunto de operaciones públicas de una clase recibe el nombre de...',
          options: [
            'Jerarquía de la clase',
            'Responsabilidad de la clase',
            'Interfaz pública de la clase',
            'Abstracción de la clase',
          ],
          correctIndex: 2,
          explain: 'El apunte lo nombra así: el conjunto de las cosas que la clase hace se llama interfaz pública.',
        },
        {
          id: 'mc2-28-3',
          q: 'El ordenamiento jerárquico superior-inferior indica principalmente que...',
          options: [
            'Las clases superiores son más eficientes en memoria',
            'Las clases inferiores tienen menos errores de compilación',
            'Las clases superiores se ejecutan siempre antes que las clases inferiores del modelo',
            'Las clases superiores agrupan lo común y las inferiores lo diferente',
          ],
          correctIndex: 3,
          explain: 'No se trata de mejor o peor: es solo un ordenamiento entre lo común y lo diferente.',
        },
        {
          id: 'mc2-28-4',
          q: '¿Cómo define el apunte a la herencia?',
          options: [
            'Un ordenamiento entre clases que define una relación "es un"',
            'Un mecanismo para copiar atributos de una clase a otra',
            'Una forma de instanciar objetos sin usar constructores',
            'Una técnica para ocultar el estado interno de un objeto',
          ],
          correctIndex: 0,
          explain: 'Es la definición literal que cierra la sección de relación ES-UN.',
        },
        {
          id: 'mc2-28-5',
          q: 'Si profesor ES UN empleado y empleado ES UNA persona, el apunte concluye que...',
          options: [
            'Persona ES UN profesor por definición inversa',
            'Profesor ES UNA persona por carácter transitivo',
            'Empleado deja de ser una persona al especializarse',
            'Profesor y empleado deben fusionarse en una clase',
          ],
          correctIndex: 1,
          explain: 'La relación ES-UN encadena niveles: profesor → empleado → persona.',
        },
      ],
      ms: [
        {
          id: 'ms2-28-1',
          q: '¿Qué produce el proceso de abstracción según el apunte?',
          options: [
            'La identificación de las partes del dominio',
            'La comprensión de cómo interactúan esas partes',
            'La definición de clases con atributos y operaciones',
            'El establecimiento de responsabilidades de cada parte',
            'La elección del IDE con el que se va a trabajar',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La elección del IDE no forma parte del proceso de abstracción descripto.',
        },
        {
          id: 'ms2-28-2',
          q: '¿Cuáles de estas clases forman la jerarquía de perros del apunte?',
          options: [
            'Caniche',
            'Pug Carlino',
            'Dóberman',
            'Bulldog Francés',
            'Border Collie',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'El apunte trabaja con Caniche, Pug Carlino y Dóberman (y menciona además Labrador y Siberiano al hablar de la interfaz pública).',
        },
        {
          id: 'ms2-28-3',
          q: '¿Qué afirmaciones sobre el orden jerárquico son incorrectas según el apunte?',
          options: [
            'Se agrupa lo común en la parte superior',
            'Se dejan las diferencias en la parte inferior',
            'Se ordena según similitudes y diferencias',
            'Es importante dar orden a la multiplicidad de partes',
            'Cada clase debe tener responsabilidades bien definidas',
          ],
          correctIndexes: [],
          explain: 'Las cinco afirmaciones son correctas y están textualmente en el apunte.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-28-1', front: '¿Qué se establece además de clases, atributos y operaciones durante la abstracción?', back: 'Las responsabilidades: qué debe hacer cada parte para contribuir a la solución del problema.' },
      { id: 'fc2-28-2', front: '¿Dónde van las partes comunes en la jerarquía?', back: 'En la parte superior. Las diferentes quedan en la inferior.' },
      { id: 'fc2-28-3', front: '¿El orden jerárquico implica calidad?', back: 'No. No se agrupa según mejor o peor: es solo un ordenamiento.' },
      { id: 'fc2-28-4', front: '¿Qué hace que un perro sea un perro?', back: 'Tener nombre y edad, y ladrar y jugar. Si otra cosa tiene y hace todo eso, entonces es un perro.' },
      { id: 'fc2-28-5', front: '¿Qué es más importante para el ES-UN: los atributos o el comportamiento?', back: 'El comportamiento. Los atributos deberían ser privados y accederse por operaciones, así que lo que la clase tiene es irrelevante.' },
      { id: 'fc2-28-6', front: '¿Cómo se llama el conjunto de operaciones públicas?', back: 'Interfaz pública de la clase.' },
      { id: 'fc2-28-7', front: '¿Cómo define el apunte la herencia?', back: 'Un ordenamiento entre clases que define una relación "es un".' },
      { id: 'fc2-28-8', front: 'Cadena ES-UN de personas del apunte', back: 'Profesor ES UN empleado, empleado ES UNA persona, por lo tanto profesor ES UNA persona.' },
    ],
  },
  '29': {
    quiz2: {
      tf: [
        { id: 'tf2-29-1', q: 'Escribiendo "class Caniche extends Perro {}" el caniche ya puede ladrar.', a: true, explain: 'Hereda todo el comportamiento de Perro, así que c.ladrar() devuelve GUAU aunque Caniche esté vacía.' },
        { id: 'tf2-29-2', q: 'El runtime resuelve las llamadas heredadas sin recorrer la jerarquía.', a: false, explain: 'El runtime hace un proceso similar al del compilador: si no está en la clase, ejecuta el código heredado de la superclase.' },
        { id: 'tf2-29-3', q: 'Agregarle cuidarCasa() al Dóberman rompe la relación "es un" con Perro.', a: false, explain: 'La relación "es un" no obliga a hacer exactamente lo mismo: se puede agregar comportamiento.' },
        { id: 'tf2-29-4', q: 'La búsqueda del método sube un escalón por vez hasta el final de la jerarquía.', a: true, explain: 'El proceso se repite en cada escalón, escalando hasta encontrar la operación que matchea.' },
        { id: 'tf2-29-5', q: 'La clase Perro del apunte declara los atributos edad y nombre como públicos.', a: false, explain: 'El código del apunte los declara private, con getters y setters.' },
      ],
      mc: [
        {
          id: 'mc2-29-1',
          q: '¿Qué ocurre si el método no aparece en ningún nivel de la jerarquía?',
          options: [
            'El código no puede compilarse correctamente',
            'El código compila y devuelve null en ejecución',
            'La JVM crea el método vacío automáticamente',
            'El compilador lo busca en la clase Object y lo ejecuta',
          ],
          correctIndex: 0,
          explain: 'Si no se encuentra en ninguna parte de la cadena de la jerarquía, no compila.',
        },
        {
          id: 'mc2-29-2',
          q: 'La consecuencia principal de la herencia que destaca el apunte es...',
          options: [
            'Un menor consumo de memoria en tiempo de ejecución',
            'La posibilidad de declarar atributos públicos',
            'La reutilización de código escrito una sola vez',
            'La eliminación de la necesidad de constructores',
          ],
          correctIndex: 2,
          explain: 'En Caniche no se repite nada del código: la herencia apunta fundamentalmente a la reutilización.',
        },
        {
          id: 'mc2-29-3',
          q: '¿Qué operación se le agrega al Labrador en el ejemplo del apunte?',
          options: [
            'cuidarCasa()',
            'ladrarConVolumen()',
            'jugarConNiños()',
            'cuidarNiños()',
          ],
          correctIndex: 3,
          explain: 'Al Labrador se le agrega cuidarNiños(); cuidarCasa() es la del Dóberman.',
        },
        {
          id: 'mc2-29-4',
          q: '¿Qué expresa la línea "Perro x = new Doberman();"?',
          options: [
            'Que Perro y Doberman son la misma clase',
            'Que Doberman ES UN Perro y cumple su interfaz pública',
            'Que se está sobreescribiendo el constructor de Perro',
            'Que Doberman pierde sus operaciones propias para siempre',
          ],
          correctIndex: 1,
          explain: 'El comentario del apunte en esa línea es exactamente "Doberman ES UN Perro".',
        },
        {
          id: 'mc2-29-5',
          q: '¿Qué devuelve el método jugar() de la clase Perro del apunte?',
          options: [
            'La cadena "JUGANDO"',
            'La cadena "GUAU"',
            'Un valor booleano true',
            'La cadena "WIF WIF"',
          ],
          correctIndex: 0,
          explain: 'public String jugar() { return "JUGANDO"; }',
        },
      ],
      ms: [
        {
          id: 'ms2-29-1',
          q: '¿Qué contiene la clase Perro tal como la escribe el apunte?',
          options: [
            'Un atributo privado edad',
            'Un atributo privado nombre',
            'Un método ladrar() que devuelve "GUAU"',
            'Un método jugar() que devuelve "JUGANDO"',
            'Un método cuidarCasa() que devuelve "CUIDANDO"',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'cuidarCasa() es una operación agregada al Dóberman, no está en Perro.',
        },
        {
          id: 'ms2-29-2',
          q: '¿Qué es cierto sobre la resolución de una llamada heredada?',
          options: [
            'Se busca primero en la propia clase',
            'Después se busca en la clase de la que extiende',
            'Se compara cantidad, tipo y orden de parámetros',
            'El proceso se repite en cada escalón de la jerarquía',
            'La búsqueda se detiene siempre en el segundo nivel',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'No hay límite de dos niveles: se escala hasta encontrar el método o hasta agotar la jerarquía.',
        },
        {
          id: 'ms2-29-3',
          q: '¿Qué razas se mencionan al hablar de la interfaz pública de Perro?',
          options: [
            'Caniche',
            'Labrador',
            'Siberiano',
            'Dóberman',
            'Beagle',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'El apunte enumera caniches, labradores, siberianos y dóberman. Beagle no aparece.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-29-1', front: '¿Qué indica la palabra extends?', back: 'Que una clase es otra (Caniche extends Perro) y hereda todo su comportamiento.' },
      { id: 'fc2-29-2', front: '¿Qué pasa si el método no está en ningún nivel de la jerarquía?', back: 'El código no puede compilarse correctamente.' },
      { id: 'fc2-29-3', front: '¿Con qué se compara para elegir el método al escalar?', back: 'Con la cantidad, el tipo y el orden de los parámetros de la llamada.' },
      { id: 'fc2-29-4', front: '¿Cuál es la primera consecuencia importante de la herencia?', back: 'No se repite código: en Caniche no hay que escribir nada para ladrar o jugar. Es un mecanismo de reutilización.' },
      { id: 'fc2-29-5', front: 'Operaciones agregadas en el ejemplo', back: 'cuidarNiños() al Labrador y cuidarCasa() al Dóberman: son perros, pero hacen algo más.' },
      { id: 'fc2-29-6', front: '¿Qué significa "cumplir con la interfaz pública" de otra clase?', back: 'Hacer al menos lo que hace esa clase. La relación "es un" admite además comportamiento adicional.' },
      { id: 'fc2-29-7', front: '¿Qué hace el runtime si el método no está en la clase del objeto?', back: 'Ejecuta el código de la operación que se hereda de la superclase.' },
      { id: 'fc2-29-8', front: 'Salida de c.ladrar() con Caniche vacía', back: 'GUAU, el ladrido heredado de Perro.' },
    ],
  },
  '30': {
    quiz2: {
      tf: [
        { id: 'tf2-30-1', q: 'Sobreescribir exige mantener el tipo, el orden y la cantidad de parámetros.', a: true, explain: 'Es la condición para "pisar" el método heredado; si se altera, se cae en una sobrecarga.' },
        { id: 'tf2-30-2', q: 'La keyword super permite saltar dos niveles con super.super en jerarquías profundas.', a: false, explain: 'No se pueden encadenar las llamadas a super: siempre de a un nivel por clase.' },
        { id: 'tf2-30-3', q: 'Llamar a ladrar() dentro del propio ladrar() sin super genera recursión infinita.', a: true, explain: 'El método se llamaría a sí mismo infinitamente; con super se apunta al de la superclase.' },
        { id: 'tf2-30-4', q: 'El constructor por default se conserva aunque se declaren otros constructores.', a: false, explain: 'Si se definen constructores adicionales al constructor por default, este se pierde.' },
        { id: 'tf2-30-5', q: 'El apunte usa super(nombre) para reutilizar la asignación ya escrita en Perro.', a: true, explain: 'El comentario dice "RE-utilizo lo que ya escribi" en lugar de repetir this.nombre = nombre.' },
      ],
      mc: [
        {
          id: 'mc2-30-1',
          q: 'El ladrar() sobreescrito del Caniche en el apunte devuelve...',
          options: [
            '"WIF WIF"',
            '"GUAU GRRRR"',
            '"GUAU"',
            '"BIP BIP"',
          ],
          correctIndex: 0,
          explain: 'Caniche tiene un ladrido más agudo: return "WIF WIF";',
        },
        {
          id: 'mc2-30-2',
          q: '¿Qué se necesita para que exista la "parte Perro" de un Doberman antes de asignarle atributos propios?',
          options: [
            'Una llamada explícita al método ladrar()',
            'Una llamada implícita o explícita a super()',
            'Una instancia previa de la clase Object',
            'Una asignación directa con this a la superclase',
          ],
          correctIndex: 1,
          explain: 'Se agrega implícitamente una llamada a super() sin parámetros, el constructor por default.',
        },
        {
          id: 'mc2-30-3',
          q: 'La superclase, según el apunte, es otro nombre para...',
          options: [
            'La clase que contiene el método main',
            'La clase con más operaciones públicas',
            'La clase padre de la que se hereda',
            'La clase que se instancia primero en ejecución',
          ],
          correctIndex: 2,
          explain: 'El apunte la nombra al presentar la keyword super: la clase padre, también llamada superclase.',
        },
        {
          id: 'mc2-30-4',
          q: '¿Qué analiza el compilador cuando Caniche sí define ladrar()?',
          options: [
            'Si la sobreescritura cambia el tipo de retorno declarado',
            'Si el atributo nombre está inicializado en el constructor',
            'Si Perro tiene también un método ladrar heredable',
            'Si ladrar sin parámetros está definida en Caniche',
          ],
          correctIndex: 3,
          explain: 'Si está definida en la propia clase, la sintaxis es correcta y no hace falta escalar.',
        },
        {
          id: 'mc2-30-5',
          q: 'El beneficio concreto de usar super.ladrar() en Doberman es que...',
          options: [
            'El "GUAU" se escribe una sola vez, en la clase Perro',
            'El método se ejecuta más rápido que uno propio',
            'El atributo agresividad queda inicializado por default',
            'El compilador deja de verificar la jerarquía completa',
          ],
          correctIndex: 0,
          explain: 'El Dóberman retorna "GUAU GRRRR" pero el código del "GUAU" está en un solo lugar.',
        },
      ],
      ms: [
        {
          id: 'ms2-30-1',
          q: '¿Para qué se usa la keyword super en el apunte?',
          options: [
            'Para llamar a un método de la superclase',
            'Para llamar a un constructor de la clase padre',
            'Para reutilizar código heredado dentro de un método pisado',
            'Para encadenar varios niveles de jerarquía de una sola vez',
            'Para hacer públicos los atributos privados heredados',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'Ni encadena niveles ni cambia la visibilidad de los atributos.',
        },
        {
          id: 'ms2-30-2',
          q: '¿Qué constructores define la versión correcta de Doberman en el apunte?',
          options: [
            'Doberman(int agresividad)',
            'Doberman(String nombre)',
            'Doberman()',
            'Doberman(String nombre, int agresividad)',
            'Doberman(Perro padre)',
          ],
          correctIndexes: [0, 1],
          explain: 'Solo esos dos. El que se agrega explícitamente en la versión corregida es el constructor por default de Perro, no de Doberman.',
        },
        {
          id: 'ms2-30-3',
          q: '¿Qué afirmaciones sobre la sobreescritura son falsas?',
          options: [
            'Permite alterar el comportamiento heredado',
            'Requiere respetar la cantidad de parámetros',
            'Requiere respetar el tipo de los parámetros',
            'Requiere respetar el orden de los parámetros',
            'Permite reutilizar lo heredado mediante super',
          ],
          correctIndexes: [],
          explain: 'Las cinco son correctas: se puede pisar el método y aun así reutilizar lo heredado con super.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-30-1', front: '¿Cómo se muestra que el caniche ladra distinto?', back: 'Con sobreescritura: se reescribe ladrar() en Caniche devolviendo "WIF WIF".' },
      { id: 'fc2-30-2', front: '¿Qué condición hay que cumplir para pisar un método heredado?', back: 'Respetar tipo, orden y cantidad de parámetros.' },
      { id: 'fc2-30-3', front: '¿Qué devuelve el ladrar() del Dóberman?', back: '"GUAU GRRRR": super.ladrar() concatenado con " GRRRR".' },
      { id: 'fc2-30-4', front: '¿Qué pasa si se omite super en esa llamada?', back: 'El método se llama a sí mismo infinitamente: loop infinito.' },
      { id: 'fc2-30-5', front: '¿Se pueden encadenar llamadas a super?', back: 'No. En jerarquías de 3 o más niveles se hace siempre de a un nivel por clase.' },
      { id: 'fc2-30-6', front: '¿Por qué falla el constructor Doberman(int agresividad) sin arreglos?', back: 'Porque la llamada implícita a super() busca el constructor por default de Perro, que se perdió al declarar Perro(String nombre).' },
      { id: 'fc2-30-7', front: '¿Qué hay que existir antes de asignar la agresividad?', back: 'La "parte Perro" del Doberman, aquello que lo hace ser un perro.' },
      { id: 'fc2-30-8', front: '¿Cómo se corrige el ejemplo?', back: 'Declarando explícitamente el constructor por default public Perro() {} en la superclase.' },
    ],
  },
  '31': {
    quiz2: {
      tf: [
        { id: 'tf2-31-1', q: 'La sobrecarga puede aplicarse sin que haya una jerarquía de herencia de por medio.', a: true, explain: 'No necesariamente se da dentro de una jerarquía: puede usar métodos que ya están en la propia clase.' },
        { id: 'tf2-31-2', q: 'La sobrecarga de constructores sigue reglas distintas a la de métodos.', a: false, explain: 'Es solo un caso particular de la sobrecarga en general, que define las mismas reglas.' },
        { id: 'tf2-31-3', q: 'Cambiar el tipo de un parámetro al reescribir un método heredado produce una sobrecarga.', a: true, explain: 'El apunte lo comenta en PerroRobotV2: con long en vez de int "caigo" en una sobrecarga.' },
        { id: 'tf2-31-4', q: 'PerroRobot no puede extender Perro porque es una máquina y no un animal.', a: false, explain: 'Si hace al menos lo que hace un perro, respeta su interfaz pública y entonces es un Perro.' },
        { id: 'tf2-31-5', q: 'ladrar(int volumen) reutiliza el ladrar() sin parámetros mediante this.', a: true, explain: 'return this.ladrar() + " VOL:"+volumen;' },
      ],
      mc: [
        {
          id: 'mc2-31-1',
          q: '¿Qué hay que alterar para sobrecargar un método?',
          options: [
            'El nombre del método y su visibilidad',
            'El tipo, el orden y la cantidad de parámetros',
            'El tipo de retorno y el modificador static',
            'La clase de la que se extiende y su paquete',
          ],
          correctIndex: 1,
          explain: 'Son las mismas reglas que rigen la sobrecarga de constructores.',
        },
        {
          id: 'mc2-31-2',
          q: '¿Por qué el apunte prefiere ladrar(int volumen) antes que ladrarConVolumen()?',
          options: [
            'Porque los nombres de método demasiado largos no compilan en el lenguaje Java',
            'Porque así se evita usar la keyword super',
            'Porque semánticamente un perro ladra y ya, con una variante de argumento',
            'Porque un método por clase es el límite del lenguaje',
          ],
          correctIndex: 2,
          explain: 'Conceptual y semánticamente la operación sigue concordando con las acciones de un perro.',
        },
        {
          id: 'mc2-31-3',
          q: 'El ladrar() de PerroRobot devuelve el de Perro concatenado con...',
          options: [
            '" BIP BIP"',
            '" GRRRR"',
            '" WIF WIF"',
            '" VOL:"',
          ],
          correctIndex: 0,
          explain: 'return super.ladrar() + " BIP BIP";',
        },
        {
          id: 'mc2-31-4',
          q: 'En PerroRobotV2, ladrar(int volumen) respecto de PerroRobot...',
          options: [
            'Genera una sobrecarga por el tipo distinto',
            'Genera un conflicto de nombres irresoluble',
            'Pisa el método heredado, porque la firma coincide',
            'Es ignorado por tener el mismo nombre',
          ],
          correctIndex: 2,
          explain: 'El comentario del apunte dice "estoy pisando": misma cantidad, tipo y orden de parámetros.',
        },
        {
          id: 'mc2-31-5',
          q: '¿Qué relación hay entre la sobrecarga de constructores y la de métodos?',
          options: [
            'Los constructores no admiten sobrecarga en Java',
            'La de métodos solo aplica dentro de jerarquías',
            'Son mecanismos completamente independientes',
            'La de constructores es un caso particular de la general',
          ],
          correctIndex: 3,
          explain: 'La sobrecarga en general es la que define las reglas de tipo, orden y cantidad de parámetros.',
        },
      ],
      ms: [
        {
          id: 'ms2-31-1',
          q: '¿Qué métodos define PerroRobot en el ejemplo final del apunte?',
          options: [
            'ladrar()',
            'ladrar(int volumen)',
            'ladrar(long volumen)',
            'ladrarConVolumen(int volumen)',
            'jugar()',
          ],
          correctIndexes: [0, 1],
          explain: 'ladrar(long volumen) está en PerroRobotV2; ladrarConVolumen es justamente la opción que el apunte descarta.',
        },
        {
          id: 'ms2-31-2',
          q: '¿Qué es cierto de la sobreescritura frente a la sobrecarga?',
          options: [
            'La sobreescritura respeta tipo, orden y cantidad de parámetros',
            'La sobrecarga altera tipo, orden y cantidad de parámetros',
            'La sobreescritura pisa el método heredado',
            'Una sobreescritura fallida termina siendo una sobrecarga',
            'La sobrecarga exige siempre una relación de herencia',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La sobrecarga no necesariamente se da dentro de una jerarquía.',
        },
        {
          id: 'ms2-31-3',
          q: '¿Qué formas de reutilizar código presenta el apunte de herencia?',
          options: [
            'Heredar el comportamiento con extends',
            'Llamar a la superclase con super',
            'Sobrecargar métodos apoyándose en los existentes',
            'Copiar y pegar el método en cada subclase',
            'Declarar los atributos como públicos',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'Copiar y pegar es justamente lo que la herencia evita, y la visibilidad de atributos no reutiliza código.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-31-1', front: '¿La sobrecarga necesita herencia?', back: 'No necesariamente: puede usar métodos de la propia clase o métodos heredados.' },
      { id: 'fc2-31-2', front: 'Regla de la sobrecarga', back: 'Alterar tipo, orden y cantidad de parámetros.' },
      { id: 'fc2-31-3', front: 'Regla de la sobreescritura', back: 'Respetar tipo, orden y cantidad de parámetros. Si no, queda una simple sobrecarga.' },
      { id: 'fc2-31-4', front: '¿Por qué PerroRobot es un Perro?', back: 'Porque hace al menos lo que hace un perro: respeta su interfaz pública, aunque sea una máquina.' },
      { id: 'fc2-31-5', front: 'Ladrido de PerroRobot', back: 'super.ladrar() + " BIP BIP".' },
      { id: 'fc2-31-6', front: 'ladrar(int volumen) en PerroRobot', back: 'return this.ladrar() + " VOL:"+volumen; — reutiliza el ladrar sin parámetros.' },
      { id: 'fc2-31-7', front: 'PerroRobotV2: ladrar(long volumen)', back: 'No pisa nada: el tipo del parámetro es otro, así que "cae" en una sobrecarga.' },
      { id: 'fc2-31-8', front: '¿Qué es la sobrecarga de constructores?', back: 'Un caso particular de la sobrecarga en general, que es la que define las reglas.' },
    ],
  },
  '32': {
    quiz2: {
      tf: [
        { id: 'tf2-32-1', q: 'Un arreglo de float recién creado tiene 0.0 en cada posición.', a: true, explain: 'Los arreglos de primitivos se llenan con los valores por default del tipo.' },
        { id: 'tf2-32-2', q: 'La posición 4 de un arreglo es la cuarta posición contando desde el inicio.', a: false, explain: 'Al contar desde 0, la posición 4 es la quinta del arreglo.' },
        { id: 'tf2-32-3', q: 'El apunte recomienda declarar los arreglos como int[] enteros.', a: true, explain: 'Ambas sintaxis son válidas, pero la recomendada es la nro. 2 con los corchetes junto al tipo.' },
        { id: 'tf2-32-4', q: 'El tamaño de un arreglo se obtiene invocando enteros.length().', a: false, explain: 'length es un atributo, no un método: se escribe sin paréntesis.' },
        { id: 'tf2-32-5', q: 'El apunte menciona while y do...while como formas alternativas de recorrer un arreglo.', a: true, explain: 'Lo dice al final de la sección de recorrido.' },
      ],
      mc: [
        {
          id: 'mc2-32-1',
          q: '¿Qué contiene cada posición de un arreglo de tipo Referencia recién creado?',
          options: [
            'null',
            '0',
            'false',
            'Una instancia por default',
          ],
          correctIndex: 0,
          explain: 'En cada posición no va a haber nada, es decir, habrá un null.',
        },
        {
          id: 'mc2-32-2',
          q: 'Cuando un arreglo es de objetos, cada posición almacena...',
          options: [
            'El objeto completo copiado en esa celda',
            'El identificador textual del objeto',
            'Una referencia al objeto',
            'El valor por default de sus atributos',
          ],
          correctIndex: 2,
          explain: 'No guarda el valor dentro de la posición, sino una referencia al objeto.',
        },
        {
          id: 'mc2-32-3',
          q: '¿De qué tipo es el valor que arroja length y por qué?',
          options: [
            'Long, porque los arreglos pueden ser enormes',
            'Entero, porque el tamaño máximo de un arreglo es un entero',
            'Short, porque de esa forma se ahorra bastante memoria dentro de la JVM',
            'Double, porque admite tamaños fraccionarios',
          ],
          correctIndex: 1,
          explain: 'Es la justificación textual del apunte.',
        },
        {
          id: 'mc2-32-4',
          q: 'Recorrer un arreglo de primitivos comparado con uno de referencias...',
          options: [
            'Requiere un bucle do...while obligatorio',
            'Necesita chequear null en cada iteración',
            'Exige convertir cada posición antes de leerla',
            'Es exactamente igual, no cambia en nada',
          ],
          correctIndex: 3,
          explain: 'El apunte lo aclara: recorrer uno escalar o primitivo es igual que uno de referencia.',
        },
        {
          id: 'mc2-32-5',
          q: 'En "for(int pos = 0; pos < tamanio; pos++)" sobre un arreglo de 10, ¿qué posiciones se visitan?',
          options: [
            'De la 0 a la 9',
            'De la 1 a la 10',
            'De la 0 a la 10',
            'De la 1 a la 9',
          ],
          correctIndex: 0,
          explain: 'En un arreglo de 10 posiciones estas se enumeran del 0 al 9.',
        },
      ],
      ms: [
        {
          id: 'ms2-32-1',
          q: '¿Qué valores por default menciona explícitamente el apunte para arreglos de primitivos?',
          options: [
            '0 para los enteros',
            'false para los boolean',
            '0.0 para los float',
            '"" para los String',
            "' ' para los char",
          ],
          correctIndexes: [0, 1, 2],
          explain: 'String no es un tipo primitivo y el char no aparece en esa enumeración.',
        },
        {
          id: 'ms2-32-2',
          q: '¿Qué operaciones sobre arreglos aparecen en el apunte?',
          options: [
            'Escribir por posición: enteros[3] = 158;',
            'Leer por posición: int valor = enteros[4];',
            'Obtener el tamaño: enteros.length',
            'Ordenar el arreglo con un método propio',
            'Redimensionar el arreglo en ejecución',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'Ordenar y redimensionar no se tratan en este apunte.',
        },
        {
          id: 'ms2-32-3',
          q: '¿Qué afirmaciones sobre la declaración de arreglos son incorrectas?',
          options: [
            'int enteros[] = new int[10]; es válida',
            'int[] enteros = new int[10]; es válida',
            'La forma recomendada es la segunda',
            'Ambas sintaxis producen un arreglo de 10 posiciones',
            'Las posiciones se enumeran del 0 al 9',
          ],
          correctIndexes: [],
          explain: 'Las cinco afirmaciones coinciden con lo que dice el apunte.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-32-1', front: '¿Con qué se llena un arreglo de enteros al crearlo?', back: 'Con 0 en cada posición, el valor por default de un entero.' },
      { id: 'fc2-32-2', front: '¿Y un arreglo de Autos?', back: 'Con null: en cada posición no hay nada.' },
      { id: 'fc2-32-3', front: '¿Qué guarda realmente un arreglo de objetos?', back: 'Referencias a los objetos, no los valores dentro de la posición.' },
      { id: 'fc2-32-4', front: '¿Cómo se escribe y se lee una posición?', back: 'enteros[3] = 158; para escribir; int valor = enteros[4]; para leer.' },
      { id: 'fc2-32-5', front: '¿Cuál es la forma recomendada de declarar un arreglo?', back: 'int[] enteros = new int[10]; (la variante int enteros[] también es válida).' },
      { id: 'fc2-32-6', front: '¿length es método o atributo?', back: 'Atributo. Se usa sin paréntesis y devuelve un entero.' },
      { id: 'fc2-32-7', front: '¿Cómo se imprime un arreglo completo?', back: 'for(int pos = 0; pos < tamanio; pos++) { System.out.println(enteros[pos]); }' },
      { id: 'fc2-32-8', front: '¿Qué otras estructuras sirven para recorrer un arreglo?', back: 'while(…) {…} y do {…} while(…), además del for.' },
    ],
  },
  '33': {
    quiz2: {
      tf: [
        { id: 'tf2-33-1', q: 'Asignar un int a un long no requiere cast porque el destino es más grande.', a: true, explain: '32 bits entran sin problema en 64 bits: es la conversión más sencilla y sin pérdida.' },
        { id: 'tf2-33-2', q: 'Pasar de double a int es una conversión implícita y segura.', a: false, explain: 'Ir a un contenedor más chico requiere cast explícito y puede perder información.' },
        { id: 'tf2-33-3', q: 'El valor resultante de convertir a char corresponde a un carácter UNICODE.', a: true, explain: 'El apunte lo indica al explicar el caso de los caracteres.' },
        { id: 'tf2-33-4', q: 'La promoción numérica se aplica al declarar variables, no al operar con ellas.', a: false, explain: 'Son reglas que se aplican al momento de hacer operaciones, para usar un tipo en común.' },
        { id: 'tf2-33-5', q: 'El apunte cita la especificación de Java 13 para las reglas de promoción.', a: true, explain: 'Cap. 5, sección 6, punto 2 de la especificación del lenguaje.' },
      ],
      mc: [
        {
          id: 'mc2-33-1',
          q: 'Al asignar el int 241 a un double, el resultado es...',
          options: [
            '241.0, con la parte decimal en ceros',
            '241, sin cambios de representación',
            '2410, por corrimiento de bits',
            'Un error de compilación por falta de cast',
          ],
          correctIndex: 0,
          explain: 'La parte decimal se llena con ceros para completar el valor.',
        },
        {
          id: 'mc2-33-2',
          q: 'En el ejemplo del apunte, castear el long 8223372036854775807l a int da...',
          options: [
            '8223372036',
            '2147483647',
            '1486618623',
            '-91',
          ],
          correctIndex: 2,
          explain: 'Es el valor concreto que muestra el apunte como pérdida de información.',
        },
        {
          id: 'mc2-33-3',
          q: '¿Cuál es la primera regla de promoción numérica que se evalúa?',
          options: [
            'Si alguno de los operandos es long',
            'Si alguno de los operandos es float',
            'Si ambos operandos son int',
            'Si alguno de los operandos es double',
          ],
          correctIndex: 3,
          explain: 'El orden es double, float, long y, en su defecto, int.',
        },
        {
          id: 'mc2-33-4',
          q: '¿Qué recomienda el apunte para convertir de byte a char sin perder información?',
          options: [
            'Pasar primero por un int y después a char',
            'Castear directamente con (char) sobre el byte',
            'Usar un long como paso intermedio',
            'Convertir el byte a String y luego a char',
          ],
          correctIndex: 0,
          explain: 'Así se evitan los problemas con los bits de signo descriptos en el ejemplo.',
        },
        {
          id: 'mc2-33-5',
          q: 'La suma de dos byte debe castearse porque...',
          options: [
            'El operador + no está definido para byte',
            'Por promoción numérica ambos se consideran int',
            'El resultado siempre supera el rango del byte',
            'Java prohíbe operar con tipos de 8 bits',
          ],
          correctIndex: 1,
          explain: 'De lo contrario ambos operadores son considerados int, así que hay que castear el resultado a byte.',
        },
      ],
      ms: [
        {
          id: 'ms2-33-1',
          q: '¿Qué reglas de promoción numérica enumera el apunte?',
          options: [
            'double convierte al otro operando a double',
            'float convierte al otro operando a float',
            'long convierte al otro operando a long',
            'byte convierte al otro operando a byte',
            'En caso contrario, ambos se consideran int',
          ],
          correctIndexes: [0, 1, 2, 4],
          explain: 'No existe una regla que promueva a byte: byte y short caen en la regla del int.',
        },
        {
          id: 'ms2-33-2',
          q: '¿Qué afirmaciones sobre el ejemplo del número 165 son correctas?',
          options: [
            'Al pasarlo a byte vale -91',
            'Su representación binaria coincide con la del -91',
            'Lo que cambia es la interpretación del bit de signo',
            'Convertido a char y luego a int puede dar 65445',
            'Convertido a byte pasa a valer 0',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'Nunca vale 0: los 8 bits menos significativos se conservan y vuelve a dar -91.',
        },
        {
          id: 'ms2-33-3',
          q: '¿Cuáles de estas conversiones pueden perder información?',
          options: [
            'long a int',
            'int a byte',
            'int a long',
            'int a double',
            'char a int',
          ],
          correctIndexes: [0, 1],
          explain: 'Las otras tres van hacia contenedores más grandes, donde no hay pérdida.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-33-1', front: '¿Cuál es la conversión primitiva más sencilla?', back: 'La de un tipo "más chico" a uno "más grande": no hay pérdida de información y no requiere cast.' },
      { id: 'fc2-33-2', front: '¿Cuántos bits tienen int y long?', back: 'int 32 bits, long 64 bits.' },
      { id: 'fc2-33-3', front: '¿Qué pasa al ir a un contenedor más chico?', back: 'Puede haber pérdida de información según el tamaño del valor de origen; hace falta cast explícito.' },
      { id: 'fc2-33-4', front: '¿Por qué 165 pasado a byte da -91?', back: 'Porque la representación binaria es la misma y solo cambia la interpretación del bit de signo.' },
      { id: 'fc2-33-5', front: '¿Qué tipo de valor resulta de una conversión a char?', back: 'Un valor de carácter UNICODE.' },
      { id: 'fc2-33-6', front: 'Camino recomendado de byte a char', back: 'Pasar primero por int y después convertir a char.' },
      { id: 'fc2-33-7', front: 'Orden de las reglas de promoción numérica', back: 'double → float → long → int (de lo contrario, ambos operandos se consideran int).' },
      { id: 'fc2-33-8', front: '¿Cómo se suma correctamente dos byte?', back: 'byte resultado = (byte)(unByte + otroByte); porque la promoción los considera int.' },
    ],
  },
  '34': {
    quiz2: {
      tf: [
        { id: 'tf2-34-1', q: 'La conversión de subclase a superclase puede escribirse también de forma explícita.', a: true, explain: 'Persona x = e; es implícita, pero Persona y = (Persona)e2; también es válida.' },
        { id: 'tf2-34-2', q: 'Guardar un Empleado en una variable de tipo Persona da acceso a las operaciones del Empleado.', a: false, explain: 'El tipo de la variable manda: solo se accede a las características y operaciones de Persona.' },
        { id: 'tf2-34-3', q: 'Un downcast mal hecho se detecta durante la compilación del programa.', a: false, explain: 'El compilador analiza sintaxis; el error aparece en ejecución como ClassCastException.' },
        { id: 'tf2-34-4', q: 'El operador instanceof devuelve un valor booleano.', a: true, explain: 'Devuelve true si la variable guarda un objeto de esa clase, y false en caso contrario.' },
        { id: 'tf2-34-5', q: 'La línea "Persona p2 = new Ejecutivo();" es interpretada como correcta por el compilador.', a: true, explain: 'Por la estructura jerárquica descripta: hay un cast implícito hacia arriba.' },
      ],
      mc: [
        {
          id: 'mc2-34-1',
          q: '¿Qué jerarquía usa el apunte para explicar la conversión de referencias?',
          options: [
            'Persona → Empleado → Ejecutivo',
            'Ejecutivo → Empleado → Persona',
            'Empleado → Persona → Ejecutivo',
            'Ejecutivo → Persona → Empleado',
          ],
          correctIndex: 1,
          explain: 'Ejecutivo hereda de Empleado y Empleado hereda de Persona.',
        },
        {
          id: 'mc2-34-2',
          q: '¿Por qué "Ejecutivo eje = p;" con p de tipo Persona no compila?',
          options: [
            'Porque el compilador sabe que no toda persona es un ejecutivo',
            'Porque la variable p ya había sido asignada en una instrucción previa',
            'Porque Ejecutivo no hereda ningún atributo de Persona',
            'Porque falta invocar el constructor de Ejecutivo',
          ],
          correctIndex: 0,
          explain: 'Alguna persona puede serlo, pero no necesariamente todas: hace falta un downcast explícito.',
        },
        {
          id: 'mc2-34-3',
          q: '¿Cómo se le "promete" al compilador que una variable guarda una subclase?',
          options: [
            'Declarando la variable como final',
            'Anotando el método con una etiqueta especial',
            'Reasignando la variable dentro de un bucle de control previo al casteo',
            'Escribiendo un downcast explícito con (Subclase)',
          ],
          correctIndex: 3,
          explain: 'Ejecutivo eje2 = (Ejecutivo)p3; es la promesa que el compilador acepta.',
        },
        {
          id: 'mc2-34-4',
          q: 'El operador instanceof se compara en el apunte con...',
          options: [
            'Un método heredado de la clase Object',
            'Operadores como el + o el *',
            'Un bloque de control como el if',
            'Una anotación del compilador',
          ],
          correctIndex: 1,
          explain: 'El apunte remarca que no es un método, es un operador como el + o el *.',
        },
        {
          id: 'mc2-34-5',
          q: '¿Qué se gana escribiendo "if(p instanceof Ejecutivo)" antes del casteo?',
          options: [
            'Se evita un error durante la ejecución',
            'Se acelera el proceso de compilación',
            'Se convierte automáticamente el objeto',
            'Se agrega la subclase a la jerarquía',
          ],
          correctIndex: 0,
          explain: 'Siempre se puede castear, pero así se evita la ClassCastException.',
        },
      ],
      ms: [
        {
          id: 'ms2-34-1',
          q: '¿Qué es cierto sobre el upcasting?',
          options: [
            'Va de la subclase hacia la superclase',
            'Se hace de manera implícita',
            'Puede escribirse también de forma explícita',
            'Restringe el acceso a lo propio de la subclase',
            'Puede lanzar una ClassCastException',
          ],
          correctIndexes: [0, 1, 2, 3],
          explain: 'La ClassCastException es riesgo del downcasting, no del upcasting.',
        },
        {
          id: 'ms2-34-2',
          q: '¿Qué clases forman la jerarquía del apunte de conversión de referencias?',
          options: [
            'Persona',
            'Empleado',
            'Ejecutivo',
            'Profesor',
            'Gerente',
          ],
          correctIndexes: [0, 1, 2],
          explain: 'Profesor aparece en el apunte de herencia, no en este; Gerente no aparece.',
        },
        {
          id: 'ms2-34-3',
          q: '¿Qué afirmaciones sobre instanceof son falsas?',
          options: [
            'Es un operador y no un método',
            'Se usa como "miVariable instanceof MiClase"',
            'Devuelve true si la variable guarda un objeto de esa clase',
            'Devuelve false en caso contrario',
            'Permite chequear antes de hacer un downcast',
          ],
          correctIndexes: [],
          explain: 'Las cinco afirmaciones son correctas según el apunte.',
        },
      ],
    },
    flashcards2: [
      { id: 'fc2-34-1', front: '¿Qué hereda una sub-clase de su super-clase?', back: 'Sus atributos y operaciones.' },
      { id: 'fc2-34-2', front: '¿Cómo se hace la conversión hacia arriba?', back: 'De forma implícita: Persona x = e; También puede escribirse explícita: Persona y = (Persona)e2;' },
      { id: 'fc2-34-3', front: '¿Qué limitación tiene una variable declarada del tipo superior?', back: 'Solo da acceso a las características y operaciones de ese tipo, aunque adentro haya un objeto de la subclase.' },
      { id: 'fc2-34-4', front: '¿Qué es el downcasting?', back: 'La conversión de tipos "hacia abajo", de la superclase hacia la subclase, con cast explícito.' },
      { id: 'fc2-34-5', front: '¿Por qué el compilador rechaza "Ejecutivo eje = p;"?', back: 'Porque no necesariamente toda persona es un ejecutivo.' },
      { id: 'fc2-34-6', front: '¿Cuándo aparece la ClassCastException?', back: 'En tiempo de ejecución, cuando el downcast explícito "mintió" y el objeto no era de esa clase.' },
      { id: 'fc2-34-7', front: '¿Qué hace el compilador respecto de la ejecución?', back: 'Analiza la sintaxis del código, no lo ejecuta: lo que ocurre durante la ejecución es distinto.' },
      { id: 'fc2-34-8', front: 'Sintaxis de instanceof', back: 'miVariable instanceof MiClase; devuelve true o false. Se suele usar dentro de un if antes de castear.' },
    ],
  },
};
