/**
 * Materia: Álgebra Lineal.
 *
 * Unidad '2' (secciones 1-7): el apunte de cátedra "Ecuaciones diofánticas y
 * ecuaciones de congruencias" (UP, 0006_APU_192Q v1-1), transcripto con
 * criollo, quizzes y flashcards.
 *
 * Las fórmulas se escriben en LaTeX entre $...$ (inline) o $$...$$ (display).
 * Render por KaTeX (cargado en seccion.html). El apunte usa la notación
 * $(a : b)$ para el máximo común divisor y $a \equiv b\ (m)$ para la
 * congruencia módulo m; se respeta tal cual.
 */

export default {
  id: 'algebra-lineal',
  title: 'Álgebra Lineal',
  subtitle: 'Ecuaciones diofánticas y de congruencias — Apuntes',
  tagline: 'Hash code · Ecuaciones diofánticas · Tanteos y divisiones sucesivas · Solución general · Congruencia · Ecuaciones modulares',
  units: {
    '2': 'Ecuaciones diofánticas y ecuaciones de congruencias',
  },
  sections: [
    {
      id: '1',
      unit: '2',
      title: 'Hash code',
      criollo: 'Antes de meterse con las diofánticas, el apunte arranca con el hash code, que es la aplicación más concreta de todo esto. La idea es fácil: en vez de revisar una lista entera para encontrar algo, calculás un número a partir del objeto y ese número te dice directamente en qué caja está. Es como un índice instantáneo.',
      blocks: [
        { type: 'p', text: 'El <strong>código hash</strong> de un objeto permite que los algoritmos y las estructuras de datos pongan objetos en compartimientos, al igual que los tipos de letra en el caso de una impresora. La impresora coloca todos los tipos A en el compartimento para A y busca una A solo en ese compartimiento. Este sistema simple permite encontrar letras mucho más rápido que la búsqueda en un cajón sin clasificar.' },
        { type: 'p', text: 'Esa también es la idea de colecciones basadas en hash, como <code>HashMap</code> y <code>HashSet</code>. Un hashcode genera un número para cualquier objeto. Esto es lo que permite que los objetos se coloquen o recuperen rápidamente en una <code>Hashtable</code>.' },
        {
          type: 'h3',
          text: 'Ejemplo 2.1 — Las diez cajas',
          criollo: 'El ejemplo de los animalitos es la mejor forma de entenderlo. No buscás en todas las cajas: calculás la función y vas derecho a una sola.',
        },
        { type: 'p', text: 'Imaginemos que en una mesa hay diez cajas, cada una marcada con un número del 0 a 9. También hay varios objetos (animalitos de juguete) diferentes para almacenar en esas cajas. Necesitamos buscar un algoritmo que permita encontrar esos objetos lo más rápido posible.' },
        { type: 'p', text: '<strong>Resolución:</strong> lo que necesitamos es una forma de decidir instantáneamente en qué caja ponemos cada objeto. Funciona como un índice: para buscar el objeto gato, aplicamos la función hashcode y luego vamos directamente a esa caja para conseguirlo.' },
        { type: 'p', text: 'En el ejemplo, utilicemos una forma realmente simple de hacer esto: el código hash indica el número de letras que hay en el nombre del objeto en singular (por ejemplo, se utiliza el término “gato” y no el término “gatos”).' },
        {
          type: 'table',
          caption: 'La función hash del ejemplo: cantidad de letras del nombre en singular.',
          headers: ['Objeto', 'Letras', 'Caja'],
          rows: [
            ['gato', '4', '4'],
            ['perro', '5', '5'],
            ['ballena', '7', '7'],
            ['rinoceronte', '11', '1'],
          ],
        },
        { type: 'p', text: '¿Y el rinoceronte? Como tiene 11 letras y ninguna caja dice 11, vamos a cambiar nuestro algoritmo y haremos que los objetos de 11 letras vayan en la caja 1, los objetos de 12 letras en la caja 2, etc. Ese algoritmo se aplica para cualquier objeto.' },
        {
          type: 'h3',
          text: 'Colisiones: el código hash no es único',
          criollo: 'Que dos objetos caigan en la misma caja no rompe nada. Igual comparás contra dos o tres cosas en vez de contra la colección entera.',
        },
        { type: 'p', text: 'A veces una caja tiene más de un objeto en ella, pero aun así, si se está buscando un perro y en la caja hay perros, burros y quebrantahuesos, será más rápido comparar un perro con un burro y un quebrantahuesos que revisar todo el conjunto de animales (gatos, perros, elefantes, ballenas, etc.). Es decir, utilizar el código hash es mucho más ágil que realizar una búsqueda lineal que revise todas las cajas.' },
        { type: 'p', text: 'El código hash <strong>no necesariamente es único</strong>. Por ejemplo, si intenta poner su objeto con código de hash $218714508$ en una tabla de hashes con 10 cajas $0, \\dots, 9$, lo pondría en la casilla 8. Si se encontrara otro objeto con el mismo hashcode de $218714508$, ambos entrarían en la caja 8, como así también los objetos con códigos hash $8, 18, 28, \\dots$' },
        { type: 'p', text: 'Esta es la razón por la cual una <code>Hashtable</code> se puede construir especificando un entero (en una función de inicialización o constructor) que representa el número inicial de cajas. Si planea colocar muchos elementos en el <code>Hashtable</code>, podría considerar especificar un número mayor de cajas para reducir el número promedio de objetos por caja.' },
        {
          type: 'h3',
          text: 'Para qué le sirve al programador',
          criollo: 'El hash es de ida nomás: del objeto sacás el número, del número no volvés al objeto. Sirve como id de búsqueda, nada más.',
        },
        { type: 'p', text: 'El código hash en sí no es útil para el programador: si el objeto <code>Perro</code> se convierte en $291564382$ entonces no se puede convertir ese número de nuevo para obtener <code>Perro</code>. El beneficio para el programador es que el código hash se puede utilizar en una tabla hash para ser utilizado como un <strong>id de búsqueda</strong>, como un índice.' },
        { type: 'p', text: 'La tabla hash es como cualquier otra colección (en su mayor parte), un grupo de objetos y algún método para acceder a esos objetos. De lo contrario, el código hash no proporciona ninguna otra utilidad al programador, a excepción de algunas posibles situaciones nuevas y raras que pueden ocurrir.' },
        { type: 'callout', tone: 'criollo', text: 'La conexión con lo que viene: el hash de un objeto se calcula casi siempre como un resto de división ($\\text{hash} \\bmod n$ te da la caja). Ese "resto de dividir por $n$" es exactamente el concepto de <strong>congruencia módulo $n$</strong> que se define más adelante en la unidad.' },
      ],
      quiz: {
        tf: [
          { id: 'tf-1-1', q: 'El código hash de un objeto es siempre único: dos objetos distintos nunca comparten hashcode.', a: false, explain: 'El apunte aclara explícitamente que el código hash no necesariamente es único. Dos objetos con el mismo hashcode caen en la misma caja.' },
          { id: 'tf-1-2', q: 'Usar el código hash es más ágil que hacer una búsqueda lineal que revise todas las cajas.', a: true, explain: 'Esa es justamente la ventaja: se va directo a una caja en vez de recorrer todo el conjunto de objetos.' },
          { id: 'tf-1-3', q: 'A partir del código hash se puede reconstruir el objeto original.', a: false, explain: 'Si el objeto Perro se convierte en $291564382$, ese número no se puede convertir de nuevo para obtener Perro. El hash es de ida.' },
          { id: 'tf-1-4', q: 'En el ejemplo de las diez cajas, el objeto "ballena" va a la caja 7.', a: true, explain: 'El código hash del ejemplo es la cantidad de letras del nombre en singular: "ballena" tiene 7 letras.' },
          { id: 'tf-1-5', q: 'Una Hashtable se puede construir especificando un entero que representa el número inicial de cajas.', a: true, explain: 'Es lo que permite reducir el número promedio de objetos por caja cuando se planea guardar muchos elementos.' },
        ],
        mc: [
          {
            id: 'mc-1-1',
            q: 'En el ejemplo del apunte, ¿a qué caja va el rinoceronte y por qué?',
            options: [
              'A la caja 1, porque se cambia el algoritmo para que los objetos de 11 letras vayan a la caja 1',
              'A la caja 11, porque tiene 11 letras',
              'A ninguna, porque el algoritmo no lo contempla',
              'A la caja 0, porque es la caja de descarte',
            ],
            correctIndex: 0,
            explain: 'Como no hay caja 11, se cambia el algoritmo: los de 11 letras van a la caja 1, los de 12 a la caja 2, etc.',
          },
          {
            id: 'mc-1-2',
            q: 'Un objeto con hashcode $218714508$ en una tabla de 10 cajas ($0, \\dots, 9$) va a la casilla:',
            options: ['8', '5', '0', '9'],
            correctIndex: 0,
            explain: 'El apunte lo ubica en la casilla 8. Ahí caen también los objetos con hash $8, 18, 28, \\dots$',
          },
          {
            id: 'mc-1-3',
            q: '¿Cuál es el beneficio real del código hash para el programador, según el apunte?',
            options: [
              'Servir como id de búsqueda dentro de una tabla hash, como un índice',
              'Comprimir el objeto para ocupar menos memoria',
              'Encriptar el objeto para que no se pueda leer',
              'Ordenar alfabéticamente la colección',
            ],
            correctIndex: 0,
            explain: 'El código hash en sí no le sirve al programador; el beneficio es usarlo como id de búsqueda dentro de la tabla hash.',
          },
          {
            id: 'mc-1-4',
            q: 'Si en una caja hay perros, burros y quebrantahuesos y buscamos un perro, ¿qué pasa?',
            options: [
              'Igual es más rápido: se compara contra esos tres y no contra toda la colección',
              'El hash falla y hay que recalcularlo',
              'Hay que recorrer todas las cajas de nuevo',
              'La tabla se reconstruye automáticamente',
            ],
            correctIndex: 0,
            explain: 'Aunque haya colisiones, comparar contra los objetos de una sola caja sigue siendo mucho más rápido que la búsqueda lineal completa.',
          },
        ],
        ms: [
          {
            id: 'ms-1-1',
            q: '¿Cuáles de estas afirmaciones sobre el código hash aparecen en el apunte?',
            options: [
              'Genera un número para cualquier objeto',
              'No necesariamente es único',
              'Permite colocar o recuperar objetos rápidamente en una Hashtable',
              'Se puede invertir para recuperar el objeto original',
              'Ordena los objetos de menor a mayor',
            ],
            correctIndexes: [0, 1, 2],
            explain: 'El hash no se puede invertir ni ordena nada: solo asigna un número que funciona como índice de caja.',
          },
          {
            id: 'ms-1-2',
            q: 'Según el ejemplo de las diez cajas, ¿qué asignaciones son correctas con el algoritmo original (cantidad de letras)?',
            options: [
              'gato → caja 4',
              'perro → caja 5',
              'ballena → caja 7',
              'gatos → caja 5',
              'elefante → caja 3',
            ],
            correctIndexes: [0, 1, 2],
            explain: 'El nombre se toma en singular ("gato", no "gatos"), así que la cuarta no aplica. "elefante" tiene 8 letras, no 3.',
          },
          {
            id: 'ms-1-3',
            q: '¿Qué colecciones o estructuras menciona el apunte como basadas en hash?',
            options: [
              'HashMap',
              'HashSet',
              'Hashtable',
              'ArrayList',
              'LinkedList',
            ],
            correctIndexes: [0, 1, 2],
            explain: 'El apunte nombra HashMap, HashSet y Hashtable. ArrayList y LinkedList no aparecen.',
          },
        ],
      },
      flashcards: [
        { id: 'fc-1-1', front: 'Código hash', back: 'Número que se genera para cualquier objeto y permite colocarlo o recuperarlo rápidamente en una tabla hash, funcionando como índice de "caja".' },
        { id: 'fc-1-2', front: '¿El hash es único?', back: 'No. Dos objetos distintos pueden tener el mismo hashcode y caer en la misma caja; también caen juntos los hash $8, 18, 28, \\dots$ en una tabla de 10 cajas.' },
        { id: 'fc-1-3', front: '¿Se puede invertir el hash?', back: 'No. Si Perro se convierte en $291564382$, ese número no se puede convertir de nuevo para obtener Perro.' },
        { id: 'fc-1-4', front: 'Ventaja frente a la búsqueda lineal', back: 'Se va directo a una sola caja en vez de revisar todo el conjunto de objetos, así que es mucho más ágil.' },
        { id: 'fc-1-5', front: 'Función hash del Ejemplo 2.1', back: 'La cantidad de letras del nombre del objeto en singular: gato → 4, perro → 5, ballena → 7.' },
        { id: 'fc-1-6', front: 'Colisión en una caja', back: 'Varios objetos comparten caja. Igual conviene: se compara solo contra los de esa caja y no contra la colección completa.' },
        { id: 'fc-1-7', front: '¿Para qué sirve el entero del constructor de una Hashtable?', back: 'Representa el número inicial de cajas. Con muchos elementos conviene un número mayor, para bajar el promedio de objetos por caja.' },
        { id: 'fc-1-8', front: 'Analogía de la impresora', back: 'La impresora pone todos los tipos A en el compartimento de A y busca una A solo ahí; es más rápido que buscar en un cajón sin clasificar.' },
      ],
    },
    {
      id: '2',
      unit: '2',
      title: 'Ecuaciones diofánticas',
      criollo: 'Una ecuación diofántica es una ecuación común y silvestre — $ax + by = c$ — pero con una restricción: las soluciones tienen que ser números <strong>enteros</strong>. Y eso cambia todo, porque ahora puede no haber ninguna solución. El teorema 2.1 te da el criterio para saber de entrada si vale la pena buscarlas o no.',
      blocks: [
        { type: 'p', text: 'Empezamos con una definición.' },
        { type: 'p', text: '<strong>Definición:</strong> se llama <strong>ecuación diofántica</strong> a una ecuación del tipo' },
        { type: 'math', latex: 'ax + by = c \\qquad a, b, c \\in \\mathbb{Z} \\qquad (2.1)', display: true },
        { type: 'p', text: 'Buscaremos las llamadas <strong>soluciones diofánticas</strong>, que son los valores de $x_0$ e $y_0 \\in \\mathbb{Z}$ que verifican la ecuación 2.1.' },
        {
          type: 'h3',
          text: 'Teorema 2.1 — Condición de existencia',
          criollo: 'Este es el filtro de entrada. Sacás el máximo común divisor entre $a$ y $b$; si ese número divide a $c$, hay solución. Si no divide, no perdés el tiempo: no existe ninguna.',
        },
        { type: 'p', text: '<strong>Teorema 2.1.</strong> La ecuación $ax + by = c$ admite solución diofántica si y solo si $(a : b) \\mid c$.' },
        { type: 'callout', tone: 'info', text: 'Notación del apunte: $(a : b)$ es el <strong>máximo común divisor</strong> entre $a$ y $b$, y la barra $\\mid$ se lee "divide a". Entonces $(a : b) \\mid c$ significa "el mcd entre $a$ y $b$ divide a $c$".' },
        {
          type: 'h3',
          text: 'Ejemplo — Verificar que 110x − 97y = 1042 admite solución',
          criollo: 'Para sacar el mcd se usa el algoritmo de Euclides: dividís, te quedás con el resto, volvés a dividir, y así hasta que el resto da cero. El último resto no nulo es el mcd.',
        },
        { type: 'p', text: 'Veamos cómo la siguiente ecuación diofántica admite solución:' },
        { type: 'math', latex: '110x - 97y = 1042', display: true },
        { type: 'p', text: 'Como enuncia el teorema 2.1, necesitamos verificar que $(110 : 97) \\mid 1042$. Usando el <strong>algoritmo de Euclides</strong>, calculamos el máximo común divisor entre 110 y 97.' },
        { type: 'math', latex: '\\begin{aligned} 110 &= 1 \\cdot 97 + 13 \\\\ 97 &= 7 \\cdot 13 + 6 \\\\ 13 &= 2 \\cdot 6 + 1 \\\\ 6 &= 6 \\cdot 1 + 0 \\end{aligned}', display: true },
        { type: 'p', text: 'Entonces 1 es el máximo común divisor entre 110 y 97, y 1 divide obviamente a 1042. Podemos afirmar que la ecuación diofántica <strong>admite al menos una solución</strong>.' },
        { type: 'callout', tone: 'criollo', text: 'Ojo con el "al menos una": el teorema te asegura que existe solución, pero no te la da ni te dice cuántas hay. Encontrar una es el tema de la sección que sigue, y contarlas todas es el de la solución general.' },
      ],
      quiz: {
        tf: [
          { id: 'tf-2-1', q: 'En una ecuación diofántica $ax + by = c$ se busca cualquier par de valores reales que la verifiquen.', a: false, explain: 'Se buscan las soluciones diofánticas: valores $x_0$ e $y_0$ que pertenecen a $\\mathbb{Z}$, es decir, enteros.' },
          { id: 'tf-2-2', q: 'Toda ecuación de la forma $ax + by = c$ con $a, b, c \\in \\mathbb{Z}$ admite solución diofántica.', a: false, explain: 'Solo si $(a : b) \\mid c$. Esa es la condición del teorema 2.1, y es un si y solo si.' },
          { id: 'tf-2-3', q: 'Aplicando el algoritmo de Euclides a 110 y 97 se obtiene que $(110 : 97) = 1$.', a: true, explain: 'Las divisiones sucesivas dan $110 = 1 \\cdot 97 + 13$, $97 = 7 \\cdot 13 + 6$, $13 = 2 \\cdot 6 + 1$ y $6 = 6 \\cdot 1 + 0$: el último resto no nulo es 1.' },
          { id: 'tf-2-4', q: 'Verificada la condición del teorema 2.1, ya se conoce el valor de la solución diofántica.', a: false, explain: 'El teorema solo garantiza que existe al menos una solución. Para hallarla hacen falta los métodos de resolución.' },
          { id: 'tf-2-5', q: 'En la notación del apunte, $(a : b)$ representa el máximo común divisor entre $a$ y $b$.', a: true, explain: 'Es la notación que usa todo el apunte, tanto en el teorema 2.1 como en las proposiciones sobre ecuaciones modulares.' },
        ],
        mc: [
          {
            id: 'mc-2-1',
            q: '¿Cuál es la definición de ecuación diofántica que da el apunte?',
            options: [
              'Una ecuación del tipo $ax + by = c$ con $a, b, c \\in \\mathbb{Z}$',
              'Una ecuación del tipo $ax + by = c$ con $a, b, c \\in \\mathbb{R}$',
              'Cualquier ecuación cuya solución sea un número primo',
              'Una ecuación de segundo grado con coeficientes enteros',
            ],
            correctIndex: 0,
            explain: 'Es la ecuación 2.1 del apunte: $ax + by = c$ con los tres coeficientes enteros.',
          },
          {
            id: 'mc-2-2',
            q: 'La ecuación $ax + by = c$ admite solución diofántica si y solo si:',
            options: [
              '$(a : b) \\mid c$',
              '$c \\mid (a : b)$',
              '$a \\mid c$ y $b \\mid c$',
              '$(a : b) = 1$',
            ],
            correctIndex: 0,
            explain: 'Es el teorema 2.1: el máximo común divisor entre $a$ y $b$ tiene que dividir a $c$.',
          },
          {
            id: 'mc-2-3',
            q: 'En el ejemplo $110x - 97y = 1042$, ¿por qué se concluye que hay solución?',
            options: [
              'Porque $(110 : 97) = 1$ y 1 divide a 1042',
              'Porque 1042 es par',
              'Porque 110 y 97 son ambos positivos',
              'Porque 97 es primo',
            ],
            correctIndex: 0,
            explain: 'Se calcula el mcd con Euclides, da 1, y 1 divide a cualquier entero, así que se cumple la condición del teorema.',
          },
          {
            id: 'mc-2-4',
            q: '¿Qué se obtiene con el algoritmo de Euclides en este contexto?',
            options: [
              'El máximo común divisor entre los coeficientes $a$ y $b$',
              'La solución general de la ecuación',
              'El resto de dividir $c$ por $a$',
              'El valor de $x_0$',
            ],
            correctIndex: 0,
            explain: 'Se usa para calcular $(a : b)$ y poder aplicar el teorema 2.1.',
          },
        ],
        ms: [
          {
            id: 'ms-2-1',
            q: '¿Qué elementos aparecen en la definición de ecuación diofántica (2.1)?',
            options: [
              'La forma $ax + by = c$',
              'La condición $a, b, c \\in \\mathbb{Z}$',
              'Las soluciones $x_0, y_0 \\in \\mathbb{Z}$',
              'La condición de que $a$ y $b$ sean coprimos',
              'La condición de que $c$ sea primo',
            ],
            correctIndexes: [0, 1, 2],
            explain: 'La definición no exige que $a$ y $b$ sean coprimos ni que $c$ sea primo: eso se convierte en la condición $(a:b) \\mid c$ del teorema.',
          },
          {
            id: 'ms-2-2',
            q: '¿Cuáles de estas divisiones forman parte del algoritmo de Euclides aplicado a 110 y 97 en el apunte?',
            options: [
              '$110 = 1 \\cdot 97 + 13$',
              '$97 = 7 \\cdot 13 + 6$',
              '$13 = 2 \\cdot 6 + 1$',
              '$6 = 6 \\cdot 1 + 0$',
              '$1042 = 97 \\cdot 10 + 72$',
            ],
            correctIndexes: [0, 1, 2, 3],
            explain: 'La división de 1042 por 97 aparece más adelante, en el método de las divisiones sucesivas, no en el cálculo del mcd.',
          },
        ],
      },
      flashcards: [
        { id: 'fc-2-1', front: 'Ecuación diofántica', back: 'Ecuación del tipo $ax + by = c$ con $a, b, c \\in \\mathbb{Z}$ (ecuación 2.1 del apunte).' },
        { id: 'fc-2-2', front: 'Solución diofántica', back: 'Los valores $x_0$ e $y_0 \\in \\mathbb{Z}$ que verifican la ecuación $ax + by = c$.' },
        { id: 'fc-2-3', front: 'Teorema 2.1', back: 'La ecuación $ax + by = c$ admite solución diofántica <strong>si y solo si</strong> $(a : b) \\mid c$.' },
        { id: 'fc-2-4', front: 'Notación $(a : b)$', back: 'El máximo común divisor entre $a$ y $b$.' },
        { id: 'fc-2-5', front: '¿Cómo se calcula $(a : b)$?', back: 'Con el algoritmo de Euclides: divisiones sucesivas quedándose con el resto hasta llegar a resto 0.' },
        { id: 'fc-2-6', front: 'Euclides con 110 y 97', back: '$110 = 1 \\cdot 97 + 13$; $97 = 7 \\cdot 13 + 6$; $13 = 2 \\cdot 6 + 1$; $6 = 6 \\cdot 1 + 0$. Entonces $(110 : 97) = 1$.' },
        { id: 'fc-2-7', front: '¿Por qué $110x - 97y = 1042$ tiene solución?', back: 'Porque $(110 : 97) = 1$ y $1 \\mid 1042$, así que se cumple el teorema 2.1.' },
      ],
    },
    {
      id: '3',
      unit: '2',
      title: 'Método de resolución de las ecuaciones diofánticas',
      criollo: 'Ya sabés si hay solución; ahora hay que encontrarla. El apunte da dos caminos: el <strong>tanteo</strong> (despejás y probás valores hasta que dé entero — sirve cuando los números son chicos) y las <strong>divisiones sucesivas</strong> (vas achicando los coeficientes con el algoritmo de la división hasta que quede una ecuación fácil, y después volvés para atrás).',
      blocks: [
        { type: 'p', text: 'Ahora veamos cómo se encuentran las soluciones de una ecuación diofántica.' },
        {
          type: 'h3',
          text: 'Método de los tanteos',
          criollo: 'Despejás la incógnita, le vas dando valores enteros a la otra y mirás cuál te da resultado entero. Como los restos se repiten en ciclo, con probar unos pocos valores alcanza.',
        },
        { type: 'p', text: '<strong>Ejemplo 1.</strong> Buscar una solución de la siguiente ecuación diofántica: $5x + 3y = 8$.' },
        { type: 'p', text: 'Por 2.1 sabemos que la ecuación admite una solución si $(5 : 3) \\mid 8$. Como $(5 : 3) = 1 \\rightarrow 1 \\mid 8$, existe solución.' },
        { type: 'p', text: 'Para calcular la solución despejamos $y$:' },
        { type: 'math', latex: 'y = \\frac{8 - 5x}{3}', display: true },
        { type: 'p', text: 'La solución debe ser un entero menor que 3.' },
        { type: 'math', latex: '\\begin{aligned} x &= 0 & y &= \\tfrac{8}{3} \\\\ x &= 1 & y &= \\tfrac{3}{3} = 1 \\\\ x &= 2 & y &= -\\tfrac{2}{3} \\end{aligned}', display: true },
        { type: 'p', text: '$(x_0, y_0) = (1, 1)$ es una solución diofántica.' },
        { type: 'p', text: '<strong>Ejemplo 2.</strong> Buscar una solución de la siguiente ecuación diofántica: $5x - 8y = 2$.' },
        { type: 'p', text: 'Como $(5 : -8) = 1$ y $1 \\mid 2$, existe una solución. Despejando $x$ se obtiene' },
        { type: 'math', latex: 'x = \\frac{2 + 8y}{5}', display: true },
        { type: 'p', text: 'Dando a $y$ los valores menores que 5, debe haber una solución entera.' },
        { type: 'math', latex: '\\begin{aligned} y &= 0 & x &= \\tfrac{2}{5} \\\\ y &= 1 & x &= \\tfrac{10}{5} \\\\ y &= 2 & x &= \\tfrac{18}{5} \\\\ y &= 3 & x &= \\tfrac{26}{5} \\\\ y &= 4 & x &= \\tfrac{34}{5} \\end{aligned}', display: true },
        { type: 'p', text: 'La solución diofántica es $(x_0, y_0) = (2, 1)$.' },
        {
          type: 'h3',
          text: 'Método de las divisiones sucesivas',
          criollo: 'La gracia de este método es que cada paso te deja una ecuación diofántica con coeficientes más chicos que la anterior. Repetís hasta que la podés resolver de cabeza, y después deshacés los reemplazos para volver a las incógnitas originales.',
        },
        { type: 'p', text: 'Supongamos que en la ecuación general 2.1 se tiene que $a < b$ y además ambos son positivos, o sea $a, b \\in \\mathbb{Z}^{+}$. Despejamos la incógnita que tiene el coeficiente de menor valor absoluto:' },
        { type: 'math', latex: 'x = \\frac{c - by}{a}', display: true },
        { type: 'p', text: 'Dividiendo $b$ por $a$ obtenemos (por el teorema 1.1) que $b = a \\cdot q_1 + r_1$, con $r_1 < a$. Y reemplazando:' },
        { type: 'math', latex: '\\begin{aligned} x &= \\frac{c}{a} - \\frac{a \\cdot q_1 + r_1}{a}\\,y \\\\ &= \\frac{c}{a} - \\frac{a}{a}q_1 y - \\frac{r_1}{a}y \\\\ &= -q_1 y + \\frac{c - r_1 y}{a} \\end{aligned}', display: true },
        { type: 'p', text: 'Entonces $x$ es entero $\\Leftrightarrow \\dfrac{c - r_1 y}{a}$ es entero. Llamaremos' },
        { type: 'math', latex: 'z = \\frac{c - r_1 y}{a} \\quad \\text{es decir} \\quad r_1 y + a z = c', display: true },
        { type: 'p', text: 'Esta ecuación diofántica tiene coeficientes menores a la anterior. Repetir el proceso si es necesario.' },
        { type: 'p', text: '<strong>Ejemplo 3.</strong> Buscar una solución de la siguiente ecuación diofántica: $27x + 83y = 17$.' },
        { type: 'p', text: 'Por 2.1 sabemos que la ecuación admite una solución si y solo si $(27 : 83) \\mid 17$. Como $(27 : 83) = 1 \\rightarrow 1 \\mid 17$, existe solución. Despejamos $x$:' },
        { type: 'math', latex: 'x = \\frac{17 - 83y}{27}', display: true },
        { type: 'p', text: 'Dividiendo 83 por 27, obtenemos que $83 = 27 \\cdot 3 + 2$, entonces' },
        { type: 'math', latex: '\\begin{aligned} x &= \\frac{17 - 83y}{27} \\\\ &= \\frac{17}{27} - \\frac{(27 \\cdot 3 + 2)y}{27} \\\\ &= -3y + \\frac{17 - 2y}{27} \\end{aligned}', display: true },
        { type: 'p', text: 'Llamaremos $z = \\dfrac{17 - 2y}{27}$; la nueva ecuación diofántica es $27z + 2y = 17$. Despejando $y$ obtenemos $y = \\dfrac{17 - 27z}{2}$:' },
        { type: 'math', latex: '\\begin{aligned} z &= 0 & y &= \\tfrac{17}{2} \\\\ z &= 1 & y &= \\tfrac{-10}{2} \\end{aligned}', display: true },
        { type: 'p', text: '$(z_0, y_0) = (1, -5)$ es una solución diofántica. Eso significa que $(x_0, y_0) = (16, -5)$ es una solución diofántica de la ecuación inicial.' },
        { type: 'p', text: '<strong>Ejemplo 4.</strong> Buscamos una solución de $110x - 97y = 1042$. Despejamos $y$:' },
        { type: 'math', latex: 'y = \\frac{-1042 + 110x}{97}', display: true },
        { type: 'p', text: 'Dividiendo 110 (y $-1042$) por 97, obtenemos que $110 = 97 + 13$ (y $1042 = 97 \\cdot 10 + 72$). Entonces' },
        { type: 'math', latex: '\\begin{aligned} y &= \\frac{-1042 + 110x}{97} \\\\ &= \\frac{-(97 \\cdot 10 + 72)}{97} + \\frac{(97 + 13)x}{97} \\\\ &= -10 + x + \\frac{-72 + 13x}{97} \\end{aligned}', display: true },
        { type: 'p', text: 'Llamaremos $z = \\dfrac{-72 + 13x}{97}$; la nueva ecuación diofántica es $13x - 97z = 72$. Despejando $x = \\dfrac{97z + 72}{13}$ y dividiendo 97 (y 72) por 13 obtenemos que $97 = 13 \\cdot 7 + 6$ (y $72 = 13 \\cdot 5 + 7$), por lo que' },
        { type: 'math', latex: '\\begin{aligned} x &= \\frac{97z + 72}{13} \\\\ &= \\frac{(13 \\cdot 7 + 6)z + (13 \\cdot 5 + 7)}{13} \\\\ &= 7z + 5 + \\frac{6z + 7}{13} \\end{aligned}', display: true },
        { type: 'p', text: 'Llamaremos $w = \\dfrac{6z + 7}{13}$; la nueva ecuación diofántica es $13w - 6z = 7$. Despejando $z = \\dfrac{13w - 7}{6}$, ahora podemos calcular 6 posibles soluciones:' },
        { type: 'math', latex: '\\begin{aligned} w &= 0 & z &= \\tfrac{-7}{6} \\\\ w &= 1 & z &= \\tfrac{6}{6} \\\\ w &= 2 & z &= \\tfrac{19}{6} \\\\ w &= 3 & z &= \\tfrac{16}{3} \\\\ w &= 4 & z &= \\tfrac{15}{2} \\\\ w &= 5 & z &= \\tfrac{29}{3} \\end{aligned}', display: true },
        { type: 'p', text: '$(w_0, z_0) = (1, 1)$ es una solución diofántica. Eso significa que $(x_0, y_0) = (13, 4)$ es una solución diofántica de la ecuación inicial.' },
        { type: 'callout', tone: 'criollo', text: 'Ojo al piojo con el apunte: en los ejemplos 3 y 4 las letras se le mezclan al escribirlas (aparece una $y$ donde va una $x$ y la variable nueva a veces se llama $y$ en vez de $z$). Acá se respetó el desarrollo pero con las letras consistentes. Si querés chequear, reemplazá: $27 \\cdot 16 + 83 \\cdot (-5) = 17$ y $110 \\cdot 13 - 97 \\cdot 4 = 1042$. Cierran.' },
      ],
      quiz: {
        tf: [
          { id: 'tf-3-1', q: 'En el método de las divisiones sucesivas se despeja la incógnita cuyo coeficiente tiene mayor valor absoluto.', a: false, explain: 'Se despeja la que tiene el coeficiente de <strong>menor</strong> valor absoluto.' },
          { id: 'tf-3-2', q: 'Cada paso del método de divisiones sucesivas produce una ecuación diofántica con coeficientes menores que la anterior.', a: true, explain: 'Esa es la clave del método: $r_1 y + a z = c$ tiene coeficientes más chicos, y se repite el proceso si hace falta.' },
          { id: 'tf-3-3', q: 'En el Ejemplo 1 ($5x + 3y = 8$) la solución hallada es $(x_0, y_0) = (1, 1)$.', a: true, explain: 'Tanteando $x = 0, 1, 2$, el único que da $y$ entero es $x = 1$, con $y = 3/3 = 1$.' },
          { id: 'tf-3-4', q: 'En el Ejemplo 2 ($5x - 8y = 2$) hay que darle a $y$ valores menores que 5 para encontrar la solución entera.', a: true, explain: 'El apunte lo dice explícitamente: dando a $y$ los valores menores que 5 debe haber una solución entera; aparece en $y = 1$, con $x = 10/5 = 2$.' },
          { id: 'tf-3-5', q: 'En el Ejemplo 3 la solución final de $27x + 83y = 17$ es $(x_0, y_0) = (1, -5)$.', a: false, explain: '$(1, -5)$ es la solución de la ecuación auxiliar $(z_0, y_0)$. Al volver atrás, la solución de la ecuación inicial es $(x_0, y_0) = (16, -5)$.' },
        ],
        mc: [
          {
            id: 'mc-3-1',
            q: 'En el método de las divisiones sucesivas, tras dividir $b$ por $a$ y reemplazar, ¿qué nueva ecuación diofántica queda?',
            options: [
              '$r_1 y + a z = c$',
              '$a y + b z = c$',
              '$q_1 y + r_1 z = c$',
              '$a y + r_1 z = b$',
            ],
            correctIndex: 0,
            explain: 'Se llama $z = \\dfrac{c - r_1 y}{a}$, de donde $r_1 y + a z = c$, con coeficientes menores que los originales.',
          },
          {
            id: 'mc-3-2',
            q: 'En el Ejemplo 3 se divide 83 por 27. ¿Qué se obtiene?',
            options: [
              '$83 = 27 \\cdot 3 + 2$',
              '$83 = 27 \\cdot 2 + 29$',
              '$83 = 27 \\cdot 3 + 1$',
              '$83 = 27 \\cdot 4 - 25$',
            ],
            correctIndex: 0,
            explain: 'Ese resto 2 es el que permite escribir $x = -3y + \\dfrac{17 - 2y}{27}$ y armar la ecuación auxiliar.',
          },
          {
            id: 'mc-3-3',
            q: 'En el Ejemplo 4, la solución diofántica final de $110x - 97y = 1042$ es:',
            options: [
              '$(x_0, y_0) = (13, 4)$',
              '$(x_0, y_0) = (1, 1)$',
              '$(x_0, y_0) = (16, -5)$',
              '$(x_0, y_0) = (2, 1)$',
            ],
            correctIndex: 0,
            explain: 'Desde $(w_0, z_0) = (1, 1)$ se deshacen los reemplazos y se llega a $(13, 4)$.',
          },
          {
            id: 'mc-3-4',
            q: 'En el método de los tanteos, ¿qué se hace después de despejar una incógnita?',
            options: [
              'Se le dan valores enteros a la otra hasta que el resultado sea entero',
              'Se aplica el algoritmo de Euclides al numerador',
              'Se factoriza el término independiente',
              'Se divide la ecuación por el máximo común divisor',
            ],
            correctIndex: 0,
            explain: 'Es literalmente tantear: probar valores hasta dar con el que produce un entero.',
          },
        ],
        ms: [
          {
            id: 'ms-3-1',
            q: '¿Qué supuestos plantea el apunte al desarrollar el método de las divisiones sucesivas sobre la ecuación general?',
            options: [
              'Que $a < b$',
              'Que $a, b \\in \\mathbb{Z}^{+}$',
              'Que se despeja la incógnita de coeficiente de menor valor absoluto',
              'Que $b = a \\cdot q_1 + r_1$ con $r_1 < a$',
              'Que $c$ es múltiplo de $a$',
            ],
            correctIndexes: [0, 1, 2, 3],
            explain: 'No se pide que $c$ sea múltiplo de $a$: justamente por eso queda la fracción que obliga a definir $z$.',
          },
          {
            id: 'ms-3-2',
            q: '¿Cuáles de estas ecuaciones auxiliares aparecen en el desarrollo del Ejemplo 4?',
            options: [
              '$13x - 97z = 72$',
              '$13w - 6z = 7$',
              '$27z + 2y = 17$',
              '$110 = 97 + 13$',
              '$5x + 3y = 8$',
            ],
            correctIndexes: [0, 1],
            explain: '$27z + 2y = 17$ es del Ejemplo 3 y $5x + 3y = 8$ del Ejemplo 1. $110 = 97 + 13$ es una división, no una ecuación diofántica auxiliar.',
          },
          {
            id: 'ms-3-3',
            q: '¿Qué soluciones diofánticas se obtienen en los ejemplos del apunte?',
            options: [
              '$5x + 3y = 8 \\Rightarrow (1, 1)$',
              '$5x - 8y = 2 \\Rightarrow (2, 1)$',
              '$27x + 83y = 17 \\Rightarrow (16, -5)$',
              '$110x - 97y = 1042 \\Rightarrow (13, 4)$',
              '$110x - 97y = 1042 \\Rightarrow (10, 72)$',
            ],
            correctIndexes: [0, 1, 2, 3],
            explain: 'Los números 10 y 72 salen de la división $1042 = 97 \\cdot 10 + 72$, no son una solución de la ecuación.',
          },
        ],
      },
      flashcards: [
        { id: 'fc-3-1', front: 'Método de los tanteos', back: 'Se despeja una incógnita y se le dan valores enteros a la otra hasta encontrar el que da resultado entero.' },
        { id: 'fc-3-2', front: 'Método de las divisiones sucesivas — idea', back: 'Se despeja la incógnita de coeficiente menor, se divide $b$ por $a$ ($b = a q_1 + r_1$) y se define $z = \\dfrac{c - r_1 y}{a}$, llegando a $r_1 y + a z = c$, con coeficientes menores. Se repite si hace falta.' },
        { id: 'fc-3-3', front: 'Ejemplo 1 — $5x + 3y = 8$', back: 'Despejando $y = \\dfrac{8 - 5x}{3}$ y tanteando, $(x_0, y_0) = (1, 1)$.' },
        { id: 'fc-3-4', front: 'Ejemplo 2 — $5x - 8y = 2$', back: 'Despejando $x = \\dfrac{2 + 8y}{5}$ y dando a $y$ valores menores que 5, $(x_0, y_0) = (2, 1)$.' },
        { id: 'fc-3-5', front: 'Ejemplo 3 — $27x + 83y = 17$', back: 'Con $83 = 27 \\cdot 3 + 2$ queda $x = -3y + \\dfrac{17 - 2y}{27}$; la auxiliar $27z + 2y = 17$ da $(z_0, y_0) = (1, -5)$ y la original $(x_0, y_0) = (16, -5)$.' },
        { id: 'fc-3-6', front: 'Ejemplo 4 — $110x - 97y = 1042$', back: 'Dos reducciones ($13x - 97z = 72$ y luego $13w - 6z = 7$) llevan a $(w_0, z_0) = (1, 1)$ y, deshaciendo, a $(x_0, y_0) = (13, 4)$.' },
        { id: 'fc-3-7', front: '¿Por qué el tanteo termina rápido?', back: 'Porque alcanza con probar los valores menores que el coeficiente del denominador: los restos se repiten en ciclo.' },
        { id: 'fc-3-8', front: 'Teorema 1.1 (algoritmo de la división)', back: 'Es el que se invoca para escribir $b = a \\cdot q_1 + r_1$ con $r_1 < a$; el apunte lo usa como base del método de divisiones sucesivas.' },
      ],
    },
    {
      id: '4',
      unit: '2',
      title: 'Solución general de una ecuación diofántica',
      criollo: 'Si encontraste <strong>una</strong> solución, ya las tenés a todas: se generan moviéndose de a saltos fijos a partir de ella. La fórmula $x = x_0 - bt$, $y = y_0 + at$ con $t$ entero te da infinitas soluciones. Geométricamente, la ecuación es una recta y las soluciones diofánticas son los puntos de esa recta que caen justo en los enteros.',
      blocks: [
        { type: 'p', text: '¿Cuántas soluciones diofánticas tiene una ecuación de primer grado con dos incógnitas que satisface la condición de existencia?' },
        { type: 'p', text: 'Sea $(x_0, y_0)$ una solución diofántica de la ecuación $ax + by = c$. Reemplazando $a x_0 + b y_0 = c$, se obtiene' },
        { type: 'math', latex: '\\begin{aligned} ax + by = a x_0 + b y_0 &\\implies a(x - x_0) + b(y - y_0) = 0 \\\\ &\\implies \\frac{x - x_0}{y - y_0} = \\frac{-b}{a} \\end{aligned}', display: true },
        { type: 'p', text: 'Toda solución entera de esta ecuación nos da una solución diofántica de la ecuación de primer grado. Pero dos fracciones son iguales cuando sus términos son múltiplos, es decir:' },
        { type: 'math', latex: '\\begin{cases} x - x_0 = -bt \\\\ y - y_0 = at \\end{cases} \\implies \\begin{cases} x = x_0 - bt \\\\ y = y_0 + at \\end{cases} \\qquad t \\in \\mathbb{Z}', display: true },
        {
          type: 'h3',
          text: 'Interpretación geométrica',
          criollo: 'La recta tiene infinitos puntos, pero solo algunos tienen las dos coordenadas enteras. Buscar soluciones diofánticas es buscar esos puntos donde la recta "pisa" la grilla de enteros.',
        },
        { type: 'p', text: 'Podemos pensar a las ecuaciones diofánticas <strong>geométricamente</strong>. Si $\\{x, y\\} \\in \\mathbb{R}^2$, entonces $ax + by = c$ es una recta en el plano (lo veremos más adelante). Por lo tanto, buscar las soluciones diofánticas significa geométricamente buscar la interacción de la recta y el espacio de los números enteros.' },
        {
          type: 'figure',
          src: 'images/diagrams/algebra-lineal/recta-solucion-diofantica.png',
          alt: 'Recta en el plano cartesiano sobre una grilla, con el punto A marcado en una intersección de la grilla y señalado como "Solución de la ecuación".',
          caption: 'La ecuación $ax + by = c$ es una recta; el punto $A$, donde la recta pasa por un nodo de la grilla de enteros, es una solución diofántica.',
        },
        { type: 'callout', tone: 'criollo', text: 'Traducción: la respuesta a "¿cuántas soluciones tiene?" es <strong>infinitas</strong> (una por cada $t \\in \\mathbb{Z}$), siempre y cuando exista al menos una. Por eso el trabajo pesado es encontrar la primera: el resto sale con la fórmula.' },
      ],
      quiz: {
        tf: [
          { id: 'tf-4-1', q: 'Conocida una solución diofántica $(x_0, y_0)$, la solución general es $x = x_0 - bt$, $y = y_0 + at$ con $t \\in \\mathbb{Z}$.', a: true, explain: 'Es exactamente la fórmula que se obtiene al igualar las fracciones y pedir que sus términos sean múltiplos.' },
          { id: 'tf-4-2', q: 'De $ax + by = a x_0 + b y_0$ se deduce que $a(x - x_0) + b(y - y_0) = 0$.', a: true, explain: 'Es el paso algebraico que hace el apunte: se pasa todo a un miembro y se agrupa.' },
          { id: 'tf-4-3', q: 'Una ecuación diofántica que cumple la condición de existencia tiene exactamente una solución.', a: false, explain: 'Tiene infinitas: una por cada valor entero del parámetro $t$.' },
          { id: 'tf-4-4', q: 'Geométricamente, $ax + by = c$ con $\\{x, y\\} \\in \\mathbb{R}^2$ representa una recta en el plano.', a: true, explain: 'Y buscar las soluciones diofánticas es buscar la interacción de esa recta con el espacio de los números enteros.' },
          { id: 'tf-4-5', q: 'En la solución general, el coeficiente $a$ acompaña a $x$ y el $b$ a $y$.', a: false, explain: 'Se cruzan: $x = x_0 - b t$ (lleva $b$) e $y = y_0 + a t$ (lleva $a$).' },
        ],
        mc: [
          {
            id: 'mc-4-1',
            q: 'A partir de $a(x - x_0) + b(y - y_0) = 0$, ¿a qué igualdad se llega?',
            options: [
              '$\\dfrac{x - x_0}{y - y_0} = \\dfrac{-b}{a}$',
              '$\\dfrac{x - x_0}{y - y_0} = \\dfrac{a}{b}$',
              '$\\dfrac{x + x_0}{y + y_0} = \\dfrac{b}{a}$',
              '$\\dfrac{x - x_0}{y - y_0} = \\dfrac{c}{a}$',
            ],
            correctIndex: 0,
            explain: 'Despejando el cociente queda $\\dfrac{x - x_0}{y - y_0} = \\dfrac{-b}{a}$, y de ahí sale la parametrización con $t$.',
          },
          {
            id: 'mc-4-2',
            q: 'En la solución general, ¿qué recorre el parámetro $t$?',
            options: [
              'Los números enteros, $t \\in \\mathbb{Z}$',
              'Los reales, $t \\in \\mathbb{R}$',
              'Los naturales, $t \\in \\mathbb{N}$',
              'Solo los valores entre 0 y $a$',
            ],
            correctIndex: 0,
            explain: 'El apunte escribe $t \\in \\mathbb{Z}$: por eso las soluciones son infinitas y todas enteras.',
          },
          {
            id: 'mc-4-3',
            q: 'Geométricamente, ¿qué significa buscar las soluciones diofánticas?',
            options: [
              'Buscar la interacción de la recta con el espacio de los números enteros',
              'Buscar la pendiente de la recta',
              'Buscar la intersección de la recta con el eje $y$',
              'Buscar dónde la recta corta al origen',
            ],
            correctIndex: 0,
            explain: 'La recta vive en $\\mathbb{R}^2$; las soluciones diofánticas son los puntos donde cae sobre coordenadas enteras.',
          },
          {
            id: 'mc-4-4',
            q: 'El razonamiento del apunte parte de suponer que:',
            options: [
              '$(x_0, y_0)$ es una solución diofántica ya conocida de $ax + by = c$',
              'La ecuación no tiene solución',
              '$a$ y $b$ son coprimos',
              '$c = 0$',
            ],
            correctIndex: 0,
            explain: 'Se parte de una solución conocida y se generan todas las demás a partir de ella.',
          },
        ],
        ms: [
          {
            id: 'ms-4-1',
            q: '¿Qué afirmaciones sobre la solución general son correctas según el apunte?',
            options: [
              'Se obtiene a partir de una solución particular $(x_0, y_0)$',
              'Tiene la forma $x = x_0 - bt$, $y = y_0 + at$',
              'El parámetro $t$ recorre $\\mathbb{Z}$',
              'Da infinitas soluciones diofánticas',
              'Solo vale si $(a : b) = 1$',
            ],
            correctIndexes: [0, 1, 2, 3],
            explain: 'La deducción no exige que $a$ y $b$ sean coprimos: parte de que ya existe una solución, o sea de que se cumple $(a : b) \\mid c$.',
          },
          {
            id: 'ms-4-2',
            q: '¿Qué pasos aparecen en la deducción de la solución general?',
            options: [
              'Reemplazar $c$ por $a x_0 + b y_0$',
              'Agrupar en $a(x - x_0) + b(y - y_0) = 0$',
              'Igualar el cociente a $\\dfrac{-b}{a}$',
              'Usar que dos fracciones son iguales cuando sus términos son múltiplos',
              'Aplicar el algoritmo de Euclides a $x_0$ e $y_0$',
            ],
            correctIndexes: [0, 1, 2, 3],
            explain: 'Euclides no interviene acá: se usó antes, para verificar la condición de existencia y para reducir coeficientes.',
          },
        ],
      },
      flashcards: [
        { id: 'fc-4-1', front: 'Solución general de $ax + by = c$', back: '$x = x_0 - bt$ e $y = y_0 + at$, con $t \\in \\mathbb{Z}$ y $(x_0, y_0)$ una solución particular.' },
        { id: 'fc-4-2', front: '¿Cuántas soluciones diofánticas hay?', back: 'Infinitas, una por cada $t \\in \\mathbb{Z}$, siempre que se cumpla la condición de existencia $(a : b) \\mid c$.' },
        { id: 'fc-4-3', front: 'Paso clave de la deducción', back: 'Reemplazar $c = a x_0 + b y_0$ para obtener $a(x - x_0) + b(y - y_0) = 0$ y de ahí $\\dfrac{x - x_0}{y - y_0} = \\dfrac{-b}{a}$.' },
        { id: 'fc-4-4', front: '¿Por qué aparece el parámetro $t$?', back: 'Porque dos fracciones son iguales cuando sus términos son múltiplos: $x - x_0 = -bt$ e $y - y_0 = at$.' },
        { id: 'fc-4-5', front: 'Interpretación geométrica', back: 'Si $\\{x, y\\} \\in \\mathbb{R}^2$, $ax + by = c$ es una recta en el plano; las soluciones diofánticas son la interacción de esa recta con el espacio de los enteros.' },
        { id: 'fc-4-6', front: '¿Qué muestra la figura del apunte?', back: 'Una recta sobre una grilla, con el punto $A$ señalado como "Solución de la ecuación": el lugar donde la recta pasa por coordenadas enteras.' },
      ],
    },
    {
      id: '5',
      unit: '2',
      title: 'Congruencia',
      criollo: 'Congruencia es aritmética de restos. Dos números son congruentes módulo $m$ si al dividirlos por $m$ te dan el mismo resto — o, lo que es lo mismo, si $m$ divide a la diferencia. Lo copado es que se puede sumar, restar, multiplicar y elevar sin salirse de la congruencia, y eso te deja calcular restos de potencias gigantes sin calcular la potencia.',
      blocks: [
        { type: 'p', text: 'Supongamos que recorremos los números enteros y vamos anotando los restos de dividirlos por un número natural $m$. Resulta entonces que dichos restos forman el ciclo infinito en el que cada valor se repite exactamente cada $m$ pasos:' },
        { type: 'math', latex: '0;\\ 1;\\ 2;\\ 3;\\ \\dots;\\ (m-2);\\ (m-1);\\ 0;\\ 1;\\ 2;\\ \\dots', display: true },
        { type: 'p', text: 'Esta situación es de gran importancia en teoría de números y emplearemos una terminología especial para referirnos a ella.' },
        {
          type: 'h3',
          text: 'Definición 2 — Congruencia módulo m',
          criollo: 'Tres formas de decir lo mismo: mismo resto, $m$ divide a la diferencia, o uno es el otro más un múltiplo de $m$. Usá la que te sirva según el ejercicio.',
        },
        { type: 'p', text: '<strong>Definición 2.</strong> Sean $m \\in \\mathbb{N}$ y $a, b \\in \\mathbb{Z}$; diremos que <strong>$a$ es congruente a $b$ módulo $m$</strong>, y escribimos $a \\equiv b\\ (m)$, si $m$ divide a $(b - a)$.' },
        { type: 'math', latex: 'a \\equiv b\\ (m) \\iff m \\mid (b - a)', display: true },
        { type: 'p', text: 'Conviene tener presente que las tres siguientes afirmaciones refieren la misma situación:' },
        {
          type: 'ul',
          items: [
            '$a \\equiv b\\ (m)$ si $a$ y $b$ tienen el mismo resto al dividirlos por $m$, es decir $r_m(a) = r_m(b)$.',
            '$a \\equiv b\\ (m)$.',
            '$a = b + km$ para algún $k \\in \\mathbb{Z}$.',
          ],
        },
        {
          type: 'h3',
          text: 'Proposición 1 — Propiedades operatorias',
          criollo: 'Las congruencias se llevan bien con las cuentas: podés sumarlas, restarlas y multiplicarlas entre sí como si fueran igualdades. Por eso se puede operar módulo $m$ sin miedo.',
        },
        { type: 'p', text: '<strong>Proposición 1.</strong> Si $a \\equiv b\\ (n)$ y $c \\equiv d\\ (n)$, entonces:' },
        {
          type: 'ul',
          items: [
            '$a + c \\equiv b + d\\ (n)$.',
            '$a - c \\equiv b - d\\ (n)$.',
            '$ac \\equiv bd\\ (n)$.',
            'Para todo entero positivo $k \\in \\mathbb{N}$: $a^k \\equiv b^k\\ (n)$.',
            'Para todo entero $r \\in \\mathbb{Z}$: $a + r \\equiv b + r\\ (n)$.',
            'Para todo entero $s \\in \\mathbb{Z}$: $as \\equiv bs\\ (n)$.',
          ],
        },
        { type: 'p', text: 'Podemos resumir todas las propiedades en una sola línea:' },
        { type: 'math', latex: '\\forall\\, r, s \\in \\mathbb{Z} \\qquad ar + cs \\equiv br + ds\\ (n) \\qquad (2.2)', display: true },
        { type: 'callout', tone: 'info', text: 'En el PDF esta fórmula 2.2 está impresa como $ar + cs \\equiv bs + ds\\ (n)$: es una errata evidente del apunte, porque el término $ar$ tiene que corresponderse con $br$. Se transcribe corregida para que sea coherente con las seis propiedades de la Proposición 1.' },
        {
          type: 'h3',
          text: 'Problemas de residuo — el resto de 11 elevado a 1243, dividido por 7',
          criollo: 'El truco: buscás una potencia que te dé resto 1. A partir de ahí, esa potencia "desaparece" y solo te queda el sobrante del exponente. Nunca calculás el número gigante.',
        },
        { type: 'p', text: 'Ahora veremos cómo resolver problemas relativos al residuo. Calculamos el residuo obtenido al dividir $11^{1243}$ por 7. El primer paso es encontrar el exponente $n$ tal que $11^n \\equiv 1\\ (7)$.' },
        { type: 'p', text: 'Empezamos a calcular con $n = 1$:' },
        { type: 'math', latex: '(11)^1 \\equiv 4\\ (7) \\qquad (2.3)', display: true },
        { type: 'p', text: 'Seguimos con $n = 2$ y utilizamos el resultado anterior:' },
        { type: 'math', latex: '(11)^2 \\equiv (4)^2 = 16 \\equiv 2\\ (7)', display: true },
        { type: 'p', text: 'Para $n = 3$ utilizamos de vuelta los resultados anteriores:' },
        { type: 'math', latex: '(11)^3 = (11)^2 \\cdot (11)^1 \\equiv 2 \\cdot (11)^1 \\equiv 4 \\cdot 2 = 8 \\equiv 1\\ (7)', display: true },
        { type: 'p', text: 'Hemos encontrado que $11^3 \\equiv 1\\ (7)$, entonces calculamos el resto de la división de 1243 por 3. Utilizando el algoritmo de Euclides tenemos que:' },
        { type: 'math', latex: '1243 = 414 \\cdot 3 + 1 \\qquad (2.4)', display: true },
        { type: 'p', text: 'Ahora, sabiendo 2.3 y 2.4, tenemos:' },
        { type: 'math', latex: '11^{1243} = 11^{(3 \\cdot 414 + 1)} = (11^3)^{414} \\cdot 11^1 = (1)^{414} \\cdot 11 = 1 \\cdot 11 \\equiv 4\\ (7)', display: true },
        { type: 'p', text: 'Entonces <strong>el resto de la división de $11^{1243}$ por 7 es 4</strong>.' },
        { type: 'callout', tone: 'info', text: 'Después de este ejemplo el apunte escribe "En general" y pasa directo al Ejemplo 2.2: la generalización queda enunciada pero no desarrollada en el texto fuente.' },
        { type: 'p', text: '<strong>Ejemplo 2.2.</strong> Hallemos el residuo obtenido al dividir $7^{135}$ por 8. Observemos que' },
        { type: 'math', latex: '7^2 \\equiv 1\\ (8)', display: true },
        { type: 'p', text: 'Entonces tenemos:' },
        { type: 'math', latex: '7^{135} = 7^{(2 \\cdot 67 + 1)} = (7^2)^{67} \\cdot 7^1 = (1)^{67} \\cdot 7 = 1 \\cdot 7 \\equiv 7\\ (8)', display: true },
        { type: 'callout', tone: 'criollo', text: 'La receta para cualquier "resto de $a^N$ por $m$": buscá el menor $n$ con $a^n \\equiv 1\\ (m)$, dividí $N$ por ese $n$ y quedate con el resto $r$. La respuesta es el resto de $a^r$. En el primer ejemplo, $1243 = 414 \\cdot 3 + 1$, así que sobra $11^1 \\equiv 4$.' },
      ],
      quiz: {
        tf: [
          { id: 'tf-5-1', q: '$a \\equiv b\\ (m)$ significa que $m$ divide a $(b - a)$.', a: true, explain: 'Es la Definición 2 del apunte, escrita como $a \\equiv b\\ (m) \\iff m \\mid (b - a)$.' },
          { id: 'tf-5-2', q: 'Los restos de dividir los enteros por $m$ forman un ciclo que se repite exactamente cada $m$ pasos.', a: true, explain: 'El ciclo es $0; 1; 2; \\dots; (m-1); 0; 1; \\dots$, con período $m$.' },
          { id: 'tf-5-3', q: 'Si $a \\equiv b\\ (n)$ y $c \\equiv d\\ (n)$, entonces $ac \\equiv bd\\ (n)$.', a: true, explain: 'Es una de las propiedades de la Proposición 1: las congruencias se pueden multiplicar entre sí.' },
          { id: 'tf-5-4', q: 'El resto de dividir $11^{1243}$ por 7 es 1.', a: false, explain: 'Es 4. Lo que vale 1 es $11^3 \\equiv 1\\ (7)$; al sobrar exponente 1 queda $11 \\equiv 4\\ (7)$.' },
          { id: 'tf-5-5', q: 'Decir que $a$ y $b$ tienen el mismo resto al dividirlos por $m$ es otra forma de decir que $a \\equiv b\\ (m)$.', a: true, explain: 'Es una de las tres afirmaciones equivalentes: $r_m(a) = r_m(b)$.' },
        ],
        mc: [
          {
            id: 'mc-5-1',
            q: '¿Cuál de estas expresiones NO es equivalente a $a \\equiv b\\ (m)$?',
            options: [
              '$a = b \\cdot km$ para algún $k \\in \\mathbb{Z}$',
              '$m \\mid (b - a)$',
              '$r_m(a) = r_m(b)$',
              '$a = b + km$ para algún $k \\in \\mathbb{Z}$',
            ],
            correctIndex: 0,
            explain: 'La forma correcta es $a = b + km$ (suma de un múltiplo de $m$), no un producto.',
          },
          {
            id: 'mc-5-2',
            q: 'Para calcular el resto de $11^{1243}$ por 7, ¿cuál es el primer paso del método?',
            options: [
              'Encontrar el exponente $n$ tal que $11^n \\equiv 1\\ (7)$',
              'Calcular $11^{1243}$ y dividirlo por 7',
              'Factorizar 1243 en primos',
              'Aplicar el teorema 2.1',
            ],
            correctIndex: 0,
            explain: 'Se busca la potencia que da resto 1; en este caso $11^3 \\equiv 1\\ (7)$.',
          },
          {
            id: 'mc-5-3',
            q: 'En el Ejemplo 2.2, ¿cuál es el residuo de dividir $7^{135}$ por 8?',
            options: ['7', '1', '3', '5'],
            correctIndex: 0,
            explain: 'Como $7^2 \\equiv 1\\ (8)$ y $135 = 2 \\cdot 67 + 1$, queda $(1)^{67} \\cdot 7 \\equiv 7\\ (8)$.',
          },
          {
            id: 'mc-5-4',
            q: 'Según la Proposición 1, si $a \\equiv b\\ (n)$, ¿qué vale para todo entero positivo $k$?',
            options: [
              '$a^k \\equiv b^k\\ (n)$',
              '$ka \\equiv b\\ (n)$',
              '$a \\equiv b^k\\ (kn)$',
              '$a^k \\equiv b\\ (n^k)$',
            ],
            correctIndex: 0,
            explain: 'Las congruencias se pueden elevar a una misma potencia entera positiva.',
          },
        ],
        ms: [
          {
            id: 'ms-5-1',
            q: '¿Cuáles de estas propiedades enuncia la Proposición 1 para $a \\equiv b\\ (n)$ y $c \\equiv d\\ (n)$?',
            options: [
              '$a + c \\equiv b + d\\ (n)$',
              '$a - c \\equiv b - d\\ (n)$',
              '$ac \\equiv bd\\ (n)$',
              '$a^k \\equiv b^k\\ (n)$ para $k \\in \\mathbb{N}$',
              '$a / c \\equiv b / d\\ (n)$',
            ],
            correctIndexes: [0, 1, 2, 3],
            explain: 'La división no figura entre las propiedades: no se puede dividir congruencias sin condiciones extra.',
          },
          {
            id: 'ms-5-2',
            q: '¿Qué pasos del cálculo del resto de $11^{1243}$ por 7 son correctos según el apunte?',
            options: [
              '$(11)^1 \\equiv 4\\ (7)$',
              '$(11)^2 \\equiv 16 \\equiv 2\\ (7)$',
              '$(11)^3 \\equiv 8 \\equiv 1\\ (7)$',
              '$1243 = 414 \\cdot 3 + 1$',
              '$1243 = 177 \\cdot 7 + 4$',
            ],
            correctIndexes: [0, 1, 2, 3],
            explain: 'La división que se hace es la de 1243 por 3 (el exponente hallado), no por 7.',
          },
          {
            id: 'ms-5-3',
            q: '¿Qué afirmaciones son equivalentes a $a \\equiv b\\ (m)$?',
            options: [
              '$m \\mid (b - a)$',
              '$r_m(a) = r_m(b)$',
              '$a = b + km$ para algún $k \\in \\mathbb{Z}$',
              '$a$ y $b$ son ambos múltiplos de $m$',
              '$a - b$ es primo',
            ],
            correctIndexes: [0, 1, 2],
            explain: 'Las dos últimas no salen de la definición: la congruencia habla de la diferencia, no de que cada número sea múltiplo ni de primalidad.',
          },
        ],
      },
      flashcards: [
        { id: 'fc-5-1', front: 'Congruencia módulo $m$ (Definición 2)', back: 'Con $m \\in \\mathbb{N}$ y $a, b \\in \\mathbb{Z}$: $a \\equiv b\\ (m)$ si y solo si $m \\mid (b - a)$.' },
        { id: 'fc-5-2', front: 'Tres formas equivalentes', back: 'Mismo resto al dividir por $m$ ($r_m(a) = r_m(b)$); $m \\mid (b - a)$; y $a = b + km$ para algún $k \\in \\mathbb{Z}$.' },
        { id: 'fc-5-3', front: 'Ciclo de los restos', back: 'Al dividir los enteros por $m$, los restos forman el ciclo infinito $0; 1; 2; \\dots; (m-1); 0; 1; \\dots$, que se repite cada $m$ pasos.' },
        { id: 'fc-5-4', front: 'Proposición 1 — operaciones', back: 'Si $a \\equiv b\\ (n)$ y $c \\equiv d\\ (n)$: se pueden sumar, restar y multiplicar las congruencias, elevar a potencia $k \\in \\mathbb{N}$, y sumar o multiplicar por un entero fijo.' },
        { id: 'fc-5-5', front: 'Fórmula 2.2 (resumen)', back: '$\\forall\\, r, s \\in \\mathbb{Z}$: $ar + cs \\equiv br + ds\\ (n)$. Resume todas las propiedades de la Proposición 1 en una línea.' },
        { id: 'fc-5-6', front: 'Método para el resto de una potencia', back: 'Buscar $n$ tal que $a^n \\equiv 1\\ (m)$, dividir el exponente por $n$ y quedarse con el resto: la respuesta es el resto de $a$ elevado a ese sobrante.' },
        { id: 'fc-5-7', front: 'Resto de $11^{1243}$ por 7', back: '4. Se usa $11^3 \\equiv 1\\ (7)$ y $1243 = 414 \\cdot 3 + 1$, así que queda $(1)^{414} \\cdot 11 \\equiv 4\\ (7)$.' },
        { id: 'fc-5-8', front: 'Resto de $7^{135}$ por 8', back: '7. Se usa $7^2 \\equiv 1\\ (8)$ y $135 = 2 \\cdot 67 + 1$, así que queda $(1)^{67} \\cdot 7 \\equiv 7\\ (8)$.' },
      ],
    },
    {
      id: '6',
      unit: '2',
      title: 'Ecuaciones modulares',
      criollo: 'Acá se cierra el círculo: una ecuación de congruencia $aX \\equiv b\\ (m)$ es, en el fondo, una diofántica disfrazada. Si la escribís como $aX - mt = b$ te queda la misma forma de siempre, y por eso la condición para que tenga solución es la misma: $(a : m) \\mid b$. Además, la cantidad de soluciones distintas en $\\mathbb{Z}_m$ es justo ese máximo común divisor.',
      blocks: [
        { type: 'p', text: 'Si $a, b \\in \\mathbb{Z}$ y $m \\in \\mathbb{N}$,' },
        { type: 'math', latex: 'aX \\equiv b\\ (m) \\qquad (2.5)', display: true },
        { type: 'p', text: 'es una <strong>ecuación lineal de congruencia</strong>. Estudiemos su resolubilidad y, en el caso de que exista alguna solución, exhibiremos un método para hallar todas las soluciones.' },
        { type: 'p', text: 'Aclaremos en primer lugar qué entenderemos por resolverla. Si consideramos que una solución es un entero $X$ tal que $aX \\equiv b\\ (m)$, la compatibilidad de la relación de congruencia con las operaciones nos muestra inmediatamente que <strong>cualquier entero congruente con $X$ módulo $m$ también es una solución</strong>.' },
        {
          type: 'h3',
          text: 'Observación 1 — Es una diofántica escrita de otra forma',
          criollo: 'Este es el puente entre las dos mitades de la unidad. Todo lo que aprendiste para diofánticas se aplica tal cual acá.',
        },
        { type: 'p', text: '<strong>Observación 1.</strong> La ecuación 2.5 se puede leer como ecuación diofántica: si $X$ es una solución, entonces existe un entero $t \\in \\mathbb{Z}$ tal que:' },
        { type: 'math', latex: 'aX = b + mt \\qquad \\text{o} \\qquad aX - mt = b', display: true },
        {
          type: 'h3',
          text: 'Proposición 2 — Condición de resolubilidad',
          criollo: 'Mismo criterio que el teorema 2.1, con $m$ en el lugar de $b$. Y si $a$ y $m$ son coprimos, la ecuación tiene solución siempre, sea cual sea $b$.',
        },
        { type: 'p', text: 'Comencemos entonces por determinar una condición necesaria y suficiente para su resolución.' },
        { type: 'p', text: '<strong>Proposición 2.</strong> La ecuación 2.5 es resoluble si y solo si $(a : m) \\mid b$.' },
        { type: 'p', text: '<strong>Demostración:</strong> si $x$ representa una solución, la condición $ax \\equiv b\\ (m)$ es equivalente a la existencia de un entero $y$ tal que $ax + my = b$. Por lo tanto, la ecuación de congruencia 2.5 es resoluble si y solo si esta última ecuación diofántica lo es. Como vimos en 2.1, ello ocurre si y solo si $(a : m) \\mid b$, como queríamos demostrar.' },
        { type: 'p', text: 'Como caso particular importante, notemos que si $a$ y $m$ son <strong>coprimos</strong>, entonces $ax \\equiv b\\ (m)$ es resoluble cualquiera sea $b$.' },
        {
          type: 'h3',
          text: 'Ejemplo 2.3 — Resolver 152X ≡ −88 (36)',
          criollo: 'Primero achicás los coeficientes módulo 36 (podés, porque son congruencias). Después Euclides te da una solución, y las demás salen sumando $m/d$ cada vez.',
        },
        { type: 'p', text: 'Resolvamos la ecuación $152X \\equiv -88\\ (36)$. Tratándose de congruencias, es claro que podemos <strong>reducir los coeficientes módulo 36</strong>, por lo que es equivalente resolver la ecuación' },
        { type: 'math', latex: '8X \\equiv 20\\ (36)', display: true },
        { type: 'p', text: 'Puesto que $(8 : 36) = 4$ y $4 \\mid 20$, resulta que la ecuación es resoluble y tiene <strong>4 soluciones</strong> en $\\mathbb{Z}_{36}$.' },
        { type: 'p', text: 'Para hallar una, aplicamos el algoritmo de Euclides para escribir $(8 : 36)$ como combinación lineal de 8 y 36, obteniéndose la expresión $4 = 8(-4) + 36 \\cdot 1$, de donde (multiplicando por 5)' },
        { type: 'math', latex: '20 = 8(-20) + 36 \\cdot 5', display: true },
        { type: 'p', text: 'o, en términos de congruencias: $8(-20) \\equiv 20\\ (36)$. Luego $(-20)$ es una solución de la ecuación. En este caso $m/d = 9$, y las soluciones en $\\mathbb{Z}_{36}$ son $(-20)$, $(-11)$, $(-2)$ y $(7)$.' },
        { type: 'p', text: 'Si nos interesa escribirlas usando los <strong>representantes canónicos</strong> de las clases, concluimos que el conjunto de soluciones es' },
        { type: 'math', latex: '\\{(7),\\ (16),\\ (25),\\ (34)\\}', display: true },
        { type: 'p', text: 'Equivalentemente, un número entero $X$ satisface la relación $152X \\equiv -88\\ (36)$ si y solo si el resto de dividir $X$ por 36 es 7, 16, 25 o 34.' },
        {
          type: 'h3',
          text: 'Proposición 3 — Simplificar por un divisor común',
          criollo: 'Si un mismo número divide a los tres ($a$, $b$ y $m$), podés dividir todo por él — incluido el módulo. Ojo con eso último: el módulo también se achica.',
        },
        { type: 'p', text: '<strong>Proposición 3.</strong> Si $a, b, m, d$ son enteros, con $d$ mayor que 0 y $d \\mid a$, $d \\mid b$, $d \\mid m$, entonces la ecuación $aX \\equiv b\\ (m)$ admite una solución si y solo si la ecuación:' },
        { type: 'math', latex: '\\frac{a}{d}X \\equiv \\frac{b}{d}\\ \\left(\\frac{m}{d}\\right)', display: true },
        { type: 'callout', tone: 'criollo', text: 'Resumen operativo: reducí coeficientes módulo $m$ → calculá $d = (a : m)$ → si $d \\nmid b$, no hay solución → si divide, hay exactamente $d$ soluciones en $\\mathbb{Z}_m$, y salen de una particular sumándole $m/d$ cada vez.' },
      ],
      quiz: {
        tf: [
          { id: 'tf-6-1', q: 'La ecuación $aX \\equiv b\\ (m)$ es resoluble si y solo si $(a : m) \\mid b$.', a: true, explain: 'Es la Proposición 2, y se demuestra reduciéndola a la ecuación diofántica $ax + my = b$.' },
          { id: 'tf-6-2', q: 'Si $X$ es solución de $aX \\equiv b\\ (m)$, ningún otro entero congruente con $X$ módulo $m$ lo es.', a: false, explain: 'Al revés: la compatibilidad de la congruencia con las operaciones muestra que cualquier entero congruente con $X$ módulo $m$ también es solución.' },
          { id: 'tf-6-3', q: 'Si $a$ y $m$ son coprimos, la ecuación $aX \\equiv b\\ (m)$ es resoluble cualquiera sea $b$.', a: true, explain: 'Es el caso particular que remarca el apunte: si $(a : m) = 1$, ese 1 divide a cualquier $b$.' },
          { id: 'tf-6-4', q: 'En el Ejemplo 2.3, la ecuación $152X \\equiv -88\\ (36)$ tiene 4 soluciones en $\\mathbb{Z}_{36}$.', a: true, explain: 'Reducida a $8X \\equiv 20\\ (36)$, con $(8 : 36) = 4$ y $4 \\mid 20$, hay 4 soluciones.' },
          { id: 'tf-6-5', q: 'La Proposición 3 permite dividir $a$ y $b$ por $d$ dejando el módulo $m$ intacto.', a: false, explain: 'El módulo también se divide: la ecuación equivalente es $\\dfrac{a}{d}X \\equiv \\dfrac{b}{d}\\ \\left(\\dfrac{m}{d}\\right)$.' },
        ],
        mc: [
          {
            id: 'mc-6-1',
            q: 'Según la Observación 1, ¿cómo se reescribe $aX \\equiv b\\ (m)$ como ecuación diofántica?',
            options: [
              '$aX - mt = b$, con $t \\in \\mathbb{Z}$',
              '$aX + b = mt$, con $t \\in \\mathbb{N}$',
              '$aX \\cdot mt = b$, con $t \\in \\mathbb{Z}$',
              '$a + X = b + m$, con $t \\in \\mathbb{Z}$',
            ],
            correctIndex: 0,
            explain: 'Si $X$ es solución existe $t$ entero con $aX = b + mt$, o sea $aX - mt = b$.',
          },
          {
            id: 'mc-6-2',
            q: 'En el Ejemplo 2.3, ¿a qué ecuación equivalente se reduce $152X \\equiv -88\\ (36)$?',
            options: [
              '$8X \\equiv 20\\ (36)$',
              '$8X \\equiv -88\\ (36)$',
              '$152X \\equiv 20\\ (9)$',
              '$4X \\equiv 5\\ (36)$',
            ],
            correctIndex: 0,
            explain: 'Se reducen los coeficientes módulo 36: $152$ pasa a $8$ y $-88$ pasa a $20$.',
          },
          {
            id: 'mc-6-3',
            q: 'El conjunto de soluciones del Ejemplo 2.3, con representantes canónicos, es:',
            options: [
              '$\\{(7), (16), (25), (34)\\}$',
              '$\\{(-20), (-11), (-2), (7)\\}$ únicamente',
              '$\\{(4), (8), (20), (36)\\}$',
              '$\\{(9), (18), (27), (36)\\}$',
            ],
            correctIndex: 0,
            explain: 'Las soluciones $(-20), (-11), (-2), (7)$ escritas con representantes canónicos dan $7, 16, 25$ y $34$.',
          },
          {
            id: 'mc-6-4',
            q: '¿Para qué se usa el algoritmo de Euclides en el Ejemplo 2.3?',
            options: [
              'Para escribir $(8 : 36)$ como combinación lineal de 8 y 36',
              'Para calcular el resto de dividir 152 por 36',
              'Para contar cuántas soluciones hay',
              'Para verificar que 20 es par',
            ],
            correctIndex: 0,
            explain: 'Se obtiene $4 = 8(-4) + 36 \\cdot 1$ y, multiplicando por 5, la solución particular $(-20)$.',
          },
        ],
        ms: [
          {
            id: 'ms-6-1',
            q: '¿Qué pasos del Ejemplo 2.3 aparecen en el apunte?',
            options: [
              'Reducir los coeficientes módulo 36 para llegar a $8X \\equiv 20\\ (36)$',
              'Verificar que $(8 : 36) = 4$ y que $4 \\mid 20$',
              'Escribir $4 = 8(-4) + 36 \\cdot 1$ con Euclides',
              'Multiplicar por 5 para obtener $20 = 8(-20) + 36 \\cdot 5$',
              'Elevar ambos miembros al cuadrado',
            ],
            correctIndexes: [0, 1, 2, 3],
            explain: 'Elevar al cuadrado no forma parte del método; el resto son los pasos textuales del ejemplo.',
          },
          {
            id: 'ms-6-2',
            q: '¿Qué hipótesis exige la Proposición 3 sobre $d$?',
            options: [
              'Que $d$ sea mayor que 0',
              'Que $d \\mid a$',
              'Que $d \\mid b$',
              'Que $d \\mid m$',
              'Que $d$ sea primo',
            ],
            correctIndexes: [0, 1, 2, 3],
            explain: 'No se pide que $d$ sea primo: alcanza con que sea positivo y divida a los tres coeficientes.',
          },
          {
            id: 'ms-6-3',
            q: '¿Cuáles de estas afirmaciones sobre las soluciones de una ecuación modular son correctas según el apunte?',
            options: [
              'Cualquier entero congruente con una solución módulo $m$ también es solución',
              'La cantidad de soluciones en $\\mathbb{Z}_{36}$ del ejemplo es 4',
              'Las soluciones del ejemplo se obtienen sumando $m/d = 9$ a partir de $(-20)$',
              'Un entero $X$ cumple $152X \\equiv -88\\ (36)$ si el resto de dividirlo por 36 es 7, 16, 25 o 34',
              'La ecuación tiene siempre una única solución entera',
            ],
            correctIndexes: [0, 1, 2, 3],
            explain: 'Nunca hay una única solución entera: si hay una, hay infinitas en $\\mathbb{Z}$, agrupadas en $d$ clases módulo $m$.',
          },
        ],
      },
      flashcards: [
        { id: 'fc-6-1', front: 'Ecuación lineal de congruencia', back: 'Con $a, b \\in \\mathbb{Z}$ y $m \\in \\mathbb{N}$, la ecuación $aX \\equiv b\\ (m)$ (ecuación 2.5).' },
        { id: 'fc-6-2', front: 'Observación 1', back: '$aX \\equiv b\\ (m)$ se lee como diofántica: existe $t \\in \\mathbb{Z}$ con $aX = b + mt$, o sea $aX - mt = b$.' },
        { id: 'fc-6-3', front: 'Proposición 2', back: 'La ecuación $aX \\equiv b\\ (m)$ es resoluble si y solo si $(a : m) \\mid b$.' },
        { id: 'fc-6-4', front: 'Caso $a$ y $m$ coprimos', back: 'Si $(a : m) = 1$, la ecuación $aX \\equiv b\\ (m)$ es resoluble cualquiera sea $b$.' },
        { id: 'fc-6-5', front: 'Ejemplo 2.3 — reducción', back: '$152X \\equiv -88\\ (36)$ equivale a $8X \\equiv 20\\ (36)$, porque los coeficientes se pueden reducir módulo 36.' },
        { id: 'fc-6-6', front: 'Ejemplo 2.3 — soluciones', back: 'Como $(8 : 36) = 4$ y $4 \\mid 20$, hay 4 soluciones en $\\mathbb{Z}_{36}$: $\\{(7), (16), (25), (34)\\}$.' },
        { id: 'fc-6-7', front: '¿Cómo se genera el resto de las soluciones?', back: 'A partir de una particular (acá $-20$), sumando $m/d$ cada vez (acá $36/4 = 9$).' },
        { id: 'fc-6-8', front: 'Proposición 3', back: 'Si $d > 0$ y $d \\mid a$, $d \\mid b$, $d \\mid m$, entonces $aX \\equiv b\\ (m)$ tiene solución si y solo si $\\dfrac{a}{d}X \\equiv \\dfrac{b}{d}\\ \\left(\\dfrac{m}{d}\\right)$.' },
      ],
    },
    {
      id: '7',
      unit: '2',
      title: 'Aplicación de las ecuaciones lineales',
      criollo: 'Cierre de la unidad con la parte "para qué sirve": el apunte muestra tres lugares donde se resuelven sistemas lineales todo el tiempo — buscar petróleo, armar itinerarios de aerolíneas y diseñar circuitos. No es teoría de museo, se usa a escala industrial.',
      blocks: [
        { type: 'p', text: 'El problema de los <strong>sistemas lineales de ecuaciones</strong> es uno de los más antiguos de la matemática y tiene una infinidad de aplicaciones, tales como en procesamiento digital de señales, análisis estructural, estimación, predicción y, más generalmente, en programación lineal, así como en la aproximación de problemas no lineales de análisis numérico.' },
        { type: 'p', text: 'Veremos ahora algunas aplicaciones en la vida real.' },
        {
          type: 'h3',
          text: 'Exploración petrolera',
          criollo: 'Un barco resolviendo miles de sistemas por día. Nada de resolver uno a mano en una hoja.',
        },
        { type: 'p', text: 'Cuando un barco busca depósitos submarinos de petróleo, diariamente sus computadoras resuelven <strong>miles de sistemas de ecuaciones lineales</strong> por separado. La información sísmica para elaborar las ecuaciones se obtiene a partir de ondas de choque submarinas creadas mediante explosiones con pistolas de aire. Las ondas rebotan en las rocas que hay bajo la superficie marina y se miden empleando geófonos conectados a extensos cables instalados debajo del barco.' },
        {
          type: 'h3',
          text: 'Programación lineal',
          criollo: 'Las aerolíneas viven de esto: quién vuela con quién, dónde está cada avión y cuándo entra a mantenimiento.',
        },
        { type: 'p', text: 'Muchas decisiones administrativas importantes se toman sobre la base de modelos de programación lineal que utilizan <strong>cientos de variables</strong>. Por ejemplo, la industria de las aerolíneas emplea programas lineales para crear los itinerarios de las tripulaciones de vuelo, monitorear las ubicaciones de los aviones o planear los diversos programas de servicios de apoyo, como mantenimiento y operaciones en terminal.' },
        {
          type: 'h3',
          text: 'Redes eléctricas',
          criollo: 'Millones de transistores no se simulan a ojo: atrás hay álgebra lineal.',
        },
        { type: 'p', text: 'Los ingenieros utilizan programas de cómputo de simulación para diseñar circuitos eléctricos y microchips que incluyen <strong>millones de transistores</strong>. Estos programas utilizan técnicas de álgebra lineal y sistemas de ecuaciones lineales.' },
        { type: 'callout', tone: 'criollo', text: 'Fijate el hilo de la unidad: arrancó con el hash code (informática), pasó por diofánticas y congruencias (teoría de números) y cierra con sistemas lineales aplicados. El común denominador es resolver ecuaciones lineales, con o sin la restricción de que las soluciones sean enteras.' },
      ],
      quiz: {
        tf: [
          { id: 'tf-7-1', q: 'El problema de los sistemas lineales de ecuaciones es uno de los más antiguos de la matemática.', a: true, explain: 'Así lo presenta el apunte, antes de listar sus aplicaciones.' },
          { id: 'tf-7-2', q: 'Un barco que busca petróleo resuelve diariamente miles de sistemas de ecuaciones lineales.', a: true, explain: 'Y lo hace por separado, con la información sísmica que recogen los geófonos.' },
          { id: 'tf-7-3', q: 'La información sísmica para armar esas ecuaciones se obtiene con ondas de choque submarinas creadas por explosiones con pistolas de aire.', a: true, explain: 'Las ondas rebotan en las rocas bajo la superficie marina y se miden con geófonos conectados a cables debajo del barco.' },
          { id: 'tf-7-4', q: 'Los modelos de programación lineal que menciona el apunte usan unas pocas variables.', a: false, explain: 'Habla de modelos que utilizan <strong>cientos</strong> de variables.' },
          { id: 'tf-7-5', q: 'Los programas de simulación de circuitos y microchips utilizan técnicas de álgebra lineal.', a: true, explain: 'Diseñan circuitos con millones de transistores usando álgebra lineal y sistemas de ecuaciones lineales.' },
        ],
        mc: [
          {
            id: 'mc-7-1',
            q: '¿Qué instrumento se usa para medir las ondas en la exploración petrolera?',
            options: ['Geófonos conectados a extensos cables', 'Radares de superficie', 'Sonares de casco', 'Magnetómetros satelitales'],
            correctIndex: 0,
            explain: 'Los geófonos están conectados a extensos cables instalados debajo del barco.',
          },
          {
            id: 'mc-7-2',
            q: 'Según el apunte, ¿para qué usa la industria de las aerolíneas los programas lineales?',
            options: [
              'Para crear itinerarios de tripulaciones, monitorear ubicaciones de aviones y planear servicios de apoyo',
              'Para calcular el precio de los pasajes en tiempo real',
              'Para diseñar el fuselaje de los aviones',
              'Para predecir el clima en las rutas de vuelo',
            ],
            correctIndex: 0,
            explain: 'Son los tres usos que enumera el apunte, incluidos mantenimiento y operaciones en terminal.',
          },
          {
            id: 'mc-7-3',
            q: '¿Cuál de estas NO figura entre las aplicaciones de los sistemas lineales que menciona el apunte?',
            options: [
              'Diseño de currículas educativas',
              'Procesamiento digital de señales',
              'Análisis estructural',
              'Aproximación de problemas no lineales de análisis numérico',
            ],
            correctIndex: 0,
            explain: 'La lista del apunte incluye señales, análisis estructural, estimación, predicción, programación lineal y análisis numérico.',
          },
          {
            id: 'mc-7-4',
            q: 'Los microchips que se diseñan con estas técnicas incluyen:',
            options: ['Millones de transistores', 'Cientos de transistores', 'Miles de resistencias', 'Decenas de circuitos integrados'],
            correctIndex: 0,
            explain: 'El apunte habla de circuitos eléctricos y microchips con millones de transistores.',
          },
        ],
        ms: [
          {
            id: 'ms-7-1',
            q: '¿Qué aplicaciones de los sistemas lineales enumera el apunte en la introducción?',
            options: [
              'Procesamiento digital de señales',
              'Análisis estructural',
              'Estimación y predicción',
              'Programación lineal',
              'Criptografía de clave pública',
            ],
            correctIndexes: [0, 1, 2, 3],
            explain: 'La criptografía no aparece en esta sección, aunque la congruencia sea su base matemática.',
          },
          {
            id: 'ms-7-2',
            q: '¿Cuáles son los tres casos de "aplicaciones en la vida real" que desarrolla el apunte?',
            options: [
              'Exploración petrolera',
              'Programación lineal',
              'Redes eléctricas',
              'Diseño de bases de datos',
              'Logística portuaria',
            ],
            correctIndexes: [0, 1, 2],
            explain: 'Son exactamente tres subtítulos: exploración petrolera, programación lineal y redes eléctricas.',
          },
        ],
      },
      flashcards: [
        { id: 'fc-7-1', front: 'Aplicaciones de los sistemas lineales', back: 'Procesamiento digital de señales, análisis estructural, estimación, predicción, programación lineal y aproximación de problemas no lineales de análisis numérico.' },
        { id: 'fc-7-2', front: 'Exploración petrolera', back: 'Un barco que busca depósitos submarinos resuelve diariamente miles de sistemas de ecuaciones lineales por separado.' },
        { id: 'fc-7-3', front: '¿De dónde sale la información sísmica?', back: 'De ondas de choque submarinas creadas con explosiones de pistolas de aire, que rebotan en las rocas y se miden con geófonos conectados a cables bajo el barco.' },
        { id: 'fc-7-4', front: 'Programación lineal en aerolíneas', back: 'Itinerarios de tripulaciones de vuelo, monitoreo de ubicaciones de aviones y planificación de servicios de apoyo (mantenimiento y operaciones en terminal).' },
        { id: 'fc-7-5', front: 'Redes eléctricas', back: 'Los programas de simulación para diseñar circuitos y microchips con millones de transistores usan técnicas de álgebra lineal y sistemas de ecuaciones lineales.' },
        { id: 'fc-7-6', front: '¿Cuántas variables usan los modelos de programación lineal?', back: 'Cientos de variables, según el apunte, y sobre ellos se toman decisiones administrativas importantes.' },
      ],
    },
  ],
  pdfs: [
    { key: 'diofanticas-congruencias', label: 'Apunte · Ecuaciones diofánticas y de congruencias', path: 'pdfs/algebra-lineal/2-ecuaciones-diofanticas-congruencias.pdf' },
  ],
};
